/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package cz.csob.ency.workflow.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the EncyWorkflowInstance service. Represents a row in the &quot;ency_workflowinstance&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>cz.csob.ency.workflow.model.impl.EncyWorkflowInstanceModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>cz.csob.ency.workflow.model.impl.EncyWorkflowInstanceImpl</code>.
 * </p>
 *
 * @author Miroslav Čermák
 * @see EncyWorkflowInstance
 * @generated
 */
@ProviderType
public interface EncyWorkflowInstanceModel
	extends BaseModel<EncyWorkflowInstance>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ency workflow instance model instance should use the {@link EncyWorkflowInstance} interface instead.
	 */

	/**
	 * Returns the primary key of this ency workflow instance.
	 *
	 * @return the primary key of this ency workflow instance
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ency workflow instance.
	 *
	 * @param primaryKey the primary key of this ency workflow instance
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this ency workflow instance.
	 *
	 * @return the uuid of this ency workflow instance
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this ency workflow instance.
	 *
	 * @param uuid the uuid of this ency workflow instance
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the workflow instance ID of this ency workflow instance.
	 *
	 * @return the workflow instance ID of this ency workflow instance
	 */
	public long getWorkflowInstanceId();

	/**
	 * Sets the workflow instance ID of this ency workflow instance.
	 *
	 * @param workflowInstanceId the workflow instance ID of this ency workflow instance
	 */
	public void setWorkflowInstanceId(long workflowInstanceId);

	/**
	 * Returns the group ID of this ency workflow instance.
	 *
	 * @return the group ID of this ency workflow instance
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this ency workflow instance.
	 *
	 * @param groupId the group ID of this ency workflow instance
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this ency workflow instance.
	 *
	 * @return the company ID of this ency workflow instance
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this ency workflow instance.
	 *
	 * @param companyId the company ID of this ency workflow instance
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this ency workflow instance.
	 *
	 * @return the user ID of this ency workflow instance
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this ency workflow instance.
	 *
	 * @param userId the user ID of this ency workflow instance
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this ency workflow instance.
	 *
	 * @return the user uuid of this ency workflow instance
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this ency workflow instance.
	 *
	 * @param userUuid the user uuid of this ency workflow instance
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this ency workflow instance.
	 *
	 * @return the user name of this ency workflow instance
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this ency workflow instance.
	 *
	 * @param userName the user name of this ency workflow instance
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this ency workflow instance.
	 *
	 * @return the create date of this ency workflow instance
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this ency workflow instance.
	 *
	 * @param createDate the create date of this ency workflow instance
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this ency workflow instance.
	 *
	 * @return the modified date of this ency workflow instance
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this ency workflow instance.
	 *
	 * @param modifiedDate the modified date of this ency workflow instance
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the workflow ID of this ency workflow instance.
	 *
	 * @return the workflow ID of this ency workflow instance
	 */
	public long getWorkflowId();

	/**
	 * Sets the workflow ID of this ency workflow instance.
	 *
	 * @param workflowId the workflow ID of this ency workflow instance
	 */
	public void setWorkflowId(long workflowId);

	/**
	 * Returns the workflow version of this ency workflow instance.
	 *
	 * @return the workflow version of this ency workflow instance
	 */
	public long getWorkflowVersion();

	/**
	 * Sets the workflow version of this ency workflow instance.
	 *
	 * @param workflowVersion the workflow version of this ency workflow instance
	 */
	public void setWorkflowVersion(long workflowVersion);

	/**
	 * Returns the class name of this ency workflow instance.
	 *
	 * @return the class name of this ency workflow instance
	 */
	@AutoEscape
	public String getClassName();

	/**
	 * Sets the class name of this ency workflow instance.
	 *
	 * @param className the class name of this ency workflow instance
	 */
	public void setClassName(String className);

	/**
	 * Returns the class pk of this ency workflow instance.
	 *
	 * @return the class pk of this ency workflow instance
	 */
	public long getClassPK();

	/**
	 * Sets the class pk of this ency workflow instance.
	 *
	 * @param classPK the class pk of this ency workflow instance
	 */
	public void setClassPK(long classPK);

	/**
	 * Returns the workflow context of this ency workflow instance.
	 *
	 * @return the workflow context of this ency workflow instance
	 */
	@AutoEscape
	public String getWorkflowContext();

	/**
	 * Sets the workflow context of this ency workflow instance.
	 *
	 * @param workflowContext the workflow context of this ency workflow instance
	 */
	public void setWorkflowContext(String workflowContext);

	@Override
	public EncyWorkflowInstance cloneWithOriginalValues();

}