/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package cz.csob.ency.workflow.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the EncyWorkflowState service. Represents a row in the &quot;ency_workflowstate&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>cz.csob.ency.workflow.model.impl.EncyWorkflowStateModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>cz.csob.ency.workflow.model.impl.EncyWorkflowStateImpl</code>.
 * </p>
 *
 * @author Miroslav Čermák
 * @see EncyWorkflowState
 * @generated
 */
@ProviderType
public interface EncyWorkflowStateModel extends BaseModel<EncyWorkflowState> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ency workflow state model instance should use the {@link EncyWorkflowState} interface instead.
	 */

	/**
	 * Returns the primary key of this ency workflow state.
	 *
	 * @return the primary key of this ency workflow state
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ency workflow state.
	 *
	 * @param primaryKey the primary key of this ency workflow state
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this ency workflow state.
	 *
	 * @return the uuid of this ency workflow state
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this ency workflow state.
	 *
	 * @param uuid the uuid of this ency workflow state
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the state ID of this ency workflow state.
	 *
	 * @return the state ID of this ency workflow state
	 */
	public long getStateId();

	/**
	 * Sets the state ID of this ency workflow state.
	 *
	 * @param stateId the state ID of this ency workflow state
	 */
	public void setStateId(long stateId);

	/**
	 * Returns the workflow ID of this ency workflow state.
	 *
	 * @return the workflow ID of this ency workflow state
	 */
	public long getWorkflowId();

	/**
	 * Sets the workflow ID of this ency workflow state.
	 *
	 * @param workflowId the workflow ID of this ency workflow state
	 */
	public void setWorkflowId(long workflowId);

	/**
	 * Returns the name of this ency workflow state.
	 *
	 * @return the name of this ency workflow state
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this ency workflow state.
	 *
	 * @param name the name of this ency workflow state
	 */
	public void setName(String name);

	/**
	 * Returns the title of this ency workflow state.
	 *
	 * @return the title of this ency workflow state
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this ency workflow state.
	 *
	 * @param title the title of this ency workflow state
	 */
	public void setTitle(String title);

	/**
	 * Returns the description of this ency workflow state.
	 *
	 * @return the description of this ency workflow state
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this ency workflow state.
	 *
	 * @param description the description of this ency workflow state
	 */
	public void setDescription(String description);

	/**
	 * Returns the version of this ency workflow state.
	 *
	 * @return the version of this ency workflow state
	 */
	public long getVersion();

	/**
	 * Sets the version of this ency workflow state.
	 *
	 * @param version the version of this ency workflow state
	 */
	public void setVersion(long version);

	/**
	 * Returns the is initial of this ency workflow state.
	 *
	 * @return the is initial of this ency workflow state
	 */
	public Boolean getIsInitial();

	/**
	 * Sets the is initial of this ency workflow state.
	 *
	 * @param isInitial the is initial of this ency workflow state
	 */
	public void setIsInitial(Boolean isInitial);

	/**
	 * Returns the is final of this ency workflow state.
	 *
	 * @return the is final of this ency workflow state
	 */
	public Boolean getIsFinal();

	/**
	 * Sets the is final of this ency workflow state.
	 *
	 * @param isFinal the is final of this ency workflow state
	 */
	public void setIsFinal(Boolean isFinal);

	/**
	 * Returns the is editable of this ency workflow state.
	 *
	 * @return the is editable of this ency workflow state
	 */
	public Boolean getIsEditable();

	/**
	 * Sets the is editable of this ency workflow state.
	 *
	 * @param isEditable the is editable of this ency workflow state
	 */
	public void setIsEditable(Boolean isEditable);

	/**
	 * Returns the is searchable of this ency workflow state.
	 *
	 * @return the is searchable of this ency workflow state
	 */
	public Boolean getIsSearchable();

	/**
	 * Sets the is searchable of this ency workflow state.
	 *
	 * @param isSearchable the is searchable of this ency workflow state
	 */
	public void setIsSearchable(Boolean isSearchable);

	/**
	 * Returns the is permanent of this ency workflow state.
	 *
	 * @return the is permanent of this ency workflow state
	 */
	public Boolean getIsPermanent();

	/**
	 * Sets the is permanent of this ency workflow state.
	 *
	 * @param isPermanent the is permanent of this ency workflow state
	 */
	public void setIsPermanent(Boolean isPermanent);

	/**
	 * Returns the css icon of this ency workflow state.
	 *
	 * @return the css icon of this ency workflow state
	 */
	@AutoEscape
	public String getCssIcon();

	/**
	 * Sets the css icon of this ency workflow state.
	 *
	 * @param cssIcon the css icon of this ency workflow state
	 */
	public void setCssIcon(String cssIcon);

	/**
	 * Returns the css icon color of this ency workflow state.
	 *
	 * @return the css icon color of this ency workflow state
	 */
	@AutoEscape
	public String getCssIconColor();

	/**
	 * Sets the css icon color of this ency workflow state.
	 *
	 * @param cssIconColor the css icon color of this ency workflow state
	 */
	public void setCssIconColor(String cssIconColor);

	/**
	 * Returns the css label color of this ency workflow state.
	 *
	 * @return the css label color of this ency workflow state
	 */
	@AutoEscape
	public String getCssLabelColor();

	/**
	 * Sets the css label color of this ency workflow state.
	 *
	 * @param cssLabelColor the css label color of this ency workflow state
	 */
	public void setCssLabelColor(String cssLabelColor);

	/**
	 * Returns the active of this ency workflow state.
	 *
	 * @return the active of this ency workflow state
	 */
	public Boolean getActive();

	/**
	 * Sets the active of this ency workflow state.
	 *
	 * @param active the active of this ency workflow state
	 */
	public void setActive(Boolean active);

	/**
	 * Returns the create date of this ency workflow state.
	 *
	 * @return the create date of this ency workflow state
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this ency workflow state.
	 *
	 * @param createDate the create date of this ency workflow state
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this ency workflow state.
	 *
	 * @return the modified date of this ency workflow state
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this ency workflow state.
	 *
	 * @param modifiedDate the modified date of this ency workflow state
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public EncyWorkflowState cloneWithOriginalValues();

}