/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package cz.csob.ency.workflow.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the EncyWorkflowTransitionInstance service. Represents a row in the &quot;ency_workflowtransitioninstance&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>cz.csob.ency.workflow.model.impl.EncyWorkflowTransitionInstanceModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>cz.csob.ency.workflow.model.impl.EncyWorkflowTransitionInstanceImpl</code>.
 * </p>
 *
 * @author Miroslav Čermák
 * @see EncyWorkflowTransitionInstance
 * @generated
 */
@ProviderType
public interface EncyWorkflowTransitionInstanceModel
	extends BaseModel<EncyWorkflowTransitionInstance>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ency workflow transition instance model instance should use the {@link EncyWorkflowTransitionInstance} interface instead.
	 */

	/**
	 * Returns the primary key of this ency workflow transition instance.
	 *
	 * @return the primary key of this ency workflow transition instance
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ency workflow transition instance.
	 *
	 * @param primaryKey the primary key of this ency workflow transition instance
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this ency workflow transition instance.
	 *
	 * @return the uuid of this ency workflow transition instance
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this ency workflow transition instance.
	 *
	 * @param uuid the uuid of this ency workflow transition instance
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the transition instance ID of this ency workflow transition instance.
	 *
	 * @return the transition instance ID of this ency workflow transition instance
	 */
	public long getTransitionInstanceId();

	/**
	 * Sets the transition instance ID of this ency workflow transition instance.
	 *
	 * @param transitionInstanceId the transition instance ID of this ency workflow transition instance
	 */
	public void setTransitionInstanceId(long transitionInstanceId);

	/**
	 * Returns the transition ID of this ency workflow transition instance.
	 *
	 * @return the transition ID of this ency workflow transition instance
	 */
	public long getTransitionId();

	/**
	 * Sets the transition ID of this ency workflow transition instance.
	 *
	 * @param transitionId the transition ID of this ency workflow transition instance
	 */
	public void setTransitionId(long transitionId);

	/**
	 * Returns the state ID of this ency workflow transition instance.
	 *
	 * @return the state ID of this ency workflow transition instance
	 */
	public long getStateId();

	/**
	 * Sets the state ID of this ency workflow transition instance.
	 *
	 * @param stateId the state ID of this ency workflow transition instance
	 */
	public void setStateId(long stateId);

	/**
	 * Returns the state instance ID of this ency workflow transition instance.
	 *
	 * @return the state instance ID of this ency workflow transition instance
	 */
	public long getStateInstanceId();

	/**
	 * Sets the state instance ID of this ency workflow transition instance.
	 *
	 * @param stateInstanceId the state instance ID of this ency workflow transition instance
	 */
	public void setStateInstanceId(long stateInstanceId);

	/**
	 * Returns the workflow ID of this ency workflow transition instance.
	 *
	 * @return the workflow ID of this ency workflow transition instance
	 */
	public long getWorkflowId();

	/**
	 * Sets the workflow ID of this ency workflow transition instance.
	 *
	 * @param workflowId the workflow ID of this ency workflow transition instance
	 */
	public void setWorkflowId(long workflowId);

	/**
	 * Returns the workflow instance ID of this ency workflow transition instance.
	 *
	 * @return the workflow instance ID of this ency workflow transition instance
	 */
	public long getWorkflowInstanceId();

	/**
	 * Sets the workflow instance ID of this ency workflow transition instance.
	 *
	 * @param workflowInstanceId the workflow instance ID of this ency workflow transition instance
	 */
	public void setWorkflowInstanceId(long workflowInstanceId);

	/**
	 * Returns the version of this ency workflow transition instance.
	 *
	 * @return the version of this ency workflow transition instance
	 */
	public long getVersion();

	/**
	 * Sets the version of this ency workflow transition instance.
	 *
	 * @param version the version of this ency workflow transition instance
	 */
	public void setVersion(long version);

	/**
	 * Returns the comment of this ency workflow transition instance.
	 *
	 * @return the comment of this ency workflow transition instance
	 */
	@AutoEscape
	public String getComment();

	/**
	 * Sets the comment of this ency workflow transition instance.
	 *
	 * @param comment the comment of this ency workflow transition instance
	 */
	public void setComment(String comment);

	/**
	 * Returns the target state ID of this ency workflow transition instance.
	 *
	 * @return the target state ID of this ency workflow transition instance
	 */
	public long getTargetStateId();

	/**
	 * Sets the target state ID of this ency workflow transition instance.
	 *
	 * @param targetStateId the target state ID of this ency workflow transition instance
	 */
	public void setTargetStateId(long targetStateId);

	/**
	 * Returns the target state instance ID of this ency workflow transition instance.
	 *
	 * @return the target state instance ID of this ency workflow transition instance
	 */
	public long getTargetStateInstanceId();

	/**
	 * Sets the target state instance ID of this ency workflow transition instance.
	 *
	 * @param targetStateInstanceId the target state instance ID of this ency workflow transition instance
	 */
	public void setTargetStateInstanceId(long targetStateInstanceId);

	/**
	 * Returns the group ID of this ency workflow transition instance.
	 *
	 * @return the group ID of this ency workflow transition instance
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this ency workflow transition instance.
	 *
	 * @param groupId the group ID of this ency workflow transition instance
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this ency workflow transition instance.
	 *
	 * @return the company ID of this ency workflow transition instance
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this ency workflow transition instance.
	 *
	 * @param companyId the company ID of this ency workflow transition instance
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this ency workflow transition instance.
	 *
	 * @return the user ID of this ency workflow transition instance
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this ency workflow transition instance.
	 *
	 * @param userId the user ID of this ency workflow transition instance
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this ency workflow transition instance.
	 *
	 * @return the user uuid of this ency workflow transition instance
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this ency workflow transition instance.
	 *
	 * @param userUuid the user uuid of this ency workflow transition instance
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this ency workflow transition instance.
	 *
	 * @return the user name of this ency workflow transition instance
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this ency workflow transition instance.
	 *
	 * @param userName the user name of this ency workflow transition instance
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this ency workflow transition instance.
	 *
	 * @return the create date of this ency workflow transition instance
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this ency workflow transition instance.
	 *
	 * @param createDate the create date of this ency workflow transition instance
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the workflow context of this ency workflow transition instance.
	 *
	 * @return the workflow context of this ency workflow transition instance
	 */
	@AutoEscape
	public String getWorkflowContext();

	/**
	 * Sets the workflow context of this ency workflow transition instance.
	 *
	 * @param workflowContext the workflow context of this ency workflow transition instance
	 */
	public void setWorkflowContext(String workflowContext);

	@Override
	public EncyWorkflowTransitionInstance cloneWithOriginalValues();

}