/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package cz.csob.ency.cds.demands.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import cz.csob.ency.cds.demands.model.CdsDemand;
import cz.csob.ency.cds.demands.model.CdsDemandVersion;
import cz.csob.ency.cds.demands.model.CdsDemandVersionModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the CdsDemandVersion service. Represents a row in the &quot;CdsDemands_CdsDemandVersion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>CdsDemandVersionModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CdsDemandVersionImpl}.
 * </p>
 *
 * @author Miroslav Čermák
 * @see CdsDemandVersionImpl
 * @generated
 */
public class CdsDemandVersionModelImpl
	extends BaseModelImpl<CdsDemandVersion> implements CdsDemandVersionModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a cds demand version model instance should use the <code>CdsDemandVersion</code> interface instead.
	 */
	public static final String TABLE_NAME = "CdsDemands_CdsDemandVersion";

	public static final Object[][] TABLE_COLUMNS = {
		{"cdsDemandVersionId", Types.BIGINT}, {"version", Types.INTEGER},
		{"uuid_", Types.VARCHAR}, {"demandId", Types.BIGINT},
		{"title", Types.VARCHAR}, {"description", Types.VARCHAR},
		{"type_", Types.INTEGER}, {"priority", Types.INTEGER},
		{"requestedDelivery", Types.TIMESTAMP}, {"isGDPR", Types.BOOLEAN},
		{"gdprInfo", Types.VARCHAR}, {"fiveTracks", Types.VARCHAR},
		{"requestorId", Types.BIGINT}, {"requestorName", Types.VARCHAR},
		{"requestedForId", Types.BIGINT}, {"requestedForName", Types.VARCHAR},
		{"contactId", Types.BIGINT}, {"contactName", Types.VARCHAR},
		{"domainId", Types.BIGINT}, {"domainName", Types.VARCHAR},
		{"banId", Types.BIGINT}, {"banName", Types.VARCHAR},
		{"spocId", Types.BIGINT}, {"spocName", Types.VARCHAR},
		{"usReasoning", Types.VARCHAR}, {"usFrequencyOut", Types.INTEGER},
		{"usAccessDPM", Types.BOOLEAN}, {"usFolderDPM", Types.VARCHAR},
		{"usCreateFolderDPM", Types.BOOLEAN},
		{"usGestorFolderDPMId", Types.BIGINT},
		{"usGestorFolderDPMName", Types.VARCHAR},
		{"usDPMNotificationMail", Types.VARCHAR}, {"bioeId", Types.VARCHAR},
		{"bioeStateId", Types.INTEGER}, {"bioeStateName", Types.VARCHAR},
		{"workEstimate", Types.DOUBLE}, {"acceptedWorkEstimate", Types.DOUBLE},
		{"expectedDelivery", Types.TIMESTAMP},
		{"acceptedDelivery", Types.TIMESTAMP}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"urlTitle", Types.VARCHAR},
		{"state_", Types.VARCHAR}, {"stateByUserId", Types.BIGINT},
		{"stateByUserName", Types.VARCHAR}, {"stateDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("cdsDemandVersionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("version", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("demandId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("title", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("type_", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("priority", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("requestedDelivery", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("isGDPR", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("gdprInfo", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("fiveTracks", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("requestorId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("requestorName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("requestedForId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("requestedForName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("contactId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("contactName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("domainId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("domainName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("banId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("banName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("spocId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("spocName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("usReasoning", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("usFrequencyOut", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("usAccessDPM", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("usFolderDPM", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("usCreateFolderDPM", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("usGestorFolderDPMId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("usGestorFolderDPMName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("usDPMNotificationMail", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("bioeId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("bioeStateId", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("bioeStateName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("workEstimate", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("acceptedWorkEstimate", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("expectedDelivery", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("acceptedDelivery", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("urlTitle", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("state_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("stateByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("stateByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("stateDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table CdsDemands_CdsDemandVersion (cdsDemandVersionId LONG not null primary key,version INTEGER,uuid_ VARCHAR(75) null,demandId LONG,title VARCHAR(500) null,description TEXT null,type_ INTEGER,priority INTEGER,requestedDelivery DATE null,isGDPR BOOLEAN,gdprInfo VARCHAR(512) null,fiveTracks VARCHAR(512) null,requestorId LONG,requestorName VARCHAR(256) null,requestedForId LONG,requestedForName VARCHAR(256) null,contactId LONG,contactName VARCHAR(256) null,domainId LONG,domainName VARCHAR(256) null,banId LONG,banName VARCHAR(256) null,spocId LONG,spocName VARCHAR(256) null,usReasoning VARCHAR(512) null,usFrequencyOut INTEGER,usAccessDPM BOOLEAN,usFolderDPM VARCHAR(256) null,usCreateFolderDPM BOOLEAN,usGestorFolderDPMId LONG,usGestorFolderDPMName VARCHAR(256) null,usDPMNotificationMail VARCHAR(75) null,bioeId VARCHAR(20) null,bioeStateId INTEGER,bioeStateName VARCHAR(75) null,workEstimate DOUBLE,acceptedWorkEstimate DOUBLE,expectedDelivery DATE null,acceptedDelivery DATE null,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(256) null,createDate DATE null,modifiedDate DATE null,urlTitle VARCHAR(256) null,state_ VARCHAR(75) null,stateByUserId LONG,stateByUserName VARCHAR(75) null,stateDate DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table CdsDemands_CdsDemandVersion";

	public static final String ORDER_BY_JPQL =
		" ORDER BY cdsDemandVersion.version DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY CdsDemands_CdsDemandVersion.version DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long DEMANDID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long DOMAINID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long USERID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long VERSION_COLUMN_BITMASK = 64L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public CdsDemandVersionModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _cdsDemandVersionId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCdsDemandVersionId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _cdsDemandVersionId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CdsDemandVersion.class;
	}

	@Override
	public String getModelClassName() {
		return CdsDemandVersion.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<CdsDemandVersion, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<CdsDemandVersion, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CdsDemandVersion, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((CdsDemandVersion)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<CdsDemandVersion, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<CdsDemandVersion, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(CdsDemandVersion)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<CdsDemandVersion, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<CdsDemandVersion, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<CdsDemandVersion, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<CdsDemandVersion, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<CdsDemandVersion, Object>>
			attributeGetterFunctions =
				new LinkedHashMap<String, Function<CdsDemandVersion, Object>>();
		Map<String, BiConsumer<CdsDemandVersion, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<CdsDemandVersion, ?>>();

		attributeGetterFunctions.put(
			"cdsDemandVersionId", CdsDemandVersion::getCdsDemandVersionId);
		attributeSetterBiConsumers.put(
			"cdsDemandVersionId",
			(BiConsumer<CdsDemandVersion, Long>)
				CdsDemandVersion::setCdsDemandVersionId);
		attributeGetterFunctions.put("version", CdsDemandVersion::getVersion);
		attributeSetterBiConsumers.put(
			"version",
			(BiConsumer<CdsDemandVersion, Integer>)
				CdsDemandVersion::setVersion);
		attributeGetterFunctions.put("uuid", CdsDemandVersion::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<CdsDemandVersion, String>)CdsDemandVersion::setUuid);
		attributeGetterFunctions.put("demandId", CdsDemandVersion::getDemandId);
		attributeSetterBiConsumers.put(
			"demandId",
			(BiConsumer<CdsDemandVersion, Long>)CdsDemandVersion::setDemandId);
		attributeGetterFunctions.put("title", CdsDemandVersion::getTitle);
		attributeSetterBiConsumers.put(
			"title",
			(BiConsumer<CdsDemandVersion, String>)CdsDemandVersion::setTitle);
		attributeGetterFunctions.put(
			"description", CdsDemandVersion::getDescription);
		attributeSetterBiConsumers.put(
			"description",
			(BiConsumer<CdsDemandVersion, String>)
				CdsDemandVersion::setDescription);
		attributeGetterFunctions.put("type", CdsDemandVersion::getType);
		attributeSetterBiConsumers.put(
			"type",
			(BiConsumer<CdsDemandVersion, Integer>)CdsDemandVersion::setType);
		attributeGetterFunctions.put("priority", CdsDemandVersion::getPriority);
		attributeSetterBiConsumers.put(
			"priority",
			(BiConsumer<CdsDemandVersion, Integer>)
				CdsDemandVersion::setPriority);
		attributeGetterFunctions.put(
			"requestedDelivery", CdsDemandVersion::getRequestedDelivery);
		attributeSetterBiConsumers.put(
			"requestedDelivery",
			(BiConsumer<CdsDemandVersion, Date>)
				CdsDemandVersion::setRequestedDelivery);
		attributeGetterFunctions.put("isGDPR", CdsDemandVersion::getIsGDPR);
		attributeSetterBiConsumers.put(
			"isGDPR",
			(BiConsumer<CdsDemandVersion, Boolean>)CdsDemandVersion::setIsGDPR);
		attributeGetterFunctions.put("gdprInfo", CdsDemandVersion::getGdprInfo);
		attributeSetterBiConsumers.put(
			"gdprInfo",
			(BiConsumer<CdsDemandVersion, String>)
				CdsDemandVersion::setGdprInfo);
		attributeGetterFunctions.put(
			"fiveTracks", CdsDemandVersion::getFiveTracks);
		attributeSetterBiConsumers.put(
			"fiveTracks",
			(BiConsumer<CdsDemandVersion, String>)
				CdsDemandVersion::setFiveTracks);
		attributeGetterFunctions.put(
			"requestorId", CdsDemandVersion::getRequestorId);
		attributeSetterBiConsumers.put(
			"requestorId",
			(BiConsumer<CdsDemandVersion, Long>)
				CdsDemandVersion::setRequestorId);
		attributeGetterFunctions.put(
			"requestorName", CdsDemandVersion::getRequestorName);
		attributeSetterBiConsumers.put(
			"requestorName",
			(BiConsumer<CdsDemandVersion, String>)
				CdsDemandVersion::setRequestorName);
		attributeGetterFunctions.put(
			"requestedForId", CdsDemandVersion::getRequestedForId);
		attributeSetterBiConsumers.put(
			"requestedForId",
			(BiConsumer<CdsDemandVersion, Long>)
				CdsDemandVersion::setRequestedForId);
		attributeGetterFunctions.put(
			"requestedForName", CdsDemandVersion::getRequestedForName);
		attributeSetterBiConsumers.put(
			"requestedForName",
			(BiConsumer<CdsDemandVersion, String>)
				CdsDemandVersion::setRequestedForName);
		attributeGetterFunctions.put(
			"contactId", CdsDemandVersion::getContactId);
		attributeSetterBiConsumers.put(
			"contactId",
			(BiConsumer<CdsDemandVersion, Long>)CdsDemandVersion::setContactId);
		attributeGetterFunctions.put(
			"contactName", CdsDemandVersion::getContactName);
		attributeSetterBiConsumers.put(
			"contactName",
			(BiConsumer<CdsDemandVersion, String>)
				CdsDemandVersion::setContactName);
		attributeGetterFunctions.put("domainId", CdsDemandVersion::getDomainId);
		attributeSetterBiConsumers.put(
			"domainId",
			(BiConsumer<CdsDemandVersion, Long>)CdsDemandVersion::setDomainId);
		attributeGetterFunctions.put(
			"domainName", CdsDemandVersion::getDomainName);
		attributeSetterBiConsumers.put(
			"domainName",
			(BiConsumer<CdsDemandVersion, String>)
				CdsDemandVersion::setDomainName);
		attributeGetterFunctions.put("banId", CdsDemandVersion::getBanId);
		attributeSetterBiConsumers.put(
			"banId",
			(BiConsumer<CdsDemandVersion, Long>)CdsDemandVersion::setBanId);
		attributeGetterFunctions.put("banName", CdsDemandVersion::getBanName);
		attributeSetterBiConsumers.put(
			"banName",
			(BiConsumer<CdsDemandVersion, String>)CdsDemandVersion::setBanName);
		attributeGetterFunctions.put("spocId", CdsDemandVersion::getSpocId);
		attributeSetterBiConsumers.put(
			"spocId",
			(BiConsumer<CdsDemandVersion, Long>)CdsDemandVersion::setSpocId);
		attributeGetterFunctions.put("spocName", CdsDemandVersion::getSpocName);
		attributeSetterBiConsumers.put(
			"spocName",
			(BiConsumer<CdsDemandVersion, String>)
				CdsDemandVersion::setSpocName);
		attributeGetterFunctions.put(
			"usReasoning", CdsDemandVersion::getUsReasoning);
		attributeSetterBiConsumers.put(
			"usReasoning",
			(BiConsumer<CdsDemandVersion, String>)
				CdsDemandVersion::setUsReasoning);
		attributeGetterFunctions.put(
			"usFrequencyOut", CdsDemandVersion::getUsFrequencyOut);
		attributeSetterBiConsumers.put(
			"usFrequencyOut",
			(BiConsumer<CdsDemandVersion, Integer>)
				CdsDemandVersion::setUsFrequencyOut);
		attributeGetterFunctions.put(
			"usAccessDPM", CdsDemandVersion::getUsAccessDPM);
		attributeSetterBiConsumers.put(
			"usAccessDPM",
			(BiConsumer<CdsDemandVersion, Boolean>)
				CdsDemandVersion::setUsAccessDPM);
		attributeGetterFunctions.put(
			"usFolderDPM", CdsDemandVersion::getUsFolderDPM);
		attributeSetterBiConsumers.put(
			"usFolderDPM",
			(BiConsumer<CdsDemandVersion, String>)
				CdsDemandVersion::setUsFolderDPM);
		attributeGetterFunctions.put(
			"usCreateFolderDPM", CdsDemandVersion::getUsCreateFolderDPM);
		attributeSetterBiConsumers.put(
			"usCreateFolderDPM",
			(BiConsumer<CdsDemandVersion, Boolean>)
				CdsDemandVersion::setUsCreateFolderDPM);
		attributeGetterFunctions.put(
			"usGestorFolderDPMId", CdsDemandVersion::getUsGestorFolderDPMId);
		attributeSetterBiConsumers.put(
			"usGestorFolderDPMId",
			(BiConsumer<CdsDemandVersion, Long>)
				CdsDemandVersion::setUsGestorFolderDPMId);
		attributeGetterFunctions.put(
			"usGestorFolderDPMName",
			CdsDemandVersion::getUsGestorFolderDPMName);
		attributeSetterBiConsumers.put(
			"usGestorFolderDPMName",
			(BiConsumer<CdsDemandVersion, String>)
				CdsDemandVersion::setUsGestorFolderDPMName);
		attributeGetterFunctions.put(
			"usDPMNotificationMail",
			CdsDemandVersion::getUsDPMNotificationMail);
		attributeSetterBiConsumers.put(
			"usDPMNotificationMail",
			(BiConsumer<CdsDemandVersion, String>)
				CdsDemandVersion::setUsDPMNotificationMail);
		attributeGetterFunctions.put("bioeId", CdsDemandVersion::getBioeId);
		attributeSetterBiConsumers.put(
			"bioeId",
			(BiConsumer<CdsDemandVersion, String>)CdsDemandVersion::setBioeId);
		attributeGetterFunctions.put(
			"bioeStateId", CdsDemandVersion::getBioeStateId);
		attributeSetterBiConsumers.put(
			"bioeStateId",
			(BiConsumer<CdsDemandVersion, Short>)
				CdsDemandVersion::setBioeStateId);
		attributeGetterFunctions.put(
			"bioeStateName", CdsDemandVersion::getBioeStateName);
		attributeSetterBiConsumers.put(
			"bioeStateName",
			(BiConsumer<CdsDemandVersion, String>)
				CdsDemandVersion::setBioeStateName);
		attributeGetterFunctions.put(
			"workEstimate", CdsDemandVersion::getWorkEstimate);
		attributeSetterBiConsumers.put(
			"workEstimate",
			(BiConsumer<CdsDemandVersion, Double>)
				CdsDemandVersion::setWorkEstimate);
		attributeGetterFunctions.put(
			"acceptedWorkEstimate", CdsDemandVersion::getAcceptedWorkEstimate);
		attributeSetterBiConsumers.put(
			"acceptedWorkEstimate",
			(BiConsumer<CdsDemandVersion, Double>)
				CdsDemandVersion::setAcceptedWorkEstimate);
		attributeGetterFunctions.put(
			"expectedDelivery", CdsDemandVersion::getExpectedDelivery);
		attributeSetterBiConsumers.put(
			"expectedDelivery",
			(BiConsumer<CdsDemandVersion, Date>)
				CdsDemandVersion::setExpectedDelivery);
		attributeGetterFunctions.put(
			"acceptedDelivery", CdsDemandVersion::getAcceptedDelivery);
		attributeSetterBiConsumers.put(
			"acceptedDelivery",
			(BiConsumer<CdsDemandVersion, Date>)
				CdsDemandVersion::setAcceptedDelivery);
		attributeGetterFunctions.put("groupId", CdsDemandVersion::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<CdsDemandVersion, Long>)CdsDemandVersion::setGroupId);
		attributeGetterFunctions.put(
			"companyId", CdsDemandVersion::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<CdsDemandVersion, Long>)CdsDemandVersion::setCompanyId);
		attributeGetterFunctions.put("userId", CdsDemandVersion::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<CdsDemandVersion, Long>)CdsDemandVersion::setUserId);
		attributeGetterFunctions.put("userName", CdsDemandVersion::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<CdsDemandVersion, String>)
				CdsDemandVersion::setUserName);
		attributeGetterFunctions.put(
			"createDate", CdsDemandVersion::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<CdsDemandVersion, Date>)
				CdsDemandVersion::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", CdsDemandVersion::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<CdsDemandVersion, Date>)
				CdsDemandVersion::setModifiedDate);
		attributeGetterFunctions.put("urlTitle", CdsDemandVersion::getUrlTitle);
		attributeSetterBiConsumers.put(
			"urlTitle",
			(BiConsumer<CdsDemandVersion, String>)
				CdsDemandVersion::setUrlTitle);
		attributeGetterFunctions.put("state", CdsDemandVersion::getState);
		attributeSetterBiConsumers.put(
			"state",
			(BiConsumer<CdsDemandVersion, String>)CdsDemandVersion::setState);
		attributeGetterFunctions.put(
			"stateByUserId", CdsDemandVersion::getStateByUserId);
		attributeSetterBiConsumers.put(
			"stateByUserId",
			(BiConsumer<CdsDemandVersion, Long>)
				CdsDemandVersion::setStateByUserId);
		attributeGetterFunctions.put(
			"stateByUserName", CdsDemandVersion::getStateByUserName);
		attributeSetterBiConsumers.put(
			"stateByUserName",
			(BiConsumer<CdsDemandVersion, String>)
				CdsDemandVersion::setStateByUserName);
		attributeGetterFunctions.put(
			"stateDate", CdsDemandVersion::getStateDate);
		attributeSetterBiConsumers.put(
			"stateDate",
			(BiConsumer<CdsDemandVersion, Date>)CdsDemandVersion::setStateDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getVersionedModelId() {
		return getDemandId();
	}

	@Override
	public void populateVersionedModel(CdsDemand cdsDemand) {
		cdsDemand.setUuid(getUuid());
		cdsDemand.setTitle(getTitle());
		cdsDemand.setDescription(getDescription());
		cdsDemand.setType(getType());
		cdsDemand.setPriority(getPriority());
		cdsDemand.setRequestedDelivery(getRequestedDelivery());
		cdsDemand.setIsGDPR(getIsGDPR());
		cdsDemand.setGdprInfo(getGdprInfo());
		cdsDemand.setFiveTracks(getFiveTracks());
		cdsDemand.setRequestorId(getRequestorId());
		cdsDemand.setRequestorName(getRequestorName());
		cdsDemand.setRequestedForId(getRequestedForId());
		cdsDemand.setRequestedForName(getRequestedForName());
		cdsDemand.setContactId(getContactId());
		cdsDemand.setContactName(getContactName());
		cdsDemand.setDomainId(getDomainId());
		cdsDemand.setDomainName(getDomainName());
		cdsDemand.setBanId(getBanId());
		cdsDemand.setBanName(getBanName());
		cdsDemand.setSpocId(getSpocId());
		cdsDemand.setSpocName(getSpocName());
		cdsDemand.setUsReasoning(getUsReasoning());
		cdsDemand.setUsFrequencyOut(getUsFrequencyOut());
		cdsDemand.setUsAccessDPM(getUsAccessDPM());
		cdsDemand.setUsFolderDPM(getUsFolderDPM());
		cdsDemand.setUsCreateFolderDPM(getUsCreateFolderDPM());
		cdsDemand.setUsGestorFolderDPMId(getUsGestorFolderDPMId());
		cdsDemand.setUsGestorFolderDPMName(getUsGestorFolderDPMName());
		cdsDemand.setUsDPMNotificationMail(getUsDPMNotificationMail());
		cdsDemand.setBioeId(getBioeId());
		cdsDemand.setBioeStateId(getBioeStateId());
		cdsDemand.setBioeStateName(getBioeStateName());
		cdsDemand.setWorkEstimate(getWorkEstimate());
		cdsDemand.setAcceptedWorkEstimate(getAcceptedWorkEstimate());
		cdsDemand.setExpectedDelivery(getExpectedDelivery());
		cdsDemand.setAcceptedDelivery(getAcceptedDelivery());
		cdsDemand.setGroupId(getGroupId());
		cdsDemand.setCompanyId(getCompanyId());
		cdsDemand.setUserId(getUserId());
		cdsDemand.setUserName(getUserName());
		cdsDemand.setCreateDate(getCreateDate());
		cdsDemand.setModifiedDate(getModifiedDate());
		cdsDemand.setUrlTitle(getUrlTitle());
		cdsDemand.setState(getState());
		cdsDemand.setStateByUserId(getStateByUserId());
		cdsDemand.setStateByUserName(getStateByUserName());
		cdsDemand.setStateDate(getStateDate());
	}

	@Override
	public void setVersionedModelId(long demandId) {
		setDemandId(demandId);
	}

	@Override
	public CdsDemand toVersionedModel() {
		CdsDemand cdsDemand = new CdsDemandImpl();

		cdsDemand.setPrimaryKey(getVersionedModelId());
		cdsDemand.setHeadId(-getVersionedModelId());

		populateVersionedModel(cdsDemand);

		return cdsDemand;
	}

	@Override
	public long getCdsDemandVersionId() {
		return _cdsDemandVersionId;
	}

	@Override
	public void setCdsDemandVersionId(long cdsDemandVersionId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_cdsDemandVersionId = cdsDemandVersionId;
	}

	@Override
	public int getVersion() {
		return _version;
	}

	@Override
	public void setVersion(int version) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_version = version;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalVersion() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("version"));
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@Override
	public long getDemandId() {
		return _demandId;
	}

	@Override
	public void setDemandId(long demandId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_demandId = demandId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalDemandId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("demandId"));
	}

	@Override
	public String getTitle() {
		if (_title == null) {
			return "";
		}
		else {
			return _title;
		}
	}

	@Override
	public void setTitle(String title) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_title = title;
	}

	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_description = description;
	}

	@Override
	public int getType() {
		return _type;
	}

	@Override
	public void setType(int type) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_type = type;
	}

	@Override
	public int getPriority() {
		return _priority;
	}

	@Override
	public void setPriority(int priority) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_priority = priority;
	}

	@Override
	public Date getRequestedDelivery() {
		return _requestedDelivery;
	}

	@Override
	public void setRequestedDelivery(Date requestedDelivery) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_requestedDelivery = requestedDelivery;
	}

	@Override
	public boolean getIsGDPR() {
		return _isGDPR;
	}

	@Override
	public boolean isIsGDPR() {
		return _isGDPR;
	}

	@Override
	public void setIsGDPR(boolean isGDPR) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_isGDPR = isGDPR;
	}

	@Override
	public String getGdprInfo() {
		if (_gdprInfo == null) {
			return "";
		}
		else {
			return _gdprInfo;
		}
	}

	@Override
	public void setGdprInfo(String gdprInfo) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_gdprInfo = gdprInfo;
	}

	@Override
	public String getFiveTracks() {
		if (_fiveTracks == null) {
			return "";
		}
		else {
			return _fiveTracks;
		}
	}

	@Override
	public void setFiveTracks(String fiveTracks) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fiveTracks = fiveTracks;
	}

	@Override
	public long getRequestorId() {
		return _requestorId;
	}

	@Override
	public void setRequestorId(long requestorId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_requestorId = requestorId;
	}

	@Override
	public String getRequestorName() {
		if (_requestorName == null) {
			return "";
		}
		else {
			return _requestorName;
		}
	}

	@Override
	public void setRequestorName(String requestorName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_requestorName = requestorName;
	}

	@Override
	public long getRequestedForId() {
		return _requestedForId;
	}

	@Override
	public void setRequestedForId(long requestedForId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_requestedForId = requestedForId;
	}

	@Override
	public String getRequestedForName() {
		if (_requestedForName == null) {
			return "";
		}
		else {
			return _requestedForName;
		}
	}

	@Override
	public void setRequestedForName(String requestedForName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_requestedForName = requestedForName;
	}

	@Override
	public long getContactId() {
		return _contactId;
	}

	@Override
	public void setContactId(long contactId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_contactId = contactId;
	}

	@Override
	public String getContactName() {
		if (_contactName == null) {
			return "";
		}
		else {
			return _contactName;
		}
	}

	@Override
	public void setContactName(String contactName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_contactName = contactName;
	}

	@Override
	public long getDomainId() {
		return _domainId;
	}

	@Override
	public void setDomainId(long domainId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_domainId = domainId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalDomainId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("domainId"));
	}

	@Override
	public String getDomainName() {
		if (_domainName == null) {
			return "";
		}
		else {
			return _domainName;
		}
	}

	@Override
	public void setDomainName(String domainName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_domainName = domainName;
	}

	@Override
	public long getBanId() {
		return _banId;
	}

	@Override
	public void setBanId(long banId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_banId = banId;
	}

	@Override
	public String getBanName() {
		if (_banName == null) {
			return "";
		}
		else {
			return _banName;
		}
	}

	@Override
	public void setBanName(String banName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_banName = banName;
	}

	@Override
	public long getSpocId() {
		return _spocId;
	}

	@Override
	public void setSpocId(long spocId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_spocId = spocId;
	}

	@Override
	public String getSpocName() {
		if (_spocName == null) {
			return "";
		}
		else {
			return _spocName;
		}
	}

	@Override
	public void setSpocName(String spocName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_spocName = spocName;
	}

	@Override
	public String getUsReasoning() {
		if (_usReasoning == null) {
			return "";
		}
		else {
			return _usReasoning;
		}
	}

	@Override
	public void setUsReasoning(String usReasoning) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_usReasoning = usReasoning;
	}

	@Override
	public int getUsFrequencyOut() {
		return _usFrequencyOut;
	}

	@Override
	public void setUsFrequencyOut(int usFrequencyOut) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_usFrequencyOut = usFrequencyOut;
	}

	@Override
	public boolean getUsAccessDPM() {
		return _usAccessDPM;
	}

	@Override
	public boolean isUsAccessDPM() {
		return _usAccessDPM;
	}

	@Override
	public void setUsAccessDPM(boolean usAccessDPM) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_usAccessDPM = usAccessDPM;
	}

	@Override
	public String getUsFolderDPM() {
		if (_usFolderDPM == null) {
			return "";
		}
		else {
			return _usFolderDPM;
		}
	}

	@Override
	public void setUsFolderDPM(String usFolderDPM) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_usFolderDPM = usFolderDPM;
	}

	@Override
	public boolean getUsCreateFolderDPM() {
		return _usCreateFolderDPM;
	}

	@Override
	public boolean isUsCreateFolderDPM() {
		return _usCreateFolderDPM;
	}

	@Override
	public void setUsCreateFolderDPM(boolean usCreateFolderDPM) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_usCreateFolderDPM = usCreateFolderDPM;
	}

	@Override
	public long getUsGestorFolderDPMId() {
		return _usGestorFolderDPMId;
	}

	@Override
	public void setUsGestorFolderDPMId(long usGestorFolderDPMId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_usGestorFolderDPMId = usGestorFolderDPMId;
	}

	@Override
	public String getUsGestorFolderDPMName() {
		if (_usGestorFolderDPMName == null) {
			return "";
		}
		else {
			return _usGestorFolderDPMName;
		}
	}

	@Override
	public void setUsGestorFolderDPMName(String usGestorFolderDPMName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_usGestorFolderDPMName = usGestorFolderDPMName;
	}

	@Override
	public String getUsDPMNotificationMail() {
		if (_usDPMNotificationMail == null) {
			return "";
		}
		else {
			return _usDPMNotificationMail;
		}
	}

	@Override
	public void setUsDPMNotificationMail(String usDPMNotificationMail) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_usDPMNotificationMail = usDPMNotificationMail;
	}

	@Override
	public String getBioeId() {
		if (_bioeId == null) {
			return "";
		}
		else {
			return _bioeId;
		}
	}

	@Override
	public void setBioeId(String bioeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_bioeId = bioeId;
	}

	@Override
	public short getBioeStateId() {
		return _bioeStateId;
	}

	@Override
	public void setBioeStateId(short bioeStateId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_bioeStateId = bioeStateId;
	}

	@Override
	public String getBioeStateName() {
		if (_bioeStateName == null) {
			return "";
		}
		else {
			return _bioeStateName;
		}
	}

	@Override
	public void setBioeStateName(String bioeStateName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_bioeStateName = bioeStateName;
	}

	@Override
	public double getWorkEstimate() {
		return _workEstimate;
	}

	@Override
	public void setWorkEstimate(double workEstimate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_workEstimate = workEstimate;
	}

	@Override
	public double getAcceptedWorkEstimate() {
		return _acceptedWorkEstimate;
	}

	@Override
	public void setAcceptedWorkEstimate(double acceptedWorkEstimate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_acceptedWorkEstimate = acceptedWorkEstimate;
	}

	@Override
	public Date getExpectedDelivery() {
		return _expectedDelivery;
	}

	@Override
	public void setExpectedDelivery(Date expectedDelivery) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_expectedDelivery = expectedDelivery;
	}

	@Override
	public Date getAcceptedDelivery() {
		return _acceptedDelivery;
	}

	@Override
	public void setAcceptedDelivery(Date acceptedDelivery) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_acceptedDelivery = acceptedDelivery;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalUserId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("userId"));
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getUrlTitle() {
		if (_urlTitle == null) {
			return "";
		}
		else {
			return _urlTitle;
		}
	}

	@Override
	public void setUrlTitle(String urlTitle) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_urlTitle = urlTitle;
	}

	@Override
	public String getState() {
		if (_state == null) {
			return "";
		}
		else {
			return _state;
		}
	}

	@Override
	public void setState(String state) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_state = state;
	}

	@Override
	public long getStateByUserId() {
		return _stateByUserId;
	}

	@Override
	public void setStateByUserId(long stateByUserId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_stateByUserId = stateByUserId;
	}

	@Override
	public String getStateByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStateByUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setStateByUserUuid(String stateByUserUuid) {
	}

	@Override
	public String getStateByUserName() {
		if (_stateByUserName == null) {
			return "";
		}
		else {
			return _stateByUserName;
		}
	}

	@Override
	public void setStateByUserName(String stateByUserName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_stateByUserName = stateByUserName;
	}

	@Override
	public Date getStateDate() {
		return _stateDate;
	}

	@Override
	public void setStateDate(Date stateDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_stateDate = stateDate;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), CdsDemandVersion.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CdsDemandVersion toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, CdsDemandVersion>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CdsDemandVersionImpl cdsDemandVersionImpl = new CdsDemandVersionImpl();

		cdsDemandVersionImpl.setCdsDemandVersionId(getCdsDemandVersionId());
		cdsDemandVersionImpl.setVersion(getVersion());
		cdsDemandVersionImpl.setUuid(getUuid());
		cdsDemandVersionImpl.setDemandId(getDemandId());
		cdsDemandVersionImpl.setTitle(getTitle());
		cdsDemandVersionImpl.setDescription(getDescription());
		cdsDemandVersionImpl.setType(getType());
		cdsDemandVersionImpl.setPriority(getPriority());
		cdsDemandVersionImpl.setRequestedDelivery(getRequestedDelivery());
		cdsDemandVersionImpl.setIsGDPR(isIsGDPR());
		cdsDemandVersionImpl.setGdprInfo(getGdprInfo());
		cdsDemandVersionImpl.setFiveTracks(getFiveTracks());
		cdsDemandVersionImpl.setRequestorId(getRequestorId());
		cdsDemandVersionImpl.setRequestorName(getRequestorName());
		cdsDemandVersionImpl.setRequestedForId(getRequestedForId());
		cdsDemandVersionImpl.setRequestedForName(getRequestedForName());
		cdsDemandVersionImpl.setContactId(getContactId());
		cdsDemandVersionImpl.setContactName(getContactName());
		cdsDemandVersionImpl.setDomainId(getDomainId());
		cdsDemandVersionImpl.setDomainName(getDomainName());
		cdsDemandVersionImpl.setBanId(getBanId());
		cdsDemandVersionImpl.setBanName(getBanName());
		cdsDemandVersionImpl.setSpocId(getSpocId());
		cdsDemandVersionImpl.setSpocName(getSpocName());
		cdsDemandVersionImpl.setUsReasoning(getUsReasoning());
		cdsDemandVersionImpl.setUsFrequencyOut(getUsFrequencyOut());
		cdsDemandVersionImpl.setUsAccessDPM(isUsAccessDPM());
		cdsDemandVersionImpl.setUsFolderDPM(getUsFolderDPM());
		cdsDemandVersionImpl.setUsCreateFolderDPM(isUsCreateFolderDPM());
		cdsDemandVersionImpl.setUsGestorFolderDPMId(getUsGestorFolderDPMId());
		cdsDemandVersionImpl.setUsGestorFolderDPMName(
			getUsGestorFolderDPMName());
		cdsDemandVersionImpl.setUsDPMNotificationMail(
			getUsDPMNotificationMail());
		cdsDemandVersionImpl.setBioeId(getBioeId());
		cdsDemandVersionImpl.setBioeStateId(getBioeStateId());
		cdsDemandVersionImpl.setBioeStateName(getBioeStateName());
		cdsDemandVersionImpl.setWorkEstimate(getWorkEstimate());
		cdsDemandVersionImpl.setAcceptedWorkEstimate(getAcceptedWorkEstimate());
		cdsDemandVersionImpl.setExpectedDelivery(getExpectedDelivery());
		cdsDemandVersionImpl.setAcceptedDelivery(getAcceptedDelivery());
		cdsDemandVersionImpl.setGroupId(getGroupId());
		cdsDemandVersionImpl.setCompanyId(getCompanyId());
		cdsDemandVersionImpl.setUserId(getUserId());
		cdsDemandVersionImpl.setUserName(getUserName());
		cdsDemandVersionImpl.setCreateDate(getCreateDate());
		cdsDemandVersionImpl.setModifiedDate(getModifiedDate());
		cdsDemandVersionImpl.setUrlTitle(getUrlTitle());
		cdsDemandVersionImpl.setState(getState());
		cdsDemandVersionImpl.setStateByUserId(getStateByUserId());
		cdsDemandVersionImpl.setStateByUserName(getStateByUserName());
		cdsDemandVersionImpl.setStateDate(getStateDate());

		cdsDemandVersionImpl.resetOriginalValues();

		return cdsDemandVersionImpl;
	}

	@Override
	public CdsDemandVersion cloneWithOriginalValues() {
		CdsDemandVersionImpl cdsDemandVersionImpl = new CdsDemandVersionImpl();

		cdsDemandVersionImpl.setCdsDemandVersionId(
			this.<Long>getColumnOriginalValue("cdsDemandVersionId"));
		cdsDemandVersionImpl.setVersion(
			this.<Integer>getColumnOriginalValue("version"));
		cdsDemandVersionImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		cdsDemandVersionImpl.setDemandId(
			this.<Long>getColumnOriginalValue("demandId"));
		cdsDemandVersionImpl.setTitle(
			this.<String>getColumnOriginalValue("title"));
		cdsDemandVersionImpl.setDescription(
			this.<String>getColumnOriginalValue("description"));
		cdsDemandVersionImpl.setType(
			this.<Integer>getColumnOriginalValue("type_"));
		cdsDemandVersionImpl.setPriority(
			this.<Integer>getColumnOriginalValue("priority"));
		cdsDemandVersionImpl.setRequestedDelivery(
			this.<Date>getColumnOriginalValue("requestedDelivery"));
		cdsDemandVersionImpl.setIsGDPR(
			this.<Boolean>getColumnOriginalValue("isGDPR"));
		cdsDemandVersionImpl.setGdprInfo(
			this.<String>getColumnOriginalValue("gdprInfo"));
		cdsDemandVersionImpl.setFiveTracks(
			this.<String>getColumnOriginalValue("fiveTracks"));
		cdsDemandVersionImpl.setRequestorId(
			this.<Long>getColumnOriginalValue("requestorId"));
		cdsDemandVersionImpl.setRequestorName(
			this.<String>getColumnOriginalValue("requestorName"));
		cdsDemandVersionImpl.setRequestedForId(
			this.<Long>getColumnOriginalValue("requestedForId"));
		cdsDemandVersionImpl.setRequestedForName(
			this.<String>getColumnOriginalValue("requestedForName"));
		cdsDemandVersionImpl.setContactId(
			this.<Long>getColumnOriginalValue("contactId"));
		cdsDemandVersionImpl.setContactName(
			this.<String>getColumnOriginalValue("contactName"));
		cdsDemandVersionImpl.setDomainId(
			this.<Long>getColumnOriginalValue("domainId"));
		cdsDemandVersionImpl.setDomainName(
			this.<String>getColumnOriginalValue("domainName"));
		cdsDemandVersionImpl.setBanId(
			this.<Long>getColumnOriginalValue("banId"));
		cdsDemandVersionImpl.setBanName(
			this.<String>getColumnOriginalValue("banName"));
		cdsDemandVersionImpl.setSpocId(
			this.<Long>getColumnOriginalValue("spocId"));
		cdsDemandVersionImpl.setSpocName(
			this.<String>getColumnOriginalValue("spocName"));
		cdsDemandVersionImpl.setUsReasoning(
			this.<String>getColumnOriginalValue("usReasoning"));
		cdsDemandVersionImpl.setUsFrequencyOut(
			this.<Integer>getColumnOriginalValue("usFrequencyOut"));
		cdsDemandVersionImpl.setUsAccessDPM(
			this.<Boolean>getColumnOriginalValue("usAccessDPM"));
		cdsDemandVersionImpl.setUsFolderDPM(
			this.<String>getColumnOriginalValue("usFolderDPM"));
		cdsDemandVersionImpl.setUsCreateFolderDPM(
			this.<Boolean>getColumnOriginalValue("usCreateFolderDPM"));
		cdsDemandVersionImpl.setUsGestorFolderDPMId(
			this.<Long>getColumnOriginalValue("usGestorFolderDPMId"));
		cdsDemandVersionImpl.setUsGestorFolderDPMName(
			this.<String>getColumnOriginalValue("usGestorFolderDPMName"));
		cdsDemandVersionImpl.setUsDPMNotificationMail(
			this.<String>getColumnOriginalValue("usDPMNotificationMail"));
		cdsDemandVersionImpl.setBioeId(
			this.<String>getColumnOriginalValue("bioeId"));
		cdsDemandVersionImpl.setBioeStateId(
			this.<Short>getColumnOriginalValue("bioeStateId"));
		cdsDemandVersionImpl.setBioeStateName(
			this.<String>getColumnOriginalValue("bioeStateName"));
		cdsDemandVersionImpl.setWorkEstimate(
			this.<Double>getColumnOriginalValue("workEstimate"));
		cdsDemandVersionImpl.setAcceptedWorkEstimate(
			this.<Double>getColumnOriginalValue("acceptedWorkEstimate"));
		cdsDemandVersionImpl.setExpectedDelivery(
			this.<Date>getColumnOriginalValue("expectedDelivery"));
		cdsDemandVersionImpl.setAcceptedDelivery(
			this.<Date>getColumnOriginalValue("acceptedDelivery"));
		cdsDemandVersionImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		cdsDemandVersionImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		cdsDemandVersionImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		cdsDemandVersionImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		cdsDemandVersionImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		cdsDemandVersionImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		cdsDemandVersionImpl.setUrlTitle(
			this.<String>getColumnOriginalValue("urlTitle"));
		cdsDemandVersionImpl.setState(
			this.<String>getColumnOriginalValue("state_"));
		cdsDemandVersionImpl.setStateByUserId(
			this.<Long>getColumnOriginalValue("stateByUserId"));
		cdsDemandVersionImpl.setStateByUserName(
			this.<String>getColumnOriginalValue("stateByUserName"));
		cdsDemandVersionImpl.setStateDate(
			this.<Date>getColumnOriginalValue("stateDate"));

		return cdsDemandVersionImpl;
	}

	@Override
	public int compareTo(CdsDemandVersion cdsDemandVersion) {
		int value = 0;

		if (getVersion() < cdsDemandVersion.getVersion()) {
			value = -1;
		}
		else if (getVersion() > cdsDemandVersion.getVersion()) {
			value = 1;
		}
		else {
			value = 0;
		}

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof CdsDemandVersion)) {
			return false;
		}

		CdsDemandVersion cdsDemandVersion = (CdsDemandVersion)object;

		long primaryKey = cdsDemandVersion.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<CdsDemandVersion> toCacheModel() {
		CdsDemandVersionCacheModel cdsDemandVersionCacheModel =
			new CdsDemandVersionCacheModel();

		cdsDemandVersionCacheModel.cdsDemandVersionId = getCdsDemandVersionId();

		cdsDemandVersionCacheModel.version = getVersion();

		cdsDemandVersionCacheModel.uuid = getUuid();

		String uuid = cdsDemandVersionCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			cdsDemandVersionCacheModel.uuid = null;
		}

		cdsDemandVersionCacheModel.demandId = getDemandId();

		cdsDemandVersionCacheModel.title = getTitle();

		String title = cdsDemandVersionCacheModel.title;

		if ((title != null) && (title.length() == 0)) {
			cdsDemandVersionCacheModel.title = null;
		}

		cdsDemandVersionCacheModel.description = getDescription();

		String description = cdsDemandVersionCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			cdsDemandVersionCacheModel.description = null;
		}

		cdsDemandVersionCacheModel.type = getType();

		cdsDemandVersionCacheModel.priority = getPriority();

		Date requestedDelivery = getRequestedDelivery();

		if (requestedDelivery != null) {
			cdsDemandVersionCacheModel.requestedDelivery =
				requestedDelivery.getTime();
		}
		else {
			cdsDemandVersionCacheModel.requestedDelivery = Long.MIN_VALUE;
		}

		cdsDemandVersionCacheModel.isGDPR = isIsGDPR();

		cdsDemandVersionCacheModel.gdprInfo = getGdprInfo();

		String gdprInfo = cdsDemandVersionCacheModel.gdprInfo;

		if ((gdprInfo != null) && (gdprInfo.length() == 0)) {
			cdsDemandVersionCacheModel.gdprInfo = null;
		}

		cdsDemandVersionCacheModel.fiveTracks = getFiveTracks();

		String fiveTracks = cdsDemandVersionCacheModel.fiveTracks;

		if ((fiveTracks != null) && (fiveTracks.length() == 0)) {
			cdsDemandVersionCacheModel.fiveTracks = null;
		}

		cdsDemandVersionCacheModel.requestorId = getRequestorId();

		cdsDemandVersionCacheModel.requestorName = getRequestorName();

		String requestorName = cdsDemandVersionCacheModel.requestorName;

		if ((requestorName != null) && (requestorName.length() == 0)) {
			cdsDemandVersionCacheModel.requestorName = null;
		}

		cdsDemandVersionCacheModel.requestedForId = getRequestedForId();

		cdsDemandVersionCacheModel.requestedForName = getRequestedForName();

		String requestedForName = cdsDemandVersionCacheModel.requestedForName;

		if ((requestedForName != null) && (requestedForName.length() == 0)) {
			cdsDemandVersionCacheModel.requestedForName = null;
		}

		cdsDemandVersionCacheModel.contactId = getContactId();

		cdsDemandVersionCacheModel.contactName = getContactName();

		String contactName = cdsDemandVersionCacheModel.contactName;

		if ((contactName != null) && (contactName.length() == 0)) {
			cdsDemandVersionCacheModel.contactName = null;
		}

		cdsDemandVersionCacheModel.domainId = getDomainId();

		cdsDemandVersionCacheModel.domainName = getDomainName();

		String domainName = cdsDemandVersionCacheModel.domainName;

		if ((domainName != null) && (domainName.length() == 0)) {
			cdsDemandVersionCacheModel.domainName = null;
		}

		cdsDemandVersionCacheModel.banId = getBanId();

		cdsDemandVersionCacheModel.banName = getBanName();

		String banName = cdsDemandVersionCacheModel.banName;

		if ((banName != null) && (banName.length() == 0)) {
			cdsDemandVersionCacheModel.banName = null;
		}

		cdsDemandVersionCacheModel.spocId = getSpocId();

		cdsDemandVersionCacheModel.spocName = getSpocName();

		String spocName = cdsDemandVersionCacheModel.spocName;

		if ((spocName != null) && (spocName.length() == 0)) {
			cdsDemandVersionCacheModel.spocName = null;
		}

		cdsDemandVersionCacheModel.usReasoning = getUsReasoning();

		String usReasoning = cdsDemandVersionCacheModel.usReasoning;

		if ((usReasoning != null) && (usReasoning.length() == 0)) {
			cdsDemandVersionCacheModel.usReasoning = null;
		}

		cdsDemandVersionCacheModel.usFrequencyOut = getUsFrequencyOut();

		cdsDemandVersionCacheModel.usAccessDPM = isUsAccessDPM();

		cdsDemandVersionCacheModel.usFolderDPM = getUsFolderDPM();

		String usFolderDPM = cdsDemandVersionCacheModel.usFolderDPM;

		if ((usFolderDPM != null) && (usFolderDPM.length() == 0)) {
			cdsDemandVersionCacheModel.usFolderDPM = null;
		}

		cdsDemandVersionCacheModel.usCreateFolderDPM = isUsCreateFolderDPM();

		cdsDemandVersionCacheModel.usGestorFolderDPMId =
			getUsGestorFolderDPMId();

		cdsDemandVersionCacheModel.usGestorFolderDPMName =
			getUsGestorFolderDPMName();

		String usGestorFolderDPMName =
			cdsDemandVersionCacheModel.usGestorFolderDPMName;

		if ((usGestorFolderDPMName != null) &&
			(usGestorFolderDPMName.length() == 0)) {

			cdsDemandVersionCacheModel.usGestorFolderDPMName = null;
		}

		cdsDemandVersionCacheModel.usDPMNotificationMail =
			getUsDPMNotificationMail();

		String usDPMNotificationMail =
			cdsDemandVersionCacheModel.usDPMNotificationMail;

		if ((usDPMNotificationMail != null) &&
			(usDPMNotificationMail.length() == 0)) {

			cdsDemandVersionCacheModel.usDPMNotificationMail = null;
		}

		cdsDemandVersionCacheModel.bioeId = getBioeId();

		String bioeId = cdsDemandVersionCacheModel.bioeId;

		if ((bioeId != null) && (bioeId.length() == 0)) {
			cdsDemandVersionCacheModel.bioeId = null;
		}

		cdsDemandVersionCacheModel.bioeStateId = getBioeStateId();

		cdsDemandVersionCacheModel.bioeStateName = getBioeStateName();

		String bioeStateName = cdsDemandVersionCacheModel.bioeStateName;

		if ((bioeStateName != null) && (bioeStateName.length() == 0)) {
			cdsDemandVersionCacheModel.bioeStateName = null;
		}

		cdsDemandVersionCacheModel.workEstimate = getWorkEstimate();

		cdsDemandVersionCacheModel.acceptedWorkEstimate =
			getAcceptedWorkEstimate();

		Date expectedDelivery = getExpectedDelivery();

		if (expectedDelivery != null) {
			cdsDemandVersionCacheModel.expectedDelivery =
				expectedDelivery.getTime();
		}
		else {
			cdsDemandVersionCacheModel.expectedDelivery = Long.MIN_VALUE;
		}

		Date acceptedDelivery = getAcceptedDelivery();

		if (acceptedDelivery != null) {
			cdsDemandVersionCacheModel.acceptedDelivery =
				acceptedDelivery.getTime();
		}
		else {
			cdsDemandVersionCacheModel.acceptedDelivery = Long.MIN_VALUE;
		}

		cdsDemandVersionCacheModel.groupId = getGroupId();

		cdsDemandVersionCacheModel.companyId = getCompanyId();

		cdsDemandVersionCacheModel.userId = getUserId();

		cdsDemandVersionCacheModel.userName = getUserName();

		String userName = cdsDemandVersionCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			cdsDemandVersionCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			cdsDemandVersionCacheModel.createDate = createDate.getTime();
		}
		else {
			cdsDemandVersionCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			cdsDemandVersionCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			cdsDemandVersionCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		cdsDemandVersionCacheModel.urlTitle = getUrlTitle();

		String urlTitle = cdsDemandVersionCacheModel.urlTitle;

		if ((urlTitle != null) && (urlTitle.length() == 0)) {
			cdsDemandVersionCacheModel.urlTitle = null;
		}

		cdsDemandVersionCacheModel.state = getState();

		String state = cdsDemandVersionCacheModel.state;

		if ((state != null) && (state.length() == 0)) {
			cdsDemandVersionCacheModel.state = null;
		}

		cdsDemandVersionCacheModel.stateByUserId = getStateByUserId();

		cdsDemandVersionCacheModel.stateByUserName = getStateByUserName();

		String stateByUserName = cdsDemandVersionCacheModel.stateByUserName;

		if ((stateByUserName != null) && (stateByUserName.length() == 0)) {
			cdsDemandVersionCacheModel.stateByUserName = null;
		}

		Date stateDate = getStateDate();

		if (stateDate != null) {
			cdsDemandVersionCacheModel.stateDate = stateDate.getTime();
		}
		else {
			cdsDemandVersionCacheModel.stateDate = Long.MIN_VALUE;
		}

		return cdsDemandVersionCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<CdsDemandVersion, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<CdsDemandVersion, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CdsDemandVersion, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(CdsDemandVersion)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<CdsDemandVersion, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<CdsDemandVersion, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CdsDemandVersion, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((CdsDemandVersion)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, CdsDemandVersion>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					CdsDemandVersion.class, ModelWrapper.class);

	}

	private long _cdsDemandVersionId;
	private int _version;
	private String _uuid;
	private long _demandId;
	private String _title;
	private String _description;
	private int _type;
	private int _priority;
	private Date _requestedDelivery;
	private boolean _isGDPR;
	private String _gdprInfo;
	private String _fiveTracks;
	private long _requestorId;
	private String _requestorName;
	private long _requestedForId;
	private String _requestedForName;
	private long _contactId;
	private String _contactName;
	private long _domainId;
	private String _domainName;
	private long _banId;
	private String _banName;
	private long _spocId;
	private String _spocName;
	private String _usReasoning;
	private int _usFrequencyOut;
	private boolean _usAccessDPM;
	private String _usFolderDPM;
	private boolean _usCreateFolderDPM;
	private long _usGestorFolderDPMId;
	private String _usGestorFolderDPMName;
	private String _usDPMNotificationMail;
	private String _bioeId;
	private short _bioeStateId;
	private String _bioeStateName;
	private double _workEstimate;
	private double _acceptedWorkEstimate;
	private Date _expectedDelivery;
	private Date _acceptedDelivery;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _urlTitle;
	private String _state;
	private long _stateByUserId;
	private String _stateByUserName;
	private Date _stateDate;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<CdsDemandVersion, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((CdsDemandVersion)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("cdsDemandVersionId", _cdsDemandVersionId);
		_columnOriginalValues.put("version", _version);
		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("demandId", _demandId);
		_columnOriginalValues.put("title", _title);
		_columnOriginalValues.put("description", _description);
		_columnOriginalValues.put("type_", _type);
		_columnOriginalValues.put("priority", _priority);
		_columnOriginalValues.put("requestedDelivery", _requestedDelivery);
		_columnOriginalValues.put("isGDPR", _isGDPR);
		_columnOriginalValues.put("gdprInfo", _gdprInfo);
		_columnOriginalValues.put("fiveTracks", _fiveTracks);
		_columnOriginalValues.put("requestorId", _requestorId);
		_columnOriginalValues.put("requestorName", _requestorName);
		_columnOriginalValues.put("requestedForId", _requestedForId);
		_columnOriginalValues.put("requestedForName", _requestedForName);
		_columnOriginalValues.put("contactId", _contactId);
		_columnOriginalValues.put("contactName", _contactName);
		_columnOriginalValues.put("domainId", _domainId);
		_columnOriginalValues.put("domainName", _domainName);
		_columnOriginalValues.put("banId", _banId);
		_columnOriginalValues.put("banName", _banName);
		_columnOriginalValues.put("spocId", _spocId);
		_columnOriginalValues.put("spocName", _spocName);
		_columnOriginalValues.put("usReasoning", _usReasoning);
		_columnOriginalValues.put("usFrequencyOut", _usFrequencyOut);
		_columnOriginalValues.put("usAccessDPM", _usAccessDPM);
		_columnOriginalValues.put("usFolderDPM", _usFolderDPM);
		_columnOriginalValues.put("usCreateFolderDPM", _usCreateFolderDPM);
		_columnOriginalValues.put("usGestorFolderDPMId", _usGestorFolderDPMId);
		_columnOriginalValues.put(
			"usGestorFolderDPMName", _usGestorFolderDPMName);
		_columnOriginalValues.put(
			"usDPMNotificationMail", _usDPMNotificationMail);
		_columnOriginalValues.put("bioeId", _bioeId);
		_columnOriginalValues.put("bioeStateId", _bioeStateId);
		_columnOriginalValues.put("bioeStateName", _bioeStateName);
		_columnOriginalValues.put("workEstimate", _workEstimate);
		_columnOriginalValues.put(
			"acceptedWorkEstimate", _acceptedWorkEstimate);
		_columnOriginalValues.put("expectedDelivery", _expectedDelivery);
		_columnOriginalValues.put("acceptedDelivery", _acceptedDelivery);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("urlTitle", _urlTitle);
		_columnOriginalValues.put("state_", _state);
		_columnOriginalValues.put("stateByUserId", _stateByUserId);
		_columnOriginalValues.put("stateByUserName", _stateByUserName);
		_columnOriginalValues.put("stateDate", _stateDate);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");
		attributeNames.put("type_", "type");
		attributeNames.put("state_", "state");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("cdsDemandVersionId", 1L);

		columnBitmasks.put("version", 2L);

		columnBitmasks.put("uuid_", 4L);

		columnBitmasks.put("demandId", 8L);

		columnBitmasks.put("title", 16L);

		columnBitmasks.put("description", 32L);

		columnBitmasks.put("type_", 64L);

		columnBitmasks.put("priority", 128L);

		columnBitmasks.put("requestedDelivery", 256L);

		columnBitmasks.put("isGDPR", 512L);

		columnBitmasks.put("gdprInfo", 1024L);

		columnBitmasks.put("fiveTracks", 2048L);

		columnBitmasks.put("requestorId", 4096L);

		columnBitmasks.put("requestorName", 8192L);

		columnBitmasks.put("requestedForId", 16384L);

		columnBitmasks.put("requestedForName", 32768L);

		columnBitmasks.put("contactId", 65536L);

		columnBitmasks.put("contactName", 131072L);

		columnBitmasks.put("domainId", 262144L);

		columnBitmasks.put("domainName", 524288L);

		columnBitmasks.put("banId", 1048576L);

		columnBitmasks.put("banName", 2097152L);

		columnBitmasks.put("spocId", 4194304L);

		columnBitmasks.put("spocName", 8388608L);

		columnBitmasks.put("usReasoning", 16777216L);

		columnBitmasks.put("usFrequencyOut", 33554432L);

		columnBitmasks.put("usAccessDPM", 67108864L);

		columnBitmasks.put("usFolderDPM", 134217728L);

		columnBitmasks.put("usCreateFolderDPM", 268435456L);

		columnBitmasks.put("usGestorFolderDPMId", 536870912L);

		columnBitmasks.put("usGestorFolderDPMName", 1073741824L);

		columnBitmasks.put("usDPMNotificationMail", 2147483648L);

		columnBitmasks.put("bioeId", 4294967296L);

		columnBitmasks.put("bioeStateId", 8589934592L);

		columnBitmasks.put("bioeStateName", 17179869184L);

		columnBitmasks.put("workEstimate", 34359738368L);

		columnBitmasks.put("acceptedWorkEstimate", 68719476736L);

		columnBitmasks.put("expectedDelivery", 137438953472L);

		columnBitmasks.put("acceptedDelivery", 274877906944L);

		columnBitmasks.put("groupId", 549755813888L);

		columnBitmasks.put("companyId", 1099511627776L);

		columnBitmasks.put("userId", 2199023255552L);

		columnBitmasks.put("userName", 4398046511104L);

		columnBitmasks.put("createDate", 8796093022208L);

		columnBitmasks.put("modifiedDate", 17592186044416L);

		columnBitmasks.put("urlTitle", 35184372088832L);

		columnBitmasks.put("state_", 70368744177664L);

		columnBitmasks.put("stateByUserId", 140737488355328L);

		columnBitmasks.put("stateByUserName", 281474976710656L);

		columnBitmasks.put("stateDate", 562949953421312L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private CdsDemandVersion _escapedModel;

}