/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package cz.csob.ency.workflow.service.base;

import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import cz.csob.ency.workflow.model.EncyWorkflowTransitionInstance;
import cz.csob.ency.workflow.service.EncyWorkflowTransitionInstanceLocalService;
import cz.csob.ency.workflow.service.EncyWorkflowTransitionInstanceLocalServiceUtil;
import cz.csob.ency.workflow.service.persistence.EncyWorkflowInstancePersistence;
import cz.csob.ency.workflow.service.persistence.EncyWorkflowLinkPersistence;
import cz.csob.ency.workflow.service.persistence.EncyWorkflowPersistence;
import cz.csob.ency.workflow.service.persistence.EncyWorkflowStateInstancePersistence;
import cz.csob.ency.workflow.service.persistence.EncyWorkflowStatePersistence;
import cz.csob.ency.workflow.service.persistence.EncyWorkflowTransitionInstancePersistence;
import cz.csob.ency.workflow.service.persistence.EncyWorkflowTransitionPersistence;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the ency workflow transition instance local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link cz.csob.ency.workflow.service.impl.EncyWorkflowTransitionInstanceLocalServiceImpl}.
 * </p>
 *
 * @author Miroslav Čermák
 * @see cz.csob.ency.workflow.service.impl.EncyWorkflowTransitionInstanceLocalServiceImpl
 * @generated
 */
public abstract class EncyWorkflowTransitionInstanceLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, EncyWorkflowTransitionInstanceLocalService,
			   IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>EncyWorkflowTransitionInstanceLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>EncyWorkflowTransitionInstanceLocalServiceUtil</code>.
	 */

	/**
	 * Adds the ency workflow transition instance to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect EncyWorkflowTransitionInstanceLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param encyWorkflowTransitionInstance the ency workflow transition instance
	 * @return the ency workflow transition instance that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public EncyWorkflowTransitionInstance addEncyWorkflowTransitionInstance(
		EncyWorkflowTransitionInstance encyWorkflowTransitionInstance) {

		encyWorkflowTransitionInstance.setNew(true);

		return encyWorkflowTransitionInstancePersistence.update(
			encyWorkflowTransitionInstance);
	}

	/**
	 * Creates a new ency workflow transition instance with the primary key. Does not add the ency workflow transition instance to the database.
	 *
	 * @param transitionInstanceId the primary key for the new ency workflow transition instance
	 * @return the new ency workflow transition instance
	 */
	@Override
	@Transactional(enabled = false)
	public EncyWorkflowTransitionInstance createEncyWorkflowTransitionInstance(
		long transitionInstanceId) {

		return encyWorkflowTransitionInstancePersistence.create(
			transitionInstanceId);
	}

	/**
	 * Deletes the ency workflow transition instance with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect EncyWorkflowTransitionInstanceLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param transitionInstanceId the primary key of the ency workflow transition instance
	 * @return the ency workflow transition instance that was removed
	 * @throws PortalException if a ency workflow transition instance with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public EncyWorkflowTransitionInstance deleteEncyWorkflowTransitionInstance(
			long transitionInstanceId)
		throws PortalException {

		return encyWorkflowTransitionInstancePersistence.remove(
			transitionInstanceId);
	}

	/**
	 * Deletes the ency workflow transition instance from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect EncyWorkflowTransitionInstanceLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param encyWorkflowTransitionInstance the ency workflow transition instance
	 * @return the ency workflow transition instance that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public EncyWorkflowTransitionInstance deleteEncyWorkflowTransitionInstance(
		EncyWorkflowTransitionInstance encyWorkflowTransitionInstance) {

		return encyWorkflowTransitionInstancePersistence.remove(
			encyWorkflowTransitionInstance);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return encyWorkflowTransitionInstancePersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			EncyWorkflowTransitionInstance.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return encyWorkflowTransitionInstancePersistence.findWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>cz.csob.ency.workflow.model.impl.EncyWorkflowTransitionInstanceModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return encyWorkflowTransitionInstancePersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>cz.csob.ency.workflow.model.impl.EncyWorkflowTransitionInstanceModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return encyWorkflowTransitionInstancePersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return encyWorkflowTransitionInstancePersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return encyWorkflowTransitionInstancePersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public EncyWorkflowTransitionInstance fetchEncyWorkflowTransitionInstance(
		long transitionInstanceId) {

		return encyWorkflowTransitionInstancePersistence.fetchByPrimaryKey(
			transitionInstanceId);
	}

	/**
	 * Returns the ency workflow transition instance matching the UUID and group.
	 *
	 * @param uuid the ency workflow transition instance's UUID
	 * @param groupId the primary key of the group
	 * @return the matching ency workflow transition instance, or <code>null</code> if a matching ency workflow transition instance could not be found
	 */
	@Override
	public EncyWorkflowTransitionInstance
		fetchEncyWorkflowTransitionInstanceByUuidAndGroupId(
			String uuid, long groupId) {

		return encyWorkflowTransitionInstancePersistence.fetchByUUID_G(
			uuid, groupId);
	}

	/**
	 * Returns the ency workflow transition instance with the primary key.
	 *
	 * @param transitionInstanceId the primary key of the ency workflow transition instance
	 * @return the ency workflow transition instance
	 * @throws PortalException if a ency workflow transition instance with the primary key could not be found
	 */
	@Override
	public EncyWorkflowTransitionInstance getEncyWorkflowTransitionInstance(
			long transitionInstanceId)
		throws PortalException {

		return encyWorkflowTransitionInstancePersistence.findByPrimaryKey(
			transitionInstanceId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			encyWorkflowTransitionInstanceLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(
			EncyWorkflowTransitionInstance.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"transitionInstanceId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			encyWorkflowTransitionInstanceLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(
			EncyWorkflowTransitionInstance.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"transitionInstanceId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			encyWorkflowTransitionInstanceLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(
			EncyWorkflowTransitionInstance.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"transitionInstanceId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return encyWorkflowTransitionInstancePersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return encyWorkflowTransitionInstanceLocalService.
			deleteEncyWorkflowTransitionInstance(
				(EncyWorkflowTransitionInstance)persistedModel);
	}

	@Override
	public BasePersistence<EncyWorkflowTransitionInstance>
		getBasePersistence() {

		return encyWorkflowTransitionInstancePersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return encyWorkflowTransitionInstancePersistence.findByPrimaryKey(
			primaryKeyObj);
	}

	/**
	 * Returns all the ency workflow transition instances matching the UUID and company.
	 *
	 * @param uuid the UUID of the ency workflow transition instances
	 * @param companyId the primary key of the company
	 * @return the matching ency workflow transition instances, or an empty list if no matches were found
	 */
	@Override
	public List<EncyWorkflowTransitionInstance>
		getEncyWorkflowTransitionInstancesByUuidAndCompanyId(
			String uuid, long companyId) {

		return encyWorkflowTransitionInstancePersistence.findByUuid_C(
			uuid, companyId);
	}

	/**
	 * Returns a range of ency workflow transition instances matching the UUID and company.
	 *
	 * @param uuid the UUID of the ency workflow transition instances
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of ency workflow transition instances
	 * @param end the upper bound of the range of ency workflow transition instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching ency workflow transition instances, or an empty list if no matches were found
	 */
	@Override
	public List<EncyWorkflowTransitionInstance>
		getEncyWorkflowTransitionInstancesByUuidAndCompanyId(
			String uuid, long companyId, int start, int end,
			OrderByComparator<EncyWorkflowTransitionInstance>
				orderByComparator) {

		return encyWorkflowTransitionInstancePersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the ency workflow transition instance matching the UUID and group.
	 *
	 * @param uuid the ency workflow transition instance's UUID
	 * @param groupId the primary key of the group
	 * @return the matching ency workflow transition instance
	 * @throws PortalException if a matching ency workflow transition instance could not be found
	 */
	@Override
	public EncyWorkflowTransitionInstance
			getEncyWorkflowTransitionInstanceByUuidAndGroupId(
				String uuid, long groupId)
		throws PortalException {

		return encyWorkflowTransitionInstancePersistence.findByUUID_G(
			uuid, groupId);
	}

	/**
	 * Returns a range of all the ency workflow transition instances.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>cz.csob.ency.workflow.model.impl.EncyWorkflowTransitionInstanceModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of ency workflow transition instances
	 * @param end the upper bound of the range of ency workflow transition instances (not inclusive)
	 * @return the range of ency workflow transition instances
	 */
	@Override
	public List<EncyWorkflowTransitionInstance>
		getEncyWorkflowTransitionInstances(int start, int end) {

		return encyWorkflowTransitionInstancePersistence.findAll(start, end);
	}

	/**
	 * Returns the number of ency workflow transition instances.
	 *
	 * @return the number of ency workflow transition instances
	 */
	@Override
	public int getEncyWorkflowTransitionInstancesCount() {
		return encyWorkflowTransitionInstancePersistence.countAll();
	}

	/**
	 * Updates the ency workflow transition instance in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect EncyWorkflowTransitionInstanceLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param encyWorkflowTransitionInstance the ency workflow transition instance
	 * @return the ency workflow transition instance that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public EncyWorkflowTransitionInstance updateEncyWorkflowTransitionInstance(
		EncyWorkflowTransitionInstance encyWorkflowTransitionInstance) {

		return encyWorkflowTransitionInstancePersistence.update(
			encyWorkflowTransitionInstance);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			EncyWorkflowTransitionInstanceLocalService.class,
			IdentifiableOSGiService.class, PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		encyWorkflowTransitionInstanceLocalService =
			(EncyWorkflowTransitionInstanceLocalService)aopProxy;

		_setLocalServiceUtilService(encyWorkflowTransitionInstanceLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return EncyWorkflowTransitionInstanceLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return EncyWorkflowTransitionInstance.class;
	}

	protected String getModelClassName() {
		return EncyWorkflowTransitionInstance.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				encyWorkflowTransitionInstancePersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		EncyWorkflowTransitionInstanceLocalService
			encyWorkflowTransitionInstanceLocalService) {

		try {
			Field field =
				EncyWorkflowTransitionInstanceLocalServiceUtil.class.
					getDeclaredField("_service");

			field.setAccessible(true);

			field.set(null, encyWorkflowTransitionInstanceLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@Reference
	protected EncyWorkflowPersistence encyWorkflowPersistence;

	@Reference
	protected EncyWorkflowInstancePersistence encyWorkflowInstancePersistence;

	@Reference
	protected EncyWorkflowLinkPersistence encyWorkflowLinkPersistence;

	@Reference
	protected EncyWorkflowStatePersistence encyWorkflowStatePersistence;

	@Reference
	protected EncyWorkflowStateInstancePersistence
		encyWorkflowStateInstancePersistence;

	@Reference
	protected EncyWorkflowTransitionPersistence
		encyWorkflowTransitionPersistence;

	protected EncyWorkflowTransitionInstanceLocalService
		encyWorkflowTransitionInstanceLocalService;

	@Reference
	protected EncyWorkflowTransitionInstancePersistence
		encyWorkflowTransitionInstancePersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}