/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package cz.csob.ency.workflow.service.base;

import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import cz.csob.ency.workflow.model.EncyWorkflowLink;
import cz.csob.ency.workflow.service.EncyWorkflowLinkLocalService;
import cz.csob.ency.workflow.service.EncyWorkflowLinkLocalServiceUtil;
import cz.csob.ency.workflow.service.persistence.EncyWorkflowInstancePersistence;
import cz.csob.ency.workflow.service.persistence.EncyWorkflowLinkPersistence;
import cz.csob.ency.workflow.service.persistence.EncyWorkflowPersistence;
import cz.csob.ency.workflow.service.persistence.EncyWorkflowStateInstancePersistence;
import cz.csob.ency.workflow.service.persistence.EncyWorkflowStatePersistence;
import cz.csob.ency.workflow.service.persistence.EncyWorkflowTransitionInstancePersistence;
import cz.csob.ency.workflow.service.persistence.EncyWorkflowTransitionPersistence;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the ency workflow link local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link cz.csob.ency.workflow.service.impl.EncyWorkflowLinkLocalServiceImpl}.
 * </p>
 *
 * @author Miroslav Čermák
 * @see cz.csob.ency.workflow.service.impl.EncyWorkflowLinkLocalServiceImpl
 * @generated
 */
public abstract class EncyWorkflowLinkLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, EncyWorkflowLinkLocalService,
			   IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>EncyWorkflowLinkLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>EncyWorkflowLinkLocalServiceUtil</code>.
	 */

	/**
	 * Adds the ency workflow link to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect EncyWorkflowLinkLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param encyWorkflowLink the ency workflow link
	 * @return the ency workflow link that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public EncyWorkflowLink addEncyWorkflowLink(
		EncyWorkflowLink encyWorkflowLink) {

		encyWorkflowLink.setNew(true);

		return encyWorkflowLinkPersistence.update(encyWorkflowLink);
	}

	/**
	 * Creates a new ency workflow link with the primary key. Does not add the ency workflow link to the database.
	 *
	 * @param workflowLinkId the primary key for the new ency workflow link
	 * @return the new ency workflow link
	 */
	@Override
	@Transactional(enabled = false)
	public EncyWorkflowLink createEncyWorkflowLink(long workflowLinkId) {
		return encyWorkflowLinkPersistence.create(workflowLinkId);
	}

	/**
	 * Deletes the ency workflow link with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect EncyWorkflowLinkLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param workflowLinkId the primary key of the ency workflow link
	 * @return the ency workflow link that was removed
	 * @throws PortalException if a ency workflow link with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public EncyWorkflowLink deleteEncyWorkflowLink(long workflowLinkId)
		throws PortalException {

		return encyWorkflowLinkPersistence.remove(workflowLinkId);
	}

	/**
	 * Deletes the ency workflow link from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect EncyWorkflowLinkLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param encyWorkflowLink the ency workflow link
	 * @return the ency workflow link that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public EncyWorkflowLink deleteEncyWorkflowLink(
		EncyWorkflowLink encyWorkflowLink) {

		return encyWorkflowLinkPersistence.remove(encyWorkflowLink);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return encyWorkflowLinkPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			EncyWorkflowLink.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return encyWorkflowLinkPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>cz.csob.ency.workflow.model.impl.EncyWorkflowLinkModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return encyWorkflowLinkPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>cz.csob.ency.workflow.model.impl.EncyWorkflowLinkModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return encyWorkflowLinkPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return encyWorkflowLinkPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return encyWorkflowLinkPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public EncyWorkflowLink fetchEncyWorkflowLink(long workflowLinkId) {
		return encyWorkflowLinkPersistence.fetchByPrimaryKey(workflowLinkId);
	}

	/**
	 * Returns the ency workflow link matching the UUID and group.
	 *
	 * @param uuid the ency workflow link's UUID
	 * @param groupId the primary key of the group
	 * @return the matching ency workflow link, or <code>null</code> if a matching ency workflow link could not be found
	 */
	@Override
	public EncyWorkflowLink fetchEncyWorkflowLinkByUuidAndGroupId(
		String uuid, long groupId) {

		return encyWorkflowLinkPersistence.fetchByUUID_G(uuid, groupId);
	}

	/**
	 * Returns the ency workflow link with the primary key.
	 *
	 * @param workflowLinkId the primary key of the ency workflow link
	 * @return the ency workflow link
	 * @throws PortalException if a ency workflow link with the primary key could not be found
	 */
	@Override
	public EncyWorkflowLink getEncyWorkflowLink(long workflowLinkId)
		throws PortalException {

		return encyWorkflowLinkPersistence.findByPrimaryKey(workflowLinkId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			encyWorkflowLinkLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(EncyWorkflowLink.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("workflowLinkId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			encyWorkflowLinkLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(EncyWorkflowLink.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"workflowLinkId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			encyWorkflowLinkLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(EncyWorkflowLink.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("workflowLinkId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(
						dynamicQuery, "modifiedDate");
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod<EncyWorkflowLink>() {

				@Override
				public void performAction(EncyWorkflowLink encyWorkflowLink)
					throws PortalException {

					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext, encyWorkflowLink);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(EncyWorkflowLink.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return encyWorkflowLinkPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return encyWorkflowLinkLocalService.deleteEncyWorkflowLink(
			(EncyWorkflowLink)persistedModel);
	}

	@Override
	public BasePersistence<EncyWorkflowLink> getBasePersistence() {
		return encyWorkflowLinkPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return encyWorkflowLinkPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns all the ency workflow links matching the UUID and company.
	 *
	 * @param uuid the UUID of the ency workflow links
	 * @param companyId the primary key of the company
	 * @return the matching ency workflow links, or an empty list if no matches were found
	 */
	@Override
	public List<EncyWorkflowLink> getEncyWorkflowLinksByUuidAndCompanyId(
		String uuid, long companyId) {

		return encyWorkflowLinkPersistence.findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of ency workflow links matching the UUID and company.
	 *
	 * @param uuid the UUID of the ency workflow links
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of ency workflow links
	 * @param end the upper bound of the range of ency workflow links (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching ency workflow links, or an empty list if no matches were found
	 */
	@Override
	public List<EncyWorkflowLink> getEncyWorkflowLinksByUuidAndCompanyId(
		String uuid, long companyId, int start, int end,
		OrderByComparator<EncyWorkflowLink> orderByComparator) {

		return encyWorkflowLinkPersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the ency workflow link matching the UUID and group.
	 *
	 * @param uuid the ency workflow link's UUID
	 * @param groupId the primary key of the group
	 * @return the matching ency workflow link
	 * @throws PortalException if a matching ency workflow link could not be found
	 */
	@Override
	public EncyWorkflowLink getEncyWorkflowLinkByUuidAndGroupId(
			String uuid, long groupId)
		throws PortalException {

		return encyWorkflowLinkPersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the ency workflow links.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>cz.csob.ency.workflow.model.impl.EncyWorkflowLinkModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of ency workflow links
	 * @param end the upper bound of the range of ency workflow links (not inclusive)
	 * @return the range of ency workflow links
	 */
	@Override
	public List<EncyWorkflowLink> getEncyWorkflowLinks(int start, int end) {
		return encyWorkflowLinkPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of ency workflow links.
	 *
	 * @return the number of ency workflow links
	 */
	@Override
	public int getEncyWorkflowLinksCount() {
		return encyWorkflowLinkPersistence.countAll();
	}

	/**
	 * Updates the ency workflow link in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect EncyWorkflowLinkLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param encyWorkflowLink the ency workflow link
	 * @return the ency workflow link that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public EncyWorkflowLink updateEncyWorkflowLink(
		EncyWorkflowLink encyWorkflowLink) {

		return encyWorkflowLinkPersistence.update(encyWorkflowLink);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			EncyWorkflowLinkLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		encyWorkflowLinkLocalService = (EncyWorkflowLinkLocalService)aopProxy;

		_setLocalServiceUtilService(encyWorkflowLinkLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return EncyWorkflowLinkLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return EncyWorkflowLink.class;
	}

	protected String getModelClassName() {
		return EncyWorkflowLink.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = encyWorkflowLinkPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		EncyWorkflowLinkLocalService encyWorkflowLinkLocalService) {

		try {
			Field field =
				EncyWorkflowLinkLocalServiceUtil.class.getDeclaredField(
					"_service");

			field.setAccessible(true);

			field.set(null, encyWorkflowLinkLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@Reference
	protected EncyWorkflowPersistence encyWorkflowPersistence;

	@Reference
	protected EncyWorkflowInstancePersistence encyWorkflowInstancePersistence;

	protected EncyWorkflowLinkLocalService encyWorkflowLinkLocalService;

	@Reference
	protected EncyWorkflowLinkPersistence encyWorkflowLinkPersistence;

	@Reference
	protected EncyWorkflowStatePersistence encyWorkflowStatePersistence;

	@Reference
	protected EncyWorkflowStateInstancePersistence
		encyWorkflowStateInstancePersistence;

	@Reference
	protected EncyWorkflowTransitionPersistence
		encyWorkflowTransitionPersistence;

	@Reference
	protected EncyWorkflowTransitionInstancePersistence
		encyWorkflowTransitionInstancePersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}