/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package cz.csob.ency.workflow.service.base;

import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import cz.csob.ency.workflow.model.EncyWorkflowInstance;
import cz.csob.ency.workflow.service.EncyWorkflowInstanceLocalService;
import cz.csob.ency.workflow.service.EncyWorkflowInstanceLocalServiceUtil;
import cz.csob.ency.workflow.service.persistence.EncyWorkflowInstancePersistence;
import cz.csob.ency.workflow.service.persistence.EncyWorkflowLinkPersistence;
import cz.csob.ency.workflow.service.persistence.EncyWorkflowPersistence;
import cz.csob.ency.workflow.service.persistence.EncyWorkflowStateInstancePersistence;
import cz.csob.ency.workflow.service.persistence.EncyWorkflowStatePersistence;
import cz.csob.ency.workflow.service.persistence.EncyWorkflowTransitionInstancePersistence;
import cz.csob.ency.workflow.service.persistence.EncyWorkflowTransitionPersistence;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the ency workflow instance local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link cz.csob.ency.workflow.service.impl.EncyWorkflowInstanceLocalServiceImpl}.
 * </p>
 *
 * @author Miroslav Čermák
 * @see cz.csob.ency.workflow.service.impl.EncyWorkflowInstanceLocalServiceImpl
 * @generated
 */
public abstract class EncyWorkflowInstanceLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, EncyWorkflowInstanceLocalService,
			   IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>EncyWorkflowInstanceLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>EncyWorkflowInstanceLocalServiceUtil</code>.
	 */

	/**
	 * Adds the ency workflow instance to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect EncyWorkflowInstanceLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param encyWorkflowInstance the ency workflow instance
	 * @return the ency workflow instance that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public EncyWorkflowInstance addEncyWorkflowInstance(
		EncyWorkflowInstance encyWorkflowInstance) {

		encyWorkflowInstance.setNew(true);

		return encyWorkflowInstancePersistence.update(encyWorkflowInstance);
	}

	/**
	 * Creates a new ency workflow instance with the primary key. Does not add the ency workflow instance to the database.
	 *
	 * @param workflowInstanceId the primary key for the new ency workflow instance
	 * @return the new ency workflow instance
	 */
	@Override
	@Transactional(enabled = false)
	public EncyWorkflowInstance createEncyWorkflowInstance(
		long workflowInstanceId) {

		return encyWorkflowInstancePersistence.create(workflowInstanceId);
	}

	/**
	 * Deletes the ency workflow instance with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect EncyWorkflowInstanceLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param workflowInstanceId the primary key of the ency workflow instance
	 * @return the ency workflow instance that was removed
	 * @throws PortalException if a ency workflow instance with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public EncyWorkflowInstance deleteEncyWorkflowInstance(
			long workflowInstanceId)
		throws PortalException {

		return encyWorkflowInstancePersistence.remove(workflowInstanceId);
	}

	/**
	 * Deletes the ency workflow instance from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect EncyWorkflowInstanceLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param encyWorkflowInstance the ency workflow instance
	 * @return the ency workflow instance that was removed
	 * @throws PortalException
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public EncyWorkflowInstance deleteEncyWorkflowInstance(
			EncyWorkflowInstance encyWorkflowInstance)
		throws PortalException {

		return encyWorkflowInstancePersistence.remove(encyWorkflowInstance);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return encyWorkflowInstancePersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			EncyWorkflowInstance.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return encyWorkflowInstancePersistence.findWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>cz.csob.ency.workflow.model.impl.EncyWorkflowInstanceModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return encyWorkflowInstancePersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>cz.csob.ency.workflow.model.impl.EncyWorkflowInstanceModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return encyWorkflowInstancePersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return encyWorkflowInstancePersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return encyWorkflowInstancePersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public EncyWorkflowInstance fetchEncyWorkflowInstance(
		long workflowInstanceId) {

		return encyWorkflowInstancePersistence.fetchByPrimaryKey(
			workflowInstanceId);
	}

	/**
	 * Returns the ency workflow instance matching the UUID and group.
	 *
	 * @param uuid the ency workflow instance's UUID
	 * @param groupId the primary key of the group
	 * @return the matching ency workflow instance, or <code>null</code> if a matching ency workflow instance could not be found
	 */
	@Override
	public EncyWorkflowInstance fetchEncyWorkflowInstanceByUuidAndGroupId(
		String uuid, long groupId) {

		return encyWorkflowInstancePersistence.fetchByUUID_G(uuid, groupId);
	}

	/**
	 * Returns the ency workflow instance with the primary key.
	 *
	 * @param workflowInstanceId the primary key of the ency workflow instance
	 * @return the ency workflow instance
	 * @throws PortalException if a ency workflow instance with the primary key could not be found
	 */
	@Override
	public EncyWorkflowInstance getEncyWorkflowInstance(long workflowInstanceId)
		throws PortalException {

		return encyWorkflowInstancePersistence.findByPrimaryKey(
			workflowInstanceId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			encyWorkflowInstanceLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(EncyWorkflowInstance.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("workflowInstanceId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			encyWorkflowInstanceLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(
			EncyWorkflowInstance.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"workflowInstanceId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			encyWorkflowInstanceLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(EncyWorkflowInstance.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("workflowInstanceId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(
						dynamicQuery, "modifiedDate");
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod
				<EncyWorkflowInstance>() {

				@Override
				public void performAction(
						EncyWorkflowInstance encyWorkflowInstance)
					throws PortalException {

					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext, encyWorkflowInstance);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(
					EncyWorkflowInstance.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return encyWorkflowInstancePersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return encyWorkflowInstanceLocalService.deleteEncyWorkflowInstance(
			(EncyWorkflowInstance)persistedModel);
	}

	@Override
	public BasePersistence<EncyWorkflowInstance> getBasePersistence() {
		return encyWorkflowInstancePersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return encyWorkflowInstancePersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns all the ency workflow instances matching the UUID and company.
	 *
	 * @param uuid the UUID of the ency workflow instances
	 * @param companyId the primary key of the company
	 * @return the matching ency workflow instances, or an empty list if no matches were found
	 */
	@Override
	public List<EncyWorkflowInstance>
		getEncyWorkflowInstancesByUuidAndCompanyId(
			String uuid, long companyId) {

		return encyWorkflowInstancePersistence.findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of ency workflow instances matching the UUID and company.
	 *
	 * @param uuid the UUID of the ency workflow instances
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of ency workflow instances
	 * @param end the upper bound of the range of ency workflow instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching ency workflow instances, or an empty list if no matches were found
	 */
	@Override
	public List<EncyWorkflowInstance>
		getEncyWorkflowInstancesByUuidAndCompanyId(
			String uuid, long companyId, int start, int end,
			OrderByComparator<EncyWorkflowInstance> orderByComparator) {

		return encyWorkflowInstancePersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the ency workflow instance matching the UUID and group.
	 *
	 * @param uuid the ency workflow instance's UUID
	 * @param groupId the primary key of the group
	 * @return the matching ency workflow instance
	 * @throws PortalException if a matching ency workflow instance could not be found
	 */
	@Override
	public EncyWorkflowInstance getEncyWorkflowInstanceByUuidAndGroupId(
			String uuid, long groupId)
		throws PortalException {

		return encyWorkflowInstancePersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the ency workflow instances.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>cz.csob.ency.workflow.model.impl.EncyWorkflowInstanceModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of ency workflow instances
	 * @param end the upper bound of the range of ency workflow instances (not inclusive)
	 * @return the range of ency workflow instances
	 */
	@Override
	public List<EncyWorkflowInstance> getEncyWorkflowInstances(
		int start, int end) {

		return encyWorkflowInstancePersistence.findAll(start, end);
	}

	/**
	 * Returns the number of ency workflow instances.
	 *
	 * @return the number of ency workflow instances
	 */
	@Override
	public int getEncyWorkflowInstancesCount() {
		return encyWorkflowInstancePersistence.countAll();
	}

	/**
	 * Updates the ency workflow instance in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect EncyWorkflowInstanceLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param encyWorkflowInstance the ency workflow instance
	 * @return the ency workflow instance that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public EncyWorkflowInstance updateEncyWorkflowInstance(
		EncyWorkflowInstance encyWorkflowInstance) {

		return encyWorkflowInstancePersistence.update(encyWorkflowInstance);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			EncyWorkflowInstanceLocalService.class,
			IdentifiableOSGiService.class, PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		encyWorkflowInstanceLocalService =
			(EncyWorkflowInstanceLocalService)aopProxy;

		_setLocalServiceUtilService(encyWorkflowInstanceLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return EncyWorkflowInstanceLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return EncyWorkflowInstance.class;
	}

	protected String getModelClassName() {
		return EncyWorkflowInstance.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				encyWorkflowInstancePersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		EncyWorkflowInstanceLocalService encyWorkflowInstanceLocalService) {

		try {
			Field field =
				EncyWorkflowInstanceLocalServiceUtil.class.getDeclaredField(
					"_service");

			field.setAccessible(true);

			field.set(null, encyWorkflowInstanceLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@Reference
	protected EncyWorkflowPersistence encyWorkflowPersistence;

	protected EncyWorkflowInstanceLocalService encyWorkflowInstanceLocalService;

	@Reference
	protected EncyWorkflowInstancePersistence encyWorkflowInstancePersistence;

	@Reference
	protected EncyWorkflowLinkPersistence encyWorkflowLinkPersistence;

	@Reference
	protected EncyWorkflowStatePersistence encyWorkflowStatePersistence;

	@Reference
	protected EncyWorkflowStateInstancePersistence
		encyWorkflowStateInstancePersistence;

	@Reference
	protected EncyWorkflowTransitionPersistence
		encyWorkflowTransitionPersistence;

	@Reference
	protected EncyWorkflowTransitionInstancePersistence
		encyWorkflowTransitionInstancePersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}