/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package cz.csob.ency.modules.e3.entry.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import cz.csob.ency.modules.e3.entry.model.E3Entry;
import cz.csob.ency.modules.e3.entry.model.E3EntryVersion;
import cz.csob.ency.modules.e3.entry.model.E3EntryVersionModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the E3EntryVersion service. Represents a row in the &quot;E3EntryVersion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>E3EntryVersionModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link E3EntryVersionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see E3EntryVersionImpl
 * @generated
 */
public class E3EntryVersionModelImpl
	extends BaseModelImpl<E3EntryVersion> implements E3EntryVersionModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a e3 entry version model instance should use the <code>E3EntryVersion</code> interface instead.
	 */
	public static final String TABLE_NAME = "E3EntryVersion";

	public static final Object[][] TABLE_COLUMNS = {
		{"e3EntryVersionId", Types.BIGINT}, {"version", Types.INTEGER},
		{"uuid_", Types.VARCHAR}, {"entry_id", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"entry_modifier_id", Types.BIGINT},
		{"entry_modifier_name", Types.VARCHAR},
		{"entry_created", Types.TIMESTAMP}, {"entry_modified", Types.TIMESTAMP},
		{"entry_author_id", Types.BIGINT}, {"entry_author_name", Types.VARCHAR},
		{"entry_xid", Types.VARCHAR}, {"entry_name", Types.VARCHAR},
		{"app_class", Types.VARCHAR}, {"parent_id", Types.BIGINT},
		{"parent_field", Types.VARCHAR}, {"json_values", Types.CLOB},
		{"status", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("e3EntryVersionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("version", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("entry_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("entry_modifier_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("entry_modifier_name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("entry_created", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("entry_modified", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("entry_author_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("entry_author_name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("entry_xid", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("entry_name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("app_class", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("parent_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("parent_field", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("json_values", Types.CLOB);
		TABLE_COLUMNS_MAP.put("status", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table E3EntryVersion (e3EntryVersionId LONG not null primary key,version INTEGER,uuid_ VARCHAR(75) null,entry_id LONG,groupId LONG,companyId LONG,entry_modifier_id LONG,entry_modifier_name VARCHAR(256) null,entry_created DATE null,entry_modified DATE null,entry_author_id LONG,entry_author_name VARCHAR(256) null,entry_xid VARCHAR(256) null,entry_name VARCHAR(256) null,app_class VARCHAR(512) null,parent_id LONG,parent_field VARCHAR(128) null,json_values TEXT null,status LONG)";

	public static final String TABLE_SQL_DROP = "drop table E3EntryVersion";

	public static final String ORDER_BY_JPQL =
		" ORDER BY e3EntryVersion.version DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY E3EntryVersion.version DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ENTRYID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PARENTFIELD_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PARENTID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long STATUS_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 64L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long VERSION_COLUMN_BITMASK = 128L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long XID_COLUMN_BITMASK = 256L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public E3EntryVersionModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _e3EntryVersionId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setE3EntryVersionId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _e3EntryVersionId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return E3EntryVersion.class;
	}

	@Override
	public String getModelClassName() {
		return E3EntryVersion.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<E3EntryVersion, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<E3EntryVersion, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<E3EntryVersion, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((E3EntryVersion)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<E3EntryVersion, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<E3EntryVersion, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(E3EntryVersion)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<E3EntryVersion, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<E3EntryVersion, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, E3EntryVersion>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			E3EntryVersion.class.getClassLoader(), E3EntryVersion.class,
			ModelWrapper.class);

		try {
			Constructor<E3EntryVersion> constructor =
				(Constructor<E3EntryVersion>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<E3EntryVersion, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<E3EntryVersion, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<E3EntryVersion, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<E3EntryVersion, Object>>();
		Map<String, BiConsumer<E3EntryVersion, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<E3EntryVersion, ?>>();

		attributeGetterFunctions.put(
			"e3EntryVersionId", E3EntryVersion::getE3EntryVersionId);
		attributeSetterBiConsumers.put(
			"e3EntryVersionId",
			(BiConsumer<E3EntryVersion, Long>)
				E3EntryVersion::setE3EntryVersionId);
		attributeGetterFunctions.put("version", E3EntryVersion::getVersion);
		attributeSetterBiConsumers.put(
			"version",
			(BiConsumer<E3EntryVersion, Integer>)E3EntryVersion::setVersion);
		attributeGetterFunctions.put("uuid", E3EntryVersion::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<E3EntryVersion, String>)E3EntryVersion::setUuid);
		attributeGetterFunctions.put("entryId", E3EntryVersion::getEntryId);
		attributeSetterBiConsumers.put(
			"entryId",
			(BiConsumer<E3EntryVersion, Long>)E3EntryVersion::setEntryId);
		attributeGetterFunctions.put("groupId", E3EntryVersion::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<E3EntryVersion, Long>)E3EntryVersion::setGroupId);
		attributeGetterFunctions.put("companyId", E3EntryVersion::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<E3EntryVersion, Long>)E3EntryVersion::setCompanyId);
		attributeGetterFunctions.put("userId", E3EntryVersion::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<E3EntryVersion, Long>)E3EntryVersion::setUserId);
		attributeGetterFunctions.put("userName", E3EntryVersion::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<E3EntryVersion, String>)E3EntryVersion::setUserName);
		attributeGetterFunctions.put(
			"createDate", E3EntryVersion::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<E3EntryVersion, Date>)E3EntryVersion::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", E3EntryVersion::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<E3EntryVersion, Date>)E3EntryVersion::setModifiedDate);
		attributeGetterFunctions.put("authorId", E3EntryVersion::getAuthorId);
		attributeSetterBiConsumers.put(
			"authorId",
			(BiConsumer<E3EntryVersion, Long>)E3EntryVersion::setAuthorId);
		attributeGetterFunctions.put(
			"authorName", E3EntryVersion::getAuthorName);
		attributeSetterBiConsumers.put(
			"authorName",
			(BiConsumer<E3EntryVersion, String>)E3EntryVersion::setAuthorName);
		attributeGetterFunctions.put("xid", E3EntryVersion::getXid);
		attributeSetterBiConsumers.put(
			"xid", (BiConsumer<E3EntryVersion, String>)E3EntryVersion::setXid);
		attributeGetterFunctions.put("name", E3EntryVersion::getName);
		attributeSetterBiConsumers.put(
			"name",
			(BiConsumer<E3EntryVersion, String>)E3EntryVersion::setName);
		attributeGetterFunctions.put("appClass", E3EntryVersion::getAppClass);
		attributeSetterBiConsumers.put(
			"appClass",
			(BiConsumer<E3EntryVersion, String>)E3EntryVersion::setAppClass);
		attributeGetterFunctions.put("parentId", E3EntryVersion::getParentId);
		attributeSetterBiConsumers.put(
			"parentId",
			(BiConsumer<E3EntryVersion, Long>)E3EntryVersion::setParentId);
		attributeGetterFunctions.put(
			"parentField", E3EntryVersion::getParentField);
		attributeSetterBiConsumers.put(
			"parentField",
			(BiConsumer<E3EntryVersion, String>)E3EntryVersion::setParentField);
		attributeGetterFunctions.put("values", E3EntryVersion::getValues);
		attributeSetterBiConsumers.put(
			"values",
			(BiConsumer<E3EntryVersion, Map<String, Serializable>>)
				E3EntryVersion::setValues);
		attributeGetterFunctions.put("status", E3EntryVersion::getStatus);
		attributeSetterBiConsumers.put(
			"status",
			(BiConsumer<E3EntryVersion, Long>)E3EntryVersion::setStatus);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getVersionedModelId() {
		return getEntryId();
	}

	@Override
	public void populateVersionedModel(E3Entry e3Entry) {
		e3Entry.setUuid(getUuid());
		e3Entry.setGroupId(getGroupId());
		e3Entry.setCompanyId(getCompanyId());
		e3Entry.setUserId(getUserId());
		e3Entry.setUserName(getUserName());
		e3Entry.setCreateDate(getCreateDate());
		e3Entry.setModifiedDate(getModifiedDate());
		e3Entry.setAuthorId(getAuthorId());
		e3Entry.setAuthorName(getAuthorName());
		e3Entry.setXid(getXid());
		e3Entry.setName(getName());
		e3Entry.setAppClass(getAppClass());
		e3Entry.setParentId(getParentId());
		e3Entry.setParentField(getParentField());
		e3Entry.setValues(getValues());
		e3Entry.setStatus(getStatus());
	}

	@Override
	public void setVersionedModelId(long entryId) {
		setEntryId(entryId);
	}

	@Override
	public E3Entry toVersionedModel() {
		E3Entry e3Entry = new E3EntryImpl();

		e3Entry.setPrimaryKey(getVersionedModelId());
		e3Entry.setHeadId(-getVersionedModelId());

		populateVersionedModel(e3Entry);

		return e3Entry;
	}

	@Override
	public long getE3EntryVersionId() {
		return _e3EntryVersionId;
	}

	@Override
	public void setE3EntryVersionId(long e3EntryVersionId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_e3EntryVersionId = e3EntryVersionId;
	}

	@Override
	public int getVersion() {
		return _version;
	}

	@Override
	public void setVersion(int version) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_version = version;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalVersion() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("version"));
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@Override
	public long getEntryId() {
		return _entryId;
	}

	@Override
	public void setEntryId(long entryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_entryId = entryId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalEntryId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("entry_id"));
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public long getAuthorId() {
		return _authorId;
	}

	@Override
	public void setAuthorId(long authorId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_authorId = authorId;
	}

	@Override
	public String getAuthorName() {
		if (_authorName == null) {
			return "";
		}
		else {
			return _authorName;
		}
	}

	@Override
	public void setAuthorName(String authorName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_authorName = authorName;
	}

	@Override
	public String getXid() {
		if (_xid == null) {
			return "";
		}
		else {
			return _xid;
		}
	}

	@Override
	public void setXid(String xid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_xid = xid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalXid() {
		return getColumnOriginalValue("entry_xid");
	}

	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	@Override
	public String getAppClass() {
		if (_appClass == null) {
			return "";
		}
		else {
			return _appClass;
		}
	}

	@Override
	public void setAppClass(String appClass) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_appClass = appClass;
	}

	@Override
	public long getParentId() {
		return _parentId;
	}

	@Override
	public void setParentId(long parentId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_parentId = parentId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalParentId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("parent_id"));
	}

	@Override
	public String getParentField() {
		if (_parentField == null) {
			return "";
		}
		else {
			return _parentField;
		}
	}

	@Override
	public void setParentField(String parentField) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_parentField = parentField;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalParentField() {
		return getColumnOriginalValue("parent_field");
	}

	@Override
	public Map<String, Serializable> getValues() {
		return _values;
	}

	@Override
	public void setValues(Map<String, Serializable> values) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_values = values;
	}

	@Override
	public long getStatus() {
		return _status;
	}

	@Override
	public void setStatus(long status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalStatus() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("status"));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), E3EntryVersion.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public E3EntryVersion toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, E3EntryVersion>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		E3EntryVersionImpl e3EntryVersionImpl = new E3EntryVersionImpl();

		e3EntryVersionImpl.setE3EntryVersionId(getE3EntryVersionId());
		e3EntryVersionImpl.setVersion(getVersion());
		e3EntryVersionImpl.setUuid(getUuid());
		e3EntryVersionImpl.setEntryId(getEntryId());
		e3EntryVersionImpl.setGroupId(getGroupId());
		e3EntryVersionImpl.setCompanyId(getCompanyId());
		e3EntryVersionImpl.setUserId(getUserId());
		e3EntryVersionImpl.setUserName(getUserName());
		e3EntryVersionImpl.setCreateDate(getCreateDate());
		e3EntryVersionImpl.setModifiedDate(getModifiedDate());
		e3EntryVersionImpl.setAuthorId(getAuthorId());
		e3EntryVersionImpl.setAuthorName(getAuthorName());
		e3EntryVersionImpl.setXid(getXid());
		e3EntryVersionImpl.setName(getName());
		e3EntryVersionImpl.setAppClass(getAppClass());
		e3EntryVersionImpl.setParentId(getParentId());
		e3EntryVersionImpl.setParentField(getParentField());
		e3EntryVersionImpl.setValues(getValues());
		e3EntryVersionImpl.setStatus(getStatus());

		e3EntryVersionImpl.resetOriginalValues();

		return e3EntryVersionImpl;
	}

	@Override
	public int compareTo(E3EntryVersion e3EntryVersion) {
		int value = 0;

		if (getVersion() < e3EntryVersion.getVersion()) {
			value = -1;
		}
		else if (getVersion() > e3EntryVersion.getVersion()) {
			value = 1;
		}
		else {
			value = 0;
		}

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof E3EntryVersion)) {
			return false;
		}

		E3EntryVersion e3EntryVersion = (E3EntryVersion)object;

		long primaryKey = e3EntryVersion.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<E3EntryVersion> toCacheModel() {
		E3EntryVersionCacheModel e3EntryVersionCacheModel =
			new E3EntryVersionCacheModel();

		e3EntryVersionCacheModel.e3EntryVersionId = getE3EntryVersionId();

		e3EntryVersionCacheModel.version = getVersion();

		e3EntryVersionCacheModel.uuid = getUuid();

		String uuid = e3EntryVersionCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			e3EntryVersionCacheModel.uuid = null;
		}

		e3EntryVersionCacheModel.entryId = getEntryId();

		e3EntryVersionCacheModel.groupId = getGroupId();

		e3EntryVersionCacheModel.companyId = getCompanyId();

		e3EntryVersionCacheModel.userId = getUserId();

		e3EntryVersionCacheModel.userName = getUserName();

		String userName = e3EntryVersionCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			e3EntryVersionCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			e3EntryVersionCacheModel.createDate = createDate.getTime();
		}
		else {
			e3EntryVersionCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			e3EntryVersionCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			e3EntryVersionCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		e3EntryVersionCacheModel.authorId = getAuthorId();

		e3EntryVersionCacheModel.authorName = getAuthorName();

		String authorName = e3EntryVersionCacheModel.authorName;

		if ((authorName != null) && (authorName.length() == 0)) {
			e3EntryVersionCacheModel.authorName = null;
		}

		e3EntryVersionCacheModel.xid = getXid();

		String xid = e3EntryVersionCacheModel.xid;

		if ((xid != null) && (xid.length() == 0)) {
			e3EntryVersionCacheModel.xid = null;
		}

		e3EntryVersionCacheModel.name = getName();

		String name = e3EntryVersionCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			e3EntryVersionCacheModel.name = null;
		}

		e3EntryVersionCacheModel.appClass = getAppClass();

		String appClass = e3EntryVersionCacheModel.appClass;

		if ((appClass != null) && (appClass.length() == 0)) {
			e3EntryVersionCacheModel.appClass = null;
		}

		e3EntryVersionCacheModel.parentId = getParentId();

		e3EntryVersionCacheModel.parentField = getParentField();

		String parentField = e3EntryVersionCacheModel.parentField;

		if ((parentField != null) && (parentField.length() == 0)) {
			e3EntryVersionCacheModel.parentField = null;
		}

		e3EntryVersionCacheModel.values = getValues();

		e3EntryVersionCacheModel.status = getStatus();

		return e3EntryVersionCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<E3EntryVersion, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(4 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<E3EntryVersion, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<E3EntryVersion, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((E3EntryVersion)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<E3EntryVersion, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<E3EntryVersion, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<E3EntryVersion, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((E3EntryVersion)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, E3EntryVersion>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _e3EntryVersionId;
	private int _version;
	private String _uuid;
	private long _entryId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _authorId;
	private String _authorName;
	private String _xid;
	private String _name;
	private String _appClass;
	private long _parentId;
	private String _parentField;
	private Map<String, Serializable> _values;
	private long _status;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<E3EntryVersion, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((E3EntryVersion)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("e3EntryVersionId", _e3EntryVersionId);
		_columnOriginalValues.put("version", _version);
		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("entry_id", _entryId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("entry_modifier_id", _userId);
		_columnOriginalValues.put("entry_modifier_name", _userName);
		_columnOriginalValues.put("entry_created", _createDate);
		_columnOriginalValues.put("entry_modified", _modifiedDate);
		_columnOriginalValues.put("entry_author_id", _authorId);
		_columnOriginalValues.put("entry_author_name", _authorName);
		_columnOriginalValues.put("entry_xid", _xid);
		_columnOriginalValues.put("entry_name", _name);
		_columnOriginalValues.put("app_class", _appClass);
		_columnOriginalValues.put("parent_id", _parentId);
		_columnOriginalValues.put("parent_field", _parentField);
		_columnOriginalValues.put("json_values", _values);
		_columnOriginalValues.put("status", _status);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");
		attributeNames.put("entry_id", "entryId");
		attributeNames.put("entry_modifier_id", "userId");
		attributeNames.put("entry_modifier_name", "userName");
		attributeNames.put("entry_created", "createDate");
		attributeNames.put("entry_modified", "modifiedDate");
		attributeNames.put("entry_author_id", "authorId");
		attributeNames.put("entry_author_name", "authorName");
		attributeNames.put("entry_xid", "xid");
		attributeNames.put("entry_name", "name");
		attributeNames.put("app_class", "appClass");
		attributeNames.put("parent_id", "parentId");
		attributeNames.put("parent_field", "parentField");
		attributeNames.put("json_values", "values");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("e3EntryVersionId", 1L);

		columnBitmasks.put("version", 2L);

		columnBitmasks.put("uuid_", 4L);

		columnBitmasks.put("entry_id", 8L);

		columnBitmasks.put("groupId", 16L);

		columnBitmasks.put("companyId", 32L);

		columnBitmasks.put("entry_modifier_id", 64L);

		columnBitmasks.put("entry_modifier_name", 128L);

		columnBitmasks.put("entry_created", 256L);

		columnBitmasks.put("entry_modified", 512L);

		columnBitmasks.put("entry_author_id", 1024L);

		columnBitmasks.put("entry_author_name", 2048L);

		columnBitmasks.put("entry_xid", 4096L);

		columnBitmasks.put("entry_name", 8192L);

		columnBitmasks.put("app_class", 16384L);

		columnBitmasks.put("parent_id", 32768L);

		columnBitmasks.put("parent_field", 65536L);

		columnBitmasks.put("json_values", 131072L);

		columnBitmasks.put("status", 262144L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private E3EntryVersion _escapedModel;

}