/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package cz.csob.ency.modules.e3.entry.model.impl;

import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;

import cz.csob.ency.modules.e3.entry.model.E3Entry;
import cz.csob.ency.modules.e3.entry.service.E3EntryLocalServiceUtil;

/**
 * The extended model base implementation for the E3Entry service. Represents a row in the &quot;E3Entry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link E3EntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see E3EntryImpl
 * @see E3Entry
 * @generated
 */
public abstract class E3EntryBaseImpl
	extends E3EntryModelImpl implements E3Entry {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a e3 entry model instance should use the <code>E3Entry</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			E3EntryLocalServiceUtil.addE3Entry(this);
		}
		else {
			try {
				E3EntryLocalServiceUtil.updateE3Entry(this);
			}
			catch (PortalException portalException) {
				throw new SystemException(portalException);
			}
		}
	}

}