/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package cz.csob.ency.delegations.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the DelegatedRole service. Represents a row in the &quot;delegations_delegatedrole&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>cz.csob.ency.delegations.model.impl.DelegatedRoleModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>cz.csob.ency.delegations.model.impl.DelegatedRoleImpl</code>.
 * </p>
 *
 * @author Miroslav Čermák
 * @see DelegatedRole
 * @generated
 */
@ProviderType
public interface DelegatedRoleModel
	extends BaseModel<DelegatedRole>, GroupedModel, MVCCModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a delegated role model instance should use the {@link DelegatedRole} interface instead.
	 */

	/**
	 * Returns the primary key of this delegated role.
	 *
	 * @return the primary key of this delegated role
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this delegated role.
	 *
	 * @param primaryKey the primary key of this delegated role
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this delegated role.
	 *
	 * @return the mvcc version of this delegated role
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this delegated role.
	 *
	 * @param mvccVersion the mvcc version of this delegated role
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the role ID of this delegated role.
	 *
	 * @return the role ID of this delegated role
	 */
	public long getRoleId();

	/**
	 * Sets the role ID of this delegated role.
	 *
	 * @param roleId the role ID of this delegated role
	 */
	public void setRoleId(long roleId);

	/**
	 * Returns the title of this delegated role.
	 *
	 * @return the title of this delegated role
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this delegated role.
	 *
	 * @param title the title of this delegated role
	 */
	public void setTitle(String title);

	/**
	 * Returns the code of this delegated role.
	 *
	 * @return the code of this delegated role
	 */
	@AutoEscape
	public String getCode();

	/**
	 * Sets the code of this delegated role.
	 *
	 * @param code the code of this delegated role
	 */
	public void setCode(String code);

	/**
	 * Returns the description of this delegated role.
	 *
	 * @return the description of this delegated role
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this delegated role.
	 *
	 * @param description the description of this delegated role
	 */
	public void setDescription(String description);

	/**
	 * Returns the group ID of this delegated role.
	 *
	 * @return the group ID of this delegated role
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this delegated role.
	 *
	 * @param groupId the group ID of this delegated role
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this delegated role.
	 *
	 * @return the company ID of this delegated role
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this delegated role.
	 *
	 * @param companyId the company ID of this delegated role
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this delegated role.
	 *
	 * @return the user ID of this delegated role
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this delegated role.
	 *
	 * @param userId the user ID of this delegated role
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this delegated role.
	 *
	 * @return the user uuid of this delegated role
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this delegated role.
	 *
	 * @param userUuid the user uuid of this delegated role
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this delegated role.
	 *
	 * @return the user name of this delegated role
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this delegated role.
	 *
	 * @param userName the user name of this delegated role
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this delegated role.
	 *
	 * @return the create date of this delegated role
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this delegated role.
	 *
	 * @param createDate the create date of this delegated role
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this delegated role.
	 *
	 * @return the modified date of this delegated role
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this delegated role.
	 *
	 * @param modifiedDate the modified date of this delegated role
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	@Override
	public DelegatedRole cloneWithOriginalValues();

}