create table MetaCds_ColumnEntry (
	mvccVersion LONG default 0 not null,
	uuid_ VARCHAR(75) null,
	columnEntryId LONG not null primary key,
	columnType VARCHAR(10) null,
	columnName VARCHAR(512) null,
	columnPosition LONG,
	columnFullName VARCHAR(512) null,
	tableEntryId LONG,
	tableName VARCHAR(512) null,
	systemName VARCHAR(10) null,
	databaseName VARCHAR(128) null,
	description TEXT null,
	dataType VARCHAR(32) null,
	dataSize LONG,
	isPrimaryKey BOOLEAN,
	isNotNull BOOLEAN,
	isActive BOOLEAN,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	urlTitle VARCHAR(256) null,
	status INTEGER,
	statusByUserId LONG,
	statusByUserName VARCHAR(75) null,
	statusDate DATE null
);

create table MetaCds_SystemEntry (
	mvccVersion LONG default 0 not null,
	uuid_ VARCHAR(75) null,
	systemEntryId LONG not null primary key,
	systemCode LONG,
	systemName VARCHAR(10) null,
	systemTitle VARCHAR(200) null,
	systemType VARCHAR(20) null,
	description TEXT null,
	stewardName VARCHAR(3000) null,
	stewardId VARCHAR(300) null,
	stewardDepartment VARCHAR(3000) null,
	businessOwnerName VARCHAR(3000) null,
	businessOwnerId VARCHAR(300) null,
	contactPersonName VARCHAR(3000) null,
	contactPersonId VARCHAR(300) null,
	sandboxName VARCHAR(256) null,
	gestorDepartmentId VARCHAR(300) null,
	gestorDepartmentName VARCHAR(512) null,
	role_ VARCHAR(256) null,
	snowAssetTagId VARCHAR(300) null,
	snowAssetTagName VARCHAR(3000) null,
	isSlaSigned BOOLEAN,
	isSelfBi BOOLEAN,
	isActive BOOLEAN,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	urlTitle VARCHAR(256) null,
	status INTEGER,
	statusByUserId LONG,
	statusByUserName VARCHAR(75) null,
	statusDate DATE null
);

create table MetaCds_TableEntry (
	mvccVersion LONG default 0 not null,
	uuid_ VARCHAR(75) null,
	tableEntryId LONG not null primary key,
	tableName VARCHAR(512) null,
	tableFullName VARCHAR(512) null,
	tableType VARCHAR(10) null,
	tableDatabase VARCHAR(128) null,
	systemEntryId LONG,
	systemName VARCHAR(10) null,
	description TEXT null,
	dsaUrl STRING null,
	contactPersonName VARCHAR(3000) null,
	contactPersonId VARCHAR(300) null,
	specificationOwnerName VARCHAR(3000) null,
	specificationOwnerId VARCHAR(300) null,
	unstructuredClause TEXT null,
	isActive BOOLEAN,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	urlTitle VARCHAR(256) null,
	status INTEGER,
	statusByUserId LONG,
	statusByUserName VARCHAR(75) null,
	statusDate DATE null
);