/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package cz.csob.ency.modules.apps.meta.cds.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.model.TrashedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the SystemEntry service. Represents a row in the &quot;MetaCds_SystemEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>cz.csob.ency.modules.apps.meta.cds.model.impl.SystemEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>cz.csob.ency.modules.apps.meta.cds.model.impl.SystemEntryImpl</code>.
 * </p>
 *
 * @author "Miroslav Čermák"
 * @see SystemEntry
 * @generated
 */
@ProviderType
public interface SystemEntryModel
	extends BaseModel<SystemEntry>, GroupedModel, MVCCModel, ShardedModel,
			StagedAuditedModel, TrashedModel, WorkflowedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a system entry model instance should use the {@link SystemEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this system entry.
	 *
	 * @return the primary key of this system entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this system entry.
	 *
	 * @param primaryKey the primary key of this system entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this system entry.
	 *
	 * @return the mvcc version of this system entry
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this system entry.
	 *
	 * @param mvccVersion the mvcc version of this system entry
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the uuid of this system entry.
	 *
	 * @return the uuid of this system entry
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this system entry.
	 *
	 * @param uuid the uuid of this system entry
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the system entry ID of this system entry.
	 *
	 * @return the system entry ID of this system entry
	 */
	public long getSystemEntryId();

	/**
	 * Sets the system entry ID of this system entry.
	 *
	 * @param systemEntryId the system entry ID of this system entry
	 */
	public void setSystemEntryId(long systemEntryId);

	/**
	 * Returns the system code of this system entry.
	 *
	 * @return the system code of this system entry
	 */
	public long getSystemCode();

	/**
	 * Sets the system code of this system entry.
	 *
	 * @param systemCode the system code of this system entry
	 */
	public void setSystemCode(long systemCode);

	/**
	 * Returns the system name of this system entry.
	 *
	 * @return the system name of this system entry
	 */
	@AutoEscape
	public String getSystemName();

	/**
	 * Sets the system name of this system entry.
	 *
	 * @param systemName the system name of this system entry
	 */
	public void setSystemName(String systemName);

	/**
	 * Returns the system title of this system entry.
	 *
	 * @return the system title of this system entry
	 */
	@AutoEscape
	public String getSystemTitle();

	/**
	 * Sets the system title of this system entry.
	 *
	 * @param systemTitle the system title of this system entry
	 */
	public void setSystemTitle(String systemTitle);

	/**
	 * Returns the system type of this system entry.
	 *
	 * @return the system type of this system entry
	 */
	@AutoEscape
	public String getSystemType();

	/**
	 * Sets the system type of this system entry.
	 *
	 * @param systemType the system type of this system entry
	 */
	public void setSystemType(String systemType);

	/**
	 * Returns the description of this system entry.
	 *
	 * @return the description of this system entry
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this system entry.
	 *
	 * @param description the description of this system entry
	 */
	public void setDescription(String description);

	/**
	 * Returns the steward name of this system entry.
	 *
	 * @return the steward name of this system entry
	 */
	@AutoEscape
	public String getStewardName();

	/**
	 * Sets the steward name of this system entry.
	 *
	 * @param stewardName the steward name of this system entry
	 */
	public void setStewardName(String stewardName);

	/**
	 * Returns the steward ID of this system entry.
	 *
	 * @return the steward ID of this system entry
	 */
	@AutoEscape
	public String getStewardId();

	/**
	 * Sets the steward ID of this system entry.
	 *
	 * @param stewardId the steward ID of this system entry
	 */
	public void setStewardId(String stewardId);

	/**
	 * Returns the steward department of this system entry.
	 *
	 * @return the steward department of this system entry
	 */
	@AutoEscape
	public String getStewardDepartment();

	/**
	 * Sets the steward department of this system entry.
	 *
	 * @param stewardDepartment the steward department of this system entry
	 */
	public void setStewardDepartment(String stewardDepartment);

	/**
	 * Returns the business owner name of this system entry.
	 *
	 * @return the business owner name of this system entry
	 */
	@AutoEscape
	public String getBusinessOwnerName();

	/**
	 * Sets the business owner name of this system entry.
	 *
	 * @param businessOwnerName the business owner name of this system entry
	 */
	public void setBusinessOwnerName(String businessOwnerName);

	/**
	 * Returns the business owner ID of this system entry.
	 *
	 * @return the business owner ID of this system entry
	 */
	@AutoEscape
	public String getBusinessOwnerId();

	/**
	 * Sets the business owner ID of this system entry.
	 *
	 * @param businessOwnerId the business owner ID of this system entry
	 */
	public void setBusinessOwnerId(String businessOwnerId);

	/**
	 * Returns the contact person name of this system entry.
	 *
	 * @return the contact person name of this system entry
	 */
	@AutoEscape
	public String getContactPersonName();

	/**
	 * Sets the contact person name of this system entry.
	 *
	 * @param contactPersonName the contact person name of this system entry
	 */
	public void setContactPersonName(String contactPersonName);

	/**
	 * Returns the contact person ID of this system entry.
	 *
	 * @return the contact person ID of this system entry
	 */
	@AutoEscape
	public String getContactPersonId();

	/**
	 * Sets the contact person ID of this system entry.
	 *
	 * @param contactPersonId the contact person ID of this system entry
	 */
	public void setContactPersonId(String contactPersonId);

	/**
	 * Returns the sandbox name of this system entry.
	 *
	 * @return the sandbox name of this system entry
	 */
	@AutoEscape
	public String getSandboxName();

	/**
	 * Sets the sandbox name of this system entry.
	 *
	 * @param sandboxName the sandbox name of this system entry
	 */
	public void setSandboxName(String sandboxName);

	/**
	 * Returns the gestor department ID of this system entry.
	 *
	 * @return the gestor department ID of this system entry
	 */
	@AutoEscape
	public String getGestorDepartmentId();

	/**
	 * Sets the gestor department ID of this system entry.
	 *
	 * @param gestorDepartmentId the gestor department ID of this system entry
	 */
	public void setGestorDepartmentId(String gestorDepartmentId);

	/**
	 * Returns the gestor department name of this system entry.
	 *
	 * @return the gestor department name of this system entry
	 */
	@AutoEscape
	public String getGestorDepartmentName();

	/**
	 * Sets the gestor department name of this system entry.
	 *
	 * @param gestorDepartmentName the gestor department name of this system entry
	 */
	public void setGestorDepartmentName(String gestorDepartmentName);

	/**
	 * Returns the role of this system entry.
	 *
	 * @return the role of this system entry
	 */
	@AutoEscape
	public String getRole();

	/**
	 * Sets the role of this system entry.
	 *
	 * @param role the role of this system entry
	 */
	public void setRole(String role);

	/**
	 * Returns the snow asset tag ID of this system entry.
	 *
	 * @return the snow asset tag ID of this system entry
	 */
	@AutoEscape
	public String getSnowAssetTagId();

	/**
	 * Sets the snow asset tag ID of this system entry.
	 *
	 * @param snowAssetTagId the snow asset tag ID of this system entry
	 */
	public void setSnowAssetTagId(String snowAssetTagId);

	/**
	 * Returns the snow asset tag name of this system entry.
	 *
	 * @return the snow asset tag name of this system entry
	 */
	@AutoEscape
	public String getSnowAssetTagName();

	/**
	 * Sets the snow asset tag name of this system entry.
	 *
	 * @param snowAssetTagName the snow asset tag name of this system entry
	 */
	public void setSnowAssetTagName(String snowAssetTagName);

	/**
	 * Returns the is sla signed of this system entry.
	 *
	 * @return the is sla signed of this system entry
	 */
	public boolean getIsSlaSigned();

	/**
	 * Returns <code>true</code> if this system entry is is sla signed.
	 *
	 * @return <code>true</code> if this system entry is is sla signed; <code>false</code> otherwise
	 */
	public boolean isIsSlaSigned();

	/**
	 * Sets whether this system entry is is sla signed.
	 *
	 * @param isSlaSigned the is sla signed of this system entry
	 */
	public void setIsSlaSigned(boolean isSlaSigned);

	/**
	 * Returns the is self bi of this system entry.
	 *
	 * @return the is self bi of this system entry
	 */
	public boolean getIsSelfBi();

	/**
	 * Returns <code>true</code> if this system entry is is self bi.
	 *
	 * @return <code>true</code> if this system entry is is self bi; <code>false</code> otherwise
	 */
	public boolean isIsSelfBi();

	/**
	 * Sets whether this system entry is is self bi.
	 *
	 * @param isSelfBi the is self bi of this system entry
	 */
	public void setIsSelfBi(boolean isSelfBi);

	/**
	 * Returns the is active of this system entry.
	 *
	 * @return the is active of this system entry
	 */
	public boolean getIsActive();

	/**
	 * Returns <code>true</code> if this system entry is is active.
	 *
	 * @return <code>true</code> if this system entry is is active; <code>false</code> otherwise
	 */
	public boolean isIsActive();

	/**
	 * Sets whether this system entry is is active.
	 *
	 * @param isActive the is active of this system entry
	 */
	public void setIsActive(boolean isActive);

	/**
	 * Returns the group ID of this system entry.
	 *
	 * @return the group ID of this system entry
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this system entry.
	 *
	 * @param groupId the group ID of this system entry
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this system entry.
	 *
	 * @return the company ID of this system entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this system entry.
	 *
	 * @param companyId the company ID of this system entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this system entry.
	 *
	 * @return the user ID of this system entry
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this system entry.
	 *
	 * @param userId the user ID of this system entry
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this system entry.
	 *
	 * @return the user uuid of this system entry
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this system entry.
	 *
	 * @param userUuid the user uuid of this system entry
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this system entry.
	 *
	 * @return the user name of this system entry
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this system entry.
	 *
	 * @param userName the user name of this system entry
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this system entry.
	 *
	 * @return the create date of this system entry
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this system entry.
	 *
	 * @param createDate the create date of this system entry
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this system entry.
	 *
	 * @return the modified date of this system entry
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this system entry.
	 *
	 * @param modifiedDate the modified date of this system entry
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the url title of this system entry.
	 *
	 * @return the url title of this system entry
	 */
	@AutoEscape
	public String getUrlTitle();

	/**
	 * Sets the url title of this system entry.
	 *
	 * @param urlTitle the url title of this system entry
	 */
	public void setUrlTitle(String urlTitle);

	/**
	 * Returns the status of this system entry.
	 *
	 * @return the status of this system entry
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this system entry.
	 *
	 * @param status the status of this system entry
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this system entry.
	 *
	 * @return the status by user ID of this system entry
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this system entry.
	 *
	 * @param statusByUserId the status by user ID of this system entry
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this system entry.
	 *
	 * @return the status by user uuid of this system entry
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this system entry.
	 *
	 * @param statusByUserUuid the status by user uuid of this system entry
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this system entry.
	 *
	 * @return the status by user name of this system entry
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this system entry.
	 *
	 * @param statusByUserName the status by user name of this system entry
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this system entry.
	 *
	 * @return the status date of this system entry
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this system entry.
	 *
	 * @param statusDate the status date of this system entry
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns the trash entry created when this system entry was moved to the Recycle Bin. The trash entry may belong to one of the ancestors of this system entry.
	 *
	 * @return the trash entry created when this system entry was moved to the Recycle Bin
	 */
	@Override
	public com.liferay.trash.kernel.model.TrashEntry getTrashEntry()
		throws PortalException;

	/**
	 * Returns the class primary key of the trash entry for this system entry.
	 *
	 * @return the class primary key of the trash entry for this system entry
	 */
	@Override
	public long getTrashEntryClassPK();

	/**
	 * Returns the trash handler for this system entry.
	 *
	 * @return the trash handler for this system entry
	 * @deprecated As of Judson (7.1.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public com.liferay.portal.kernel.trash.TrashHandler getTrashHandler();

	/**
	 * Returns <code>true</code> if this system entry is in the Recycle Bin.
	 *
	 * @return <code>true</code> if this system entry is in the Recycle Bin; <code>false</code> otherwise
	 */
	@Override
	public boolean isInTrash();

	/**
	 * Returns <code>true</code> if the parent of this system entry is in the Recycle Bin.
	 *
	 * @return <code>true</code> if the parent of this system entry is in the Recycle Bin; <code>false</code> otherwise
	 */
	@Override
	public boolean isInTrashContainer();

	@Override
	public boolean isInTrashExplicitly();

	@Override
	public boolean isInTrashImplicitly();

	/**
	 * Returns <code>true</code> if this system entry is approved.
	 *
	 * @return <code>true</code> if this system entry is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this system entry is denied.
	 *
	 * @return <code>true</code> if this system entry is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this system entry is a draft.
	 *
	 * @return <code>true</code> if this system entry is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this system entry is expired.
	 *
	 * @return <code>true</code> if this system entry is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this system entry is inactive.
	 *
	 * @return <code>true</code> if this system entry is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this system entry is incomplete.
	 *
	 * @return <code>true</code> if this system entry is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this system entry is pending.
	 *
	 * @return <code>true</code> if this system entry is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this system entry is scheduled.
	 *
	 * @return <code>true</code> if this system entry is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

	@Override
	public SystemEntry cloneWithOriginalValues();

}