/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package cz.csob.ency.workflow.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import cz.csob.ency.workflow.model.EncyWorkflowInstance;
import cz.csob.ency.workflow.model.EncyWorkflowInstanceModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the EncyWorkflowInstance service. Represents a row in the &quot;ency_workflowinstance&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>EncyWorkflowInstanceModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EncyWorkflowInstanceImpl}.
 * </p>
 *
 * @author Miroslav Čermák
 * @see EncyWorkflowInstanceImpl
 * @generated
 */
public class EncyWorkflowInstanceModelImpl
	extends BaseModelImpl<EncyWorkflowInstance>
	implements EncyWorkflowInstanceModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a ency workflow instance model instance should use the <code>EncyWorkflowInstance</code> interface instead.
	 */
	public static final String TABLE_NAME = "ency_workflowinstance";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"workflowInstanceId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"workflowId", Types.BIGINT}, {"workflowVersion", Types.BIGINT},
		{"className", Types.VARCHAR}, {"classPK", Types.BIGINT},
		{"workflowContext", Types.CLOB}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("workflowInstanceId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("workflowId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("workflowVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("className", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("classPK", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("workflowContext", Types.CLOB);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ency_workflowinstance (uuid_ VARCHAR(75) null,workflowInstanceId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,workflowId LONG,workflowVersion LONG,className VARCHAR(1000) null,classPK LONG,workflowContext TEXT null)";

	public static final String TABLE_SQL_DROP =
		"drop table ency_workflowinstance";

	public static final String ORDER_BY_JPQL =
		" ORDER BY encyWorkflowInstance.workflowInstanceId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ency_workflowinstance.workflowInstanceId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CLASSNAME_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CLASSPK_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long WORKFLOWINSTANCEID_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public EncyWorkflowInstanceModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _workflowInstanceId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setWorkflowInstanceId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _workflowInstanceId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return EncyWorkflowInstance.class;
	}

	@Override
	public String getModelClassName() {
		return EncyWorkflowInstance.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<EncyWorkflowInstance, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<EncyWorkflowInstance, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EncyWorkflowInstance, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((EncyWorkflowInstance)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<EncyWorkflowInstance, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<EncyWorkflowInstance, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(EncyWorkflowInstance)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<EncyWorkflowInstance, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<EncyWorkflowInstance, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<EncyWorkflowInstance, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<EncyWorkflowInstance, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<EncyWorkflowInstance, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<EncyWorkflowInstance, Object>>();
		Map<String, BiConsumer<EncyWorkflowInstance, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<EncyWorkflowInstance, ?>>();

		attributeGetterFunctions.put("uuid", EncyWorkflowInstance::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<EncyWorkflowInstance, String>)
				EncyWorkflowInstance::setUuid);
		attributeGetterFunctions.put(
			"workflowInstanceId", EncyWorkflowInstance::getWorkflowInstanceId);
		attributeSetterBiConsumers.put(
			"workflowInstanceId",
			(BiConsumer<EncyWorkflowInstance, Long>)
				EncyWorkflowInstance::setWorkflowInstanceId);
		attributeGetterFunctions.put(
			"groupId", EncyWorkflowInstance::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<EncyWorkflowInstance, Long>)
				EncyWorkflowInstance::setGroupId);
		attributeGetterFunctions.put(
			"companyId", EncyWorkflowInstance::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<EncyWorkflowInstance, Long>)
				EncyWorkflowInstance::setCompanyId);
		attributeGetterFunctions.put("userId", EncyWorkflowInstance::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<EncyWorkflowInstance, Long>)
				EncyWorkflowInstance::setUserId);
		attributeGetterFunctions.put(
			"userName", EncyWorkflowInstance::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<EncyWorkflowInstance, String>)
				EncyWorkflowInstance::setUserName);
		attributeGetterFunctions.put(
			"createDate", EncyWorkflowInstance::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<EncyWorkflowInstance, Date>)
				EncyWorkflowInstance::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", EncyWorkflowInstance::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<EncyWorkflowInstance, Date>)
				EncyWorkflowInstance::setModifiedDate);
		attributeGetterFunctions.put(
			"workflowId", EncyWorkflowInstance::getWorkflowId);
		attributeSetterBiConsumers.put(
			"workflowId",
			(BiConsumer<EncyWorkflowInstance, Long>)
				EncyWorkflowInstance::setWorkflowId);
		attributeGetterFunctions.put(
			"workflowVersion", EncyWorkflowInstance::getWorkflowVersion);
		attributeSetterBiConsumers.put(
			"workflowVersion",
			(BiConsumer<EncyWorkflowInstance, Long>)
				EncyWorkflowInstance::setWorkflowVersion);
		attributeGetterFunctions.put(
			"className", EncyWorkflowInstance::getClassName);
		attributeSetterBiConsumers.put(
			"className",
			(BiConsumer<EncyWorkflowInstance, String>)
				EncyWorkflowInstance::setClassName);
		attributeGetterFunctions.put(
			"classPK", EncyWorkflowInstance::getClassPK);
		attributeSetterBiConsumers.put(
			"classPK",
			(BiConsumer<EncyWorkflowInstance, Long>)
				EncyWorkflowInstance::setClassPK);
		attributeGetterFunctions.put(
			"workflowContext", EncyWorkflowInstance::getWorkflowContext);
		attributeSetterBiConsumers.put(
			"workflowContext",
			(BiConsumer<EncyWorkflowInstance, String>)
				EncyWorkflowInstance::setWorkflowContext);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@Override
	public long getWorkflowInstanceId() {
		return _workflowInstanceId;
	}

	@Override
	public void setWorkflowInstanceId(long workflowInstanceId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_workflowInstanceId = workflowInstanceId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public long getWorkflowId() {
		return _workflowId;
	}

	@Override
	public void setWorkflowId(long workflowId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_workflowId = workflowId;
	}

	@Override
	public long getWorkflowVersion() {
		return _workflowVersion;
	}

	@Override
	public void setWorkflowVersion(long workflowVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_workflowVersion = workflowVersion;
	}

	@Override
	public String getClassName() {
		if (_className == null) {
			return "";
		}
		else {
			return _className;
		}
	}

	@Override
	public void setClassName(String className) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_className = className;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalClassName() {
		return getColumnOriginalValue("className");
	}

	@Override
	public long getClassPK() {
		return _classPK;
	}

	@Override
	public void setClassPK(long classPK) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_classPK = classPK;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalClassPK() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("classPK"));
	}

	@Override
	public String getWorkflowContext() {
		if (_workflowContext == null) {
			return "";
		}
		else {
			return _workflowContext;
		}
	}

	@Override
	public void setWorkflowContext(String workflowContext) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_workflowContext = workflowContext;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(EncyWorkflowInstance.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), EncyWorkflowInstance.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public EncyWorkflowInstance toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, EncyWorkflowInstance>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EncyWorkflowInstanceImpl encyWorkflowInstanceImpl =
			new EncyWorkflowInstanceImpl();

		encyWorkflowInstanceImpl.setUuid(getUuid());
		encyWorkflowInstanceImpl.setWorkflowInstanceId(getWorkflowInstanceId());
		encyWorkflowInstanceImpl.setGroupId(getGroupId());
		encyWorkflowInstanceImpl.setCompanyId(getCompanyId());
		encyWorkflowInstanceImpl.setUserId(getUserId());
		encyWorkflowInstanceImpl.setUserName(getUserName());
		encyWorkflowInstanceImpl.setCreateDate(getCreateDate());
		encyWorkflowInstanceImpl.setModifiedDate(getModifiedDate());
		encyWorkflowInstanceImpl.setWorkflowId(getWorkflowId());
		encyWorkflowInstanceImpl.setWorkflowVersion(getWorkflowVersion());
		encyWorkflowInstanceImpl.setClassName(getClassName());
		encyWorkflowInstanceImpl.setClassPK(getClassPK());
		encyWorkflowInstanceImpl.setWorkflowContext(getWorkflowContext());

		encyWorkflowInstanceImpl.resetOriginalValues();

		return encyWorkflowInstanceImpl;
	}

	@Override
	public EncyWorkflowInstance cloneWithOriginalValues() {
		EncyWorkflowInstanceImpl encyWorkflowInstanceImpl =
			new EncyWorkflowInstanceImpl();

		encyWorkflowInstanceImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		encyWorkflowInstanceImpl.setWorkflowInstanceId(
			this.<Long>getColumnOriginalValue("workflowInstanceId"));
		encyWorkflowInstanceImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		encyWorkflowInstanceImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		encyWorkflowInstanceImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		encyWorkflowInstanceImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		encyWorkflowInstanceImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		encyWorkflowInstanceImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		encyWorkflowInstanceImpl.setWorkflowId(
			this.<Long>getColumnOriginalValue("workflowId"));
		encyWorkflowInstanceImpl.setWorkflowVersion(
			this.<Long>getColumnOriginalValue("workflowVersion"));
		encyWorkflowInstanceImpl.setClassName(
			this.<String>getColumnOriginalValue("className"));
		encyWorkflowInstanceImpl.setClassPK(
			this.<Long>getColumnOriginalValue("classPK"));
		encyWorkflowInstanceImpl.setWorkflowContext(
			this.<String>getColumnOriginalValue("workflowContext"));

		return encyWorkflowInstanceImpl;
	}

	@Override
	public int compareTo(EncyWorkflowInstance encyWorkflowInstance) {
		long primaryKey = encyWorkflowInstance.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof EncyWorkflowInstance)) {
			return false;
		}

		EncyWorkflowInstance encyWorkflowInstance =
			(EncyWorkflowInstance)object;

		long primaryKey = encyWorkflowInstance.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<EncyWorkflowInstance> toCacheModel() {
		EncyWorkflowInstanceCacheModel encyWorkflowInstanceCacheModel =
			new EncyWorkflowInstanceCacheModel();

		encyWorkflowInstanceCacheModel.uuid = getUuid();

		String uuid = encyWorkflowInstanceCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			encyWorkflowInstanceCacheModel.uuid = null;
		}

		encyWorkflowInstanceCacheModel.workflowInstanceId =
			getWorkflowInstanceId();

		encyWorkflowInstanceCacheModel.groupId = getGroupId();

		encyWorkflowInstanceCacheModel.companyId = getCompanyId();

		encyWorkflowInstanceCacheModel.userId = getUserId();

		encyWorkflowInstanceCacheModel.userName = getUserName();

		String userName = encyWorkflowInstanceCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			encyWorkflowInstanceCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			encyWorkflowInstanceCacheModel.createDate = createDate.getTime();
		}
		else {
			encyWorkflowInstanceCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			encyWorkflowInstanceCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			encyWorkflowInstanceCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		encyWorkflowInstanceCacheModel.workflowId = getWorkflowId();

		encyWorkflowInstanceCacheModel.workflowVersion = getWorkflowVersion();

		encyWorkflowInstanceCacheModel.className = getClassName();

		String className = encyWorkflowInstanceCacheModel.className;

		if ((className != null) && (className.length() == 0)) {
			encyWorkflowInstanceCacheModel.className = null;
		}

		encyWorkflowInstanceCacheModel.classPK = getClassPK();

		encyWorkflowInstanceCacheModel.workflowContext = getWorkflowContext();

		String workflowContext = encyWorkflowInstanceCacheModel.workflowContext;

		if ((workflowContext != null) && (workflowContext.length() == 0)) {
			encyWorkflowInstanceCacheModel.workflowContext = null;
		}

		return encyWorkflowInstanceCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<EncyWorkflowInstance, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<EncyWorkflowInstance, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EncyWorkflowInstance, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(EncyWorkflowInstance)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<EncyWorkflowInstance, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<EncyWorkflowInstance, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EncyWorkflowInstance, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply((EncyWorkflowInstance)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, EncyWorkflowInstance>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					EncyWorkflowInstance.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _workflowInstanceId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _workflowId;
	private long _workflowVersion;
	private String _className;
	private long _classPK;
	private String _workflowContext;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<EncyWorkflowInstance, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((EncyWorkflowInstance)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("workflowInstanceId", _workflowInstanceId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("workflowId", _workflowId);
		_columnOriginalValues.put("workflowVersion", _workflowVersion);
		_columnOriginalValues.put("className", _className);
		_columnOriginalValues.put("classPK", _classPK);
		_columnOriginalValues.put("workflowContext", _workflowContext);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("workflowInstanceId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("workflowId", 256L);

		columnBitmasks.put("workflowVersion", 512L);

		columnBitmasks.put("className", 1024L);

		columnBitmasks.put("classPK", 2048L);

		columnBitmasks.put("workflowContext", 4096L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private EncyWorkflowInstance _escapedModel;

}