/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package cz.csob.ency.workflow.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import cz.csob.ency.workflow.model.EncyWorkflowStateInstance;
import cz.csob.ency.workflow.model.EncyWorkflowStateInstanceModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the EncyWorkflowStateInstance service. Represents a row in the &quot;ency_workflowstateinstance&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>EncyWorkflowStateInstanceModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EncyWorkflowStateInstanceImpl}.
 * </p>
 *
 * @author Miroslav Čermák
 * @see EncyWorkflowStateInstanceImpl
 * @generated
 */
public class EncyWorkflowStateInstanceModelImpl
	extends BaseModelImpl<EncyWorkflowStateInstance>
	implements EncyWorkflowStateInstanceModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a ency workflow state instance model instance should use the <code>EncyWorkflowStateInstance</code> interface instead.
	 */
	public static final String TABLE_NAME = "ency_workflowstateinstance";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"stateInstanceId", Types.BIGINT},
		{"stateId", Types.BIGINT}, {"workflowId", Types.BIGINT},
		{"workflowInstanceId", Types.BIGINT}, {"version", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"completedDate", Types.TIMESTAMP}, {"workflowContext", Types.CLOB}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("stateInstanceId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("stateId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("workflowId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("workflowInstanceId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("version", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("completedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("workflowContext", Types.CLOB);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ency_workflowstateinstance (uuid_ VARCHAR(75) null,stateInstanceId LONG not null primary key,stateId LONG,workflowId LONG,workflowInstanceId LONG,version LONG,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,completedDate DATE null,workflowContext TEXT null)";

	public static final String TABLE_SQL_DROP =
		"drop table ency_workflowstateinstance";

	public static final String ORDER_BY_JPQL =
		" ORDER BY encyWorkflowStateInstance.stateInstanceId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ency_workflowstateinstance.stateInstanceId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long WORKFLOWID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long WORKFLOWINSTANCEID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long STATEINSTANCEID_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public EncyWorkflowStateInstanceModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _stateInstanceId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setStateInstanceId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _stateInstanceId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return EncyWorkflowStateInstance.class;
	}

	@Override
	public String getModelClassName() {
		return EncyWorkflowStateInstance.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<EncyWorkflowStateInstance, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<EncyWorkflowStateInstance, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EncyWorkflowStateInstance, Object>
				attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((EncyWorkflowStateInstance)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<EncyWorkflowStateInstance, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<EncyWorkflowStateInstance, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(EncyWorkflowStateInstance)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<EncyWorkflowStateInstance, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<EncyWorkflowStateInstance, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map
		<String, Function<EncyWorkflowStateInstance, Object>>
			_attributeGetterFunctions;
	private static final Map
		<String, BiConsumer<EncyWorkflowStateInstance, Object>>
			_attributeSetterBiConsumers;

	static {
		Map<String, Function<EncyWorkflowStateInstance, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<EncyWorkflowStateInstance, Object>>();
		Map<String, BiConsumer<EncyWorkflowStateInstance, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<EncyWorkflowStateInstance, ?>>();

		attributeGetterFunctions.put(
			"uuid", EncyWorkflowStateInstance::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<EncyWorkflowStateInstance, String>)
				EncyWorkflowStateInstance::setUuid);
		attributeGetterFunctions.put(
			"stateInstanceId", EncyWorkflowStateInstance::getStateInstanceId);
		attributeSetterBiConsumers.put(
			"stateInstanceId",
			(BiConsumer<EncyWorkflowStateInstance, Long>)
				EncyWorkflowStateInstance::setStateInstanceId);
		attributeGetterFunctions.put(
			"stateId", EncyWorkflowStateInstance::getStateId);
		attributeSetterBiConsumers.put(
			"stateId",
			(BiConsumer<EncyWorkflowStateInstance, Long>)
				EncyWorkflowStateInstance::setStateId);
		attributeGetterFunctions.put(
			"workflowId", EncyWorkflowStateInstance::getWorkflowId);
		attributeSetterBiConsumers.put(
			"workflowId",
			(BiConsumer<EncyWorkflowStateInstance, Long>)
				EncyWorkflowStateInstance::setWorkflowId);
		attributeGetterFunctions.put(
			"workflowInstanceId",
			EncyWorkflowStateInstance::getWorkflowInstanceId);
		attributeSetterBiConsumers.put(
			"workflowInstanceId",
			(BiConsumer<EncyWorkflowStateInstance, Long>)
				EncyWorkflowStateInstance::setWorkflowInstanceId);
		attributeGetterFunctions.put(
			"version", EncyWorkflowStateInstance::getVersion);
		attributeSetterBiConsumers.put(
			"version",
			(BiConsumer<EncyWorkflowStateInstance, Long>)
				EncyWorkflowStateInstance::setVersion);
		attributeGetterFunctions.put(
			"groupId", EncyWorkflowStateInstance::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<EncyWorkflowStateInstance, Long>)
				EncyWorkflowStateInstance::setGroupId);
		attributeGetterFunctions.put(
			"companyId", EncyWorkflowStateInstance::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<EncyWorkflowStateInstance, Long>)
				EncyWorkflowStateInstance::setCompanyId);
		attributeGetterFunctions.put(
			"userId", EncyWorkflowStateInstance::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<EncyWorkflowStateInstance, Long>)
				EncyWorkflowStateInstance::setUserId);
		attributeGetterFunctions.put(
			"userName", EncyWorkflowStateInstance::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<EncyWorkflowStateInstance, String>)
				EncyWorkflowStateInstance::setUserName);
		attributeGetterFunctions.put(
			"createDate", EncyWorkflowStateInstance::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<EncyWorkflowStateInstance, Date>)
				EncyWorkflowStateInstance::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", EncyWorkflowStateInstance::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<EncyWorkflowStateInstance, Date>)
				EncyWorkflowStateInstance::setModifiedDate);
		attributeGetterFunctions.put(
			"completedDate", EncyWorkflowStateInstance::getCompletedDate);
		attributeSetterBiConsumers.put(
			"completedDate",
			(BiConsumer<EncyWorkflowStateInstance, Date>)
				EncyWorkflowStateInstance::setCompletedDate);
		attributeGetterFunctions.put(
			"workflowContext", EncyWorkflowStateInstance::getWorkflowContext);
		attributeSetterBiConsumers.put(
			"workflowContext",
			(BiConsumer<EncyWorkflowStateInstance, String>)
				EncyWorkflowStateInstance::setWorkflowContext);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@Override
	public long getStateInstanceId() {
		return _stateInstanceId;
	}

	@Override
	public void setStateInstanceId(long stateInstanceId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_stateInstanceId = stateInstanceId;
	}

	@Override
	public long getStateId() {
		return _stateId;
	}

	@Override
	public void setStateId(long stateId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_stateId = stateId;
	}

	@Override
	public long getWorkflowId() {
		return _workflowId;
	}

	@Override
	public void setWorkflowId(long workflowId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_workflowId = workflowId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalWorkflowId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("workflowId"));
	}

	@Override
	public long getWorkflowInstanceId() {
		return _workflowInstanceId;
	}

	@Override
	public void setWorkflowInstanceId(long workflowInstanceId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_workflowInstanceId = workflowInstanceId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalWorkflowInstanceId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("workflowInstanceId"));
	}

	@Override
	public long getVersion() {
		return _version;
	}

	@Override
	public void setVersion(long version) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_version = version;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public Date getCompletedDate() {
		return _completedDate;
	}

	@Override
	public void setCompletedDate(Date completedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_completedDate = completedDate;
	}

	@Override
	public String getWorkflowContext() {
		if (_workflowContext == null) {
			return "";
		}
		else {
			return _workflowContext;
		}
	}

	@Override
	public void setWorkflowContext(String workflowContext) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_workflowContext = workflowContext;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(
				EncyWorkflowStateInstance.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), EncyWorkflowStateInstance.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public EncyWorkflowStateInstance toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, EncyWorkflowStateInstance>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EncyWorkflowStateInstanceImpl encyWorkflowStateInstanceImpl =
			new EncyWorkflowStateInstanceImpl();

		encyWorkflowStateInstanceImpl.setUuid(getUuid());
		encyWorkflowStateInstanceImpl.setStateInstanceId(getStateInstanceId());
		encyWorkflowStateInstanceImpl.setStateId(getStateId());
		encyWorkflowStateInstanceImpl.setWorkflowId(getWorkflowId());
		encyWorkflowStateInstanceImpl.setWorkflowInstanceId(
			getWorkflowInstanceId());
		encyWorkflowStateInstanceImpl.setVersion(getVersion());
		encyWorkflowStateInstanceImpl.setGroupId(getGroupId());
		encyWorkflowStateInstanceImpl.setCompanyId(getCompanyId());
		encyWorkflowStateInstanceImpl.setUserId(getUserId());
		encyWorkflowStateInstanceImpl.setUserName(getUserName());
		encyWorkflowStateInstanceImpl.setCreateDate(getCreateDate());
		encyWorkflowStateInstanceImpl.setModifiedDate(getModifiedDate());
		encyWorkflowStateInstanceImpl.setCompletedDate(getCompletedDate());
		encyWorkflowStateInstanceImpl.setWorkflowContext(getWorkflowContext());

		encyWorkflowStateInstanceImpl.resetOriginalValues();

		return encyWorkflowStateInstanceImpl;
	}

	@Override
	public EncyWorkflowStateInstance cloneWithOriginalValues() {
		EncyWorkflowStateInstanceImpl encyWorkflowStateInstanceImpl =
			new EncyWorkflowStateInstanceImpl();

		encyWorkflowStateInstanceImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		encyWorkflowStateInstanceImpl.setStateInstanceId(
			this.<Long>getColumnOriginalValue("stateInstanceId"));
		encyWorkflowStateInstanceImpl.setStateId(
			this.<Long>getColumnOriginalValue("stateId"));
		encyWorkflowStateInstanceImpl.setWorkflowId(
			this.<Long>getColumnOriginalValue("workflowId"));
		encyWorkflowStateInstanceImpl.setWorkflowInstanceId(
			this.<Long>getColumnOriginalValue("workflowInstanceId"));
		encyWorkflowStateInstanceImpl.setVersion(
			this.<Long>getColumnOriginalValue("version"));
		encyWorkflowStateInstanceImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		encyWorkflowStateInstanceImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		encyWorkflowStateInstanceImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		encyWorkflowStateInstanceImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		encyWorkflowStateInstanceImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		encyWorkflowStateInstanceImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		encyWorkflowStateInstanceImpl.setCompletedDate(
			this.<Date>getColumnOriginalValue("completedDate"));
		encyWorkflowStateInstanceImpl.setWorkflowContext(
			this.<String>getColumnOriginalValue("workflowContext"));

		return encyWorkflowStateInstanceImpl;
	}

	@Override
	public int compareTo(EncyWorkflowStateInstance encyWorkflowStateInstance) {
		long primaryKey = encyWorkflowStateInstance.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof EncyWorkflowStateInstance)) {
			return false;
		}

		EncyWorkflowStateInstance encyWorkflowStateInstance =
			(EncyWorkflowStateInstance)object;

		long primaryKey = encyWorkflowStateInstance.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<EncyWorkflowStateInstance> toCacheModel() {
		EncyWorkflowStateInstanceCacheModel
			encyWorkflowStateInstanceCacheModel =
				new EncyWorkflowStateInstanceCacheModel();

		encyWorkflowStateInstanceCacheModel.uuid = getUuid();

		String uuid = encyWorkflowStateInstanceCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			encyWorkflowStateInstanceCacheModel.uuid = null;
		}

		encyWorkflowStateInstanceCacheModel.stateInstanceId =
			getStateInstanceId();

		encyWorkflowStateInstanceCacheModel.stateId = getStateId();

		encyWorkflowStateInstanceCacheModel.workflowId = getWorkflowId();

		encyWorkflowStateInstanceCacheModel.workflowInstanceId =
			getWorkflowInstanceId();

		encyWorkflowStateInstanceCacheModel.version = getVersion();

		encyWorkflowStateInstanceCacheModel.groupId = getGroupId();

		encyWorkflowStateInstanceCacheModel.companyId = getCompanyId();

		encyWorkflowStateInstanceCacheModel.userId = getUserId();

		encyWorkflowStateInstanceCacheModel.userName = getUserName();

		String userName = encyWorkflowStateInstanceCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			encyWorkflowStateInstanceCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			encyWorkflowStateInstanceCacheModel.createDate =
				createDate.getTime();
		}
		else {
			encyWorkflowStateInstanceCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			encyWorkflowStateInstanceCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			encyWorkflowStateInstanceCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		Date completedDate = getCompletedDate();

		if (completedDate != null) {
			encyWorkflowStateInstanceCacheModel.completedDate =
				completedDate.getTime();
		}
		else {
			encyWorkflowStateInstanceCacheModel.completedDate = Long.MIN_VALUE;
		}

		encyWorkflowStateInstanceCacheModel.workflowContext =
			getWorkflowContext();

		String workflowContext =
			encyWorkflowStateInstanceCacheModel.workflowContext;

		if ((workflowContext != null) && (workflowContext.length() == 0)) {
			encyWorkflowStateInstanceCacheModel.workflowContext = null;
		}

		return encyWorkflowStateInstanceCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<EncyWorkflowStateInstance, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<EncyWorkflowStateInstance, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EncyWorkflowStateInstance, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(EncyWorkflowStateInstance)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<EncyWorkflowStateInstance, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<EncyWorkflowStateInstance, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EncyWorkflowStateInstance, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply((EncyWorkflowStateInstance)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, EncyWorkflowStateInstance>
				_escapedModelProxyProviderFunction =
					ProxyUtil.getProxyProviderFunction(
						EncyWorkflowStateInstance.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _stateInstanceId;
	private long _stateId;
	private long _workflowId;
	private long _workflowInstanceId;
	private long _version;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private Date _completedDate;
	private String _workflowContext;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<EncyWorkflowStateInstance, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((EncyWorkflowStateInstance)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("stateInstanceId", _stateInstanceId);
		_columnOriginalValues.put("stateId", _stateId);
		_columnOriginalValues.put("workflowId", _workflowId);
		_columnOriginalValues.put("workflowInstanceId", _workflowInstanceId);
		_columnOriginalValues.put("version", _version);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("completedDate", _completedDate);
		_columnOriginalValues.put("workflowContext", _workflowContext);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("stateInstanceId", 2L);

		columnBitmasks.put("stateId", 4L);

		columnBitmasks.put("workflowId", 8L);

		columnBitmasks.put("workflowInstanceId", 16L);

		columnBitmasks.put("version", 32L);

		columnBitmasks.put("groupId", 64L);

		columnBitmasks.put("companyId", 128L);

		columnBitmasks.put("userId", 256L);

		columnBitmasks.put("userName", 512L);

		columnBitmasks.put("createDate", 1024L);

		columnBitmasks.put("modifiedDate", 2048L);

		columnBitmasks.put("completedDate", 4096L);

		columnBitmasks.put("workflowContext", 8192L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private EncyWorkflowStateInstance _escapedModel;

}