/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package cz.csob.ency.workflow.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import cz.csob.ency.workflow.model.EncyWorkflowLink;
import cz.csob.ency.workflow.model.EncyWorkflowLinkModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the EncyWorkflowLink service. Represents a row in the &quot;ency_workflowlink&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>EncyWorkflowLinkModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EncyWorkflowLinkImpl}.
 * </p>
 *
 * @author Miroslav Čermák
 * @see EncyWorkflowLinkImpl
 * @generated
 */
public class EncyWorkflowLinkModelImpl
	extends BaseModelImpl<EncyWorkflowLink> implements EncyWorkflowLinkModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a ency workflow link model instance should use the <code>EncyWorkflowLink</code> interface instead.
	 */
	public static final String TABLE_NAME = "ency_workflowlink";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"workflowLinkId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"className", Types.VARCHAR}, {"folderClassName", Types.VARCHAR},
		{"folderPK", Types.BIGINT}, {"workflowId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("workflowLinkId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("className", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("folderClassName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("folderPK", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("workflowId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ency_workflowlink (uuid_ VARCHAR(75) null,workflowLinkId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,className VARCHAR(1000) null,folderClassName VARCHAR(1000) null,folderPK LONG,workflowId LONG)";

	public static final String TABLE_SQL_DROP = "drop table ency_workflowlink";

	public static final String ORDER_BY_JPQL =
		" ORDER BY encyWorkflowLink.workflowLinkId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ency_workflowlink.workflowLinkId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CLASSNAME_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long FOLDERCLASSNAME_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long FOLDERPK_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long WORKFLOWID_COLUMN_BITMASK = 64L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long WORKFLOWLINKID_COLUMN_BITMASK = 128L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public EncyWorkflowLinkModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _workflowLinkId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setWorkflowLinkId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _workflowLinkId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return EncyWorkflowLink.class;
	}

	@Override
	public String getModelClassName() {
		return EncyWorkflowLink.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<EncyWorkflowLink, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<EncyWorkflowLink, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EncyWorkflowLink, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((EncyWorkflowLink)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<EncyWorkflowLink, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<EncyWorkflowLink, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(EncyWorkflowLink)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<EncyWorkflowLink, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<EncyWorkflowLink, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<EncyWorkflowLink, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<EncyWorkflowLink, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<EncyWorkflowLink, Object>>
			attributeGetterFunctions =
				new LinkedHashMap<String, Function<EncyWorkflowLink, Object>>();
		Map<String, BiConsumer<EncyWorkflowLink, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<EncyWorkflowLink, ?>>();

		attributeGetterFunctions.put("uuid", EncyWorkflowLink::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<EncyWorkflowLink, String>)EncyWorkflowLink::setUuid);
		attributeGetterFunctions.put(
			"workflowLinkId", EncyWorkflowLink::getWorkflowLinkId);
		attributeSetterBiConsumers.put(
			"workflowLinkId",
			(BiConsumer<EncyWorkflowLink, Long>)
				EncyWorkflowLink::setWorkflowLinkId);
		attributeGetterFunctions.put("groupId", EncyWorkflowLink::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<EncyWorkflowLink, Long>)EncyWorkflowLink::setGroupId);
		attributeGetterFunctions.put(
			"companyId", EncyWorkflowLink::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<EncyWorkflowLink, Long>)EncyWorkflowLink::setCompanyId);
		attributeGetterFunctions.put("userId", EncyWorkflowLink::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<EncyWorkflowLink, Long>)EncyWorkflowLink::setUserId);
		attributeGetterFunctions.put("userName", EncyWorkflowLink::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<EncyWorkflowLink, String>)
				EncyWorkflowLink::setUserName);
		attributeGetterFunctions.put(
			"createDate", EncyWorkflowLink::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<EncyWorkflowLink, Date>)
				EncyWorkflowLink::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", EncyWorkflowLink::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<EncyWorkflowLink, Date>)
				EncyWorkflowLink::setModifiedDate);
		attributeGetterFunctions.put(
			"className", EncyWorkflowLink::getClassName);
		attributeSetterBiConsumers.put(
			"className",
			(BiConsumer<EncyWorkflowLink, String>)
				EncyWorkflowLink::setClassName);
		attributeGetterFunctions.put(
			"folderClassName", EncyWorkflowLink::getFolderClassName);
		attributeSetterBiConsumers.put(
			"folderClassName",
			(BiConsumer<EncyWorkflowLink, String>)
				EncyWorkflowLink::setFolderClassName);
		attributeGetterFunctions.put("folderPK", EncyWorkflowLink::getFolderPK);
		attributeSetterBiConsumers.put(
			"folderPK",
			(BiConsumer<EncyWorkflowLink, Long>)EncyWorkflowLink::setFolderPK);
		attributeGetterFunctions.put(
			"workflowId", EncyWorkflowLink::getWorkflowId);
		attributeSetterBiConsumers.put(
			"workflowId",
			(BiConsumer<EncyWorkflowLink, Long>)
				EncyWorkflowLink::setWorkflowId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@Override
	public long getWorkflowLinkId() {
		return _workflowLinkId;
	}

	@Override
	public void setWorkflowLinkId(long workflowLinkId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_workflowLinkId = workflowLinkId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getClassName() {
		if (_className == null) {
			return "";
		}
		else {
			return _className;
		}
	}

	@Override
	public void setClassName(String className) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_className = className;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalClassName() {
		return getColumnOriginalValue("className");
	}

	@Override
	public String getFolderClassName() {
		if (_folderClassName == null) {
			return "";
		}
		else {
			return _folderClassName;
		}
	}

	@Override
	public void setFolderClassName(String folderClassName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_folderClassName = folderClassName;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalFolderClassName() {
		return getColumnOriginalValue("folderClassName");
	}

	@Override
	public long getFolderPK() {
		return _folderPK;
	}

	@Override
	public void setFolderPK(long folderPK) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_folderPK = folderPK;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalFolderPK() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("folderPK"));
	}

	@Override
	public long getWorkflowId() {
		return _workflowId;
	}

	@Override
	public void setWorkflowId(long workflowId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_workflowId = workflowId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalWorkflowId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("workflowId"));
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(EncyWorkflowLink.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), EncyWorkflowLink.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public EncyWorkflowLink toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, EncyWorkflowLink>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EncyWorkflowLinkImpl encyWorkflowLinkImpl = new EncyWorkflowLinkImpl();

		encyWorkflowLinkImpl.setUuid(getUuid());
		encyWorkflowLinkImpl.setWorkflowLinkId(getWorkflowLinkId());
		encyWorkflowLinkImpl.setGroupId(getGroupId());
		encyWorkflowLinkImpl.setCompanyId(getCompanyId());
		encyWorkflowLinkImpl.setUserId(getUserId());
		encyWorkflowLinkImpl.setUserName(getUserName());
		encyWorkflowLinkImpl.setCreateDate(getCreateDate());
		encyWorkflowLinkImpl.setModifiedDate(getModifiedDate());
		encyWorkflowLinkImpl.setClassName(getClassName());
		encyWorkflowLinkImpl.setFolderClassName(getFolderClassName());
		encyWorkflowLinkImpl.setFolderPK(getFolderPK());
		encyWorkflowLinkImpl.setWorkflowId(getWorkflowId());

		encyWorkflowLinkImpl.resetOriginalValues();

		return encyWorkflowLinkImpl;
	}

	@Override
	public EncyWorkflowLink cloneWithOriginalValues() {
		EncyWorkflowLinkImpl encyWorkflowLinkImpl = new EncyWorkflowLinkImpl();

		encyWorkflowLinkImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		encyWorkflowLinkImpl.setWorkflowLinkId(
			this.<Long>getColumnOriginalValue("workflowLinkId"));
		encyWorkflowLinkImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		encyWorkflowLinkImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		encyWorkflowLinkImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		encyWorkflowLinkImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		encyWorkflowLinkImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		encyWorkflowLinkImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		encyWorkflowLinkImpl.setClassName(
			this.<String>getColumnOriginalValue("className"));
		encyWorkflowLinkImpl.setFolderClassName(
			this.<String>getColumnOriginalValue("folderClassName"));
		encyWorkflowLinkImpl.setFolderPK(
			this.<Long>getColumnOriginalValue("folderPK"));
		encyWorkflowLinkImpl.setWorkflowId(
			this.<Long>getColumnOriginalValue("workflowId"));

		return encyWorkflowLinkImpl;
	}

	@Override
	public int compareTo(EncyWorkflowLink encyWorkflowLink) {
		long primaryKey = encyWorkflowLink.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof EncyWorkflowLink)) {
			return false;
		}

		EncyWorkflowLink encyWorkflowLink = (EncyWorkflowLink)object;

		long primaryKey = encyWorkflowLink.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<EncyWorkflowLink> toCacheModel() {
		EncyWorkflowLinkCacheModel encyWorkflowLinkCacheModel =
			new EncyWorkflowLinkCacheModel();

		encyWorkflowLinkCacheModel.uuid = getUuid();

		String uuid = encyWorkflowLinkCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			encyWorkflowLinkCacheModel.uuid = null;
		}

		encyWorkflowLinkCacheModel.workflowLinkId = getWorkflowLinkId();

		encyWorkflowLinkCacheModel.groupId = getGroupId();

		encyWorkflowLinkCacheModel.companyId = getCompanyId();

		encyWorkflowLinkCacheModel.userId = getUserId();

		encyWorkflowLinkCacheModel.userName = getUserName();

		String userName = encyWorkflowLinkCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			encyWorkflowLinkCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			encyWorkflowLinkCacheModel.createDate = createDate.getTime();
		}
		else {
			encyWorkflowLinkCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			encyWorkflowLinkCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			encyWorkflowLinkCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		encyWorkflowLinkCacheModel.className = getClassName();

		String className = encyWorkflowLinkCacheModel.className;

		if ((className != null) && (className.length() == 0)) {
			encyWorkflowLinkCacheModel.className = null;
		}

		encyWorkflowLinkCacheModel.folderClassName = getFolderClassName();

		String folderClassName = encyWorkflowLinkCacheModel.folderClassName;

		if ((folderClassName != null) && (folderClassName.length() == 0)) {
			encyWorkflowLinkCacheModel.folderClassName = null;
		}

		encyWorkflowLinkCacheModel.folderPK = getFolderPK();

		encyWorkflowLinkCacheModel.workflowId = getWorkflowId();

		return encyWorkflowLinkCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<EncyWorkflowLink, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<EncyWorkflowLink, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EncyWorkflowLink, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(EncyWorkflowLink)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<EncyWorkflowLink, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<EncyWorkflowLink, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EncyWorkflowLink, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((EncyWorkflowLink)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, EncyWorkflowLink>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					EncyWorkflowLink.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _workflowLinkId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _className;
	private String _folderClassName;
	private long _folderPK;
	private long _workflowId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<EncyWorkflowLink, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((EncyWorkflowLink)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("workflowLinkId", _workflowLinkId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("className", _className);
		_columnOriginalValues.put("folderClassName", _folderClassName);
		_columnOriginalValues.put("folderPK", _folderPK);
		_columnOriginalValues.put("workflowId", _workflowId);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("workflowLinkId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("className", 256L);

		columnBitmasks.put("folderClassName", 512L);

		columnBitmasks.put("folderPK", 1024L);

		columnBitmasks.put("workflowId", 2048L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private EncyWorkflowLink _escapedModel;

}