create table E3Entry (
	mvccVersion LONG default 0 not null,
	uuid_ VARCHAR(75) null,
	headId LONG,
	head BOOLEAN,
	entry_id LONG not null primary key,
	groupId LONG,
	companyId LONG,
	entry_modifier_id LONG,
	entry_modifier_name VARCHAR(256) null,
	entry_created DATE null,
	entry_modified DATE null,
	entry_author_id LONG,
	entry_author_name VARCHAR(256) null,
	entry_xid VARCHAR(256) null,
	entry_name VARCHAR(256) null,
	app_class VARCHAR(512) null,
	parent_id LONG,
	parent_field VARCHAR(128) null,
	json_values TEXT null,
	status LONG
);

create table E3EntryVersion (
	e3EntryVersionId LONG not null primary key,
	version INTEGER,
	uuid_ VARCHAR(75) null,
	entry_id LONG,
	groupId LONG,
	companyId LONG,
	entry_modifier_id LONG,
	entry_modifier_name VARCHAR(256) null,
	entry_created DATE null,
	entry_modified DATE null,
	entry_author_id LONG,
	entry_author_name VARCHAR(256) null,
	entry_xid VARCHAR(256) null,
	entry_name VARCHAR(256) null,
	app_class VARCHAR(512) null,
	parent_id LONG,
	parent_field VARCHAR(128) null,
	json_values TEXT null,
	status LONG
);