create table pdr_attribute (
	mvccVersion LONG default 0 not null,
	attributeId LONG not null primary key,
	fullName VARCHAR(75) null,
	parentId LONG,
	nameCz VARCHAR(75) null,
	nameEn VARCHAR(75) null,
	nameSk VARCHAR(75) null,
	order_ INTEGER,
	level INTEGER,
	idsPath VARCHAR(75) null,
	description VARCHAR(75) null,
	personalDataTypeId LONG,
	tagName VARCHAR(75) null,
	isRoA BOOLEAN,
	isRtP BOOLEAN,
	separatorBefore VARCHAR(75) null,
	separatorAfter VARCHAR(75) null,
	isMerge BOOLEAN,
	isLabel BOOLEAN,
	isObject BOOLEAN,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null
);

create table pdr_mapping (
	mvccVersion LONG default 0 not null,
	mappingId LONG not null primary key,
	title VARCHAR(75) null,
	systemId LONG,
	tableId LONG,
	columnId LONG,
	attributeId LONG,
	mappingRules VARCHAR(75) null,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	state_ VARCHAR(75) null,
	stateByUserId LONG,
	stateByUserName VARCHAR(75) null,
	stateDate DATE null
);