/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package cz.csob.ency.workflow.uad.exporter;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.user.associated.data.exporter.DynamicQueryUADExporter;

import cz.csob.ency.workflow.model.EncyWorkflowLink;
import cz.csob.ency.workflow.service.EncyWorkflowLinkLocalService;
import cz.csob.ency.workflow.uad.constants.EncyWorkflowUADConstants;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the ency workflow definition link UAD exporter.
 *
 * <p>
 * This implementation exists only as a container for the default methods
 * generated by ServiceBuilder. All custom service methods should be put in
 * {@link cz.csob.ency.workflow.uad.exporter.EncyWorkflowLinkUADExporter}.
 * </p>
 *
 * @author Miroslav Čermák
 * @generated
 */
public abstract class BaseEncyWorkflowLinkUADExporter
	extends DynamicQueryUADExporter<EncyWorkflowLink> {

	@Override
	public Class<EncyWorkflowLink> getTypeClass() {
		return EncyWorkflowLink.class;
	}

	@Override
	protected ActionableDynamicQuery doGetActionableDynamicQuery() {
		return encyWorkflowLinkLocalService.
			getActionableDynamicQuery();
	}

	@Override
	protected String[] doGetUserIdFieldNames() {
		return EncyWorkflowUADConstants.
			USER_ID_FIELD_NAMES_ENCY_WORKFLOW_DEFINITION_LINK;
	}

	@Override
	protected String toXmlString(
		EncyWorkflowLink encyWorkflowLink) {

		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append("cz.csob.ency.workflow.model.EncyWorkflowLink");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>workflowLinkId</column-name><column-value><![CDATA[");
		sb.append(encyWorkflowLink.getWorkflowLinkId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(encyWorkflowLink.getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(encyWorkflowLink.getUserName());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	@Reference
	protected EncyWorkflowLinkLocalService
		encyWorkflowLinkLocalService;

}