/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package cz.csob.ency.pdr.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the PDRAttribute service. Represents a row in the &quot;pdr_attribute&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>cz.csob.ency.pdr.model.impl.PDRAttributeModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>cz.csob.ency.pdr.model.impl.PDRAttributeImpl</code>.
 * </p>
 *
 * @author Miroslav Čermák
 * @see PDRAttribute
 * @generated
 */
@ProviderType
public interface PDRAttributeModel
	extends BaseModel<PDRAttribute>, GroupedModel, MVCCModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a pdr attribute model instance should use the {@link PDRAttribute} interface instead.
	 */

	/**
	 * Returns the primary key of this pdr attribute.
	 *
	 * @return the primary key of this pdr attribute
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this pdr attribute.
	 *
	 * @param primaryKey the primary key of this pdr attribute
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this pdr attribute.
	 *
	 * @return the mvcc version of this pdr attribute
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this pdr attribute.
	 *
	 * @param mvccVersion the mvcc version of this pdr attribute
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the attribute ID of this pdr attribute.
	 *
	 * @return the attribute ID of this pdr attribute
	 */
	public long getAttributeId();

	/**
	 * Sets the attribute ID of this pdr attribute.
	 *
	 * @param attributeId the attribute ID of this pdr attribute
	 */
	public void setAttributeId(long attributeId);

	/**
	 * Returns the full name of this pdr attribute.
	 *
	 * @return the full name of this pdr attribute
	 */
	@AutoEscape
	public String getFullName();

	/**
	 * Sets the full name of this pdr attribute.
	 *
	 * @param fullName the full name of this pdr attribute
	 */
	public void setFullName(String fullName);

	/**
	 * Returns the parent ID of this pdr attribute.
	 *
	 * @return the parent ID of this pdr attribute
	 */
	public long getParentId();

	/**
	 * Sets the parent ID of this pdr attribute.
	 *
	 * @param parentId the parent ID of this pdr attribute
	 */
	public void setParentId(long parentId);

	/**
	 * Returns the name cz of this pdr attribute.
	 *
	 * @return the name cz of this pdr attribute
	 */
	@AutoEscape
	public String getNameCz();

	/**
	 * Sets the name cz of this pdr attribute.
	 *
	 * @param nameCz the name cz of this pdr attribute
	 */
	public void setNameCz(String nameCz);

	/**
	 * Returns the name en of this pdr attribute.
	 *
	 * @return the name en of this pdr attribute
	 */
	@AutoEscape
	public String getNameEn();

	/**
	 * Sets the name en of this pdr attribute.
	 *
	 * @param nameEn the name en of this pdr attribute
	 */
	public void setNameEn(String nameEn);

	/**
	 * Returns the name sk of this pdr attribute.
	 *
	 * @return the name sk of this pdr attribute
	 */
	@AutoEscape
	public String getNameSk();

	/**
	 * Sets the name sk of this pdr attribute.
	 *
	 * @param nameSk the name sk of this pdr attribute
	 */
	public void setNameSk(String nameSk);

	/**
	 * Returns the order of this pdr attribute.
	 *
	 * @return the order of this pdr attribute
	 */
	public int getOrder();

	/**
	 * Sets the order of this pdr attribute.
	 *
	 * @param order the order of this pdr attribute
	 */
	public void setOrder(int order);

	/**
	 * Returns the level of this pdr attribute.
	 *
	 * @return the level of this pdr attribute
	 */
	public int getLevel();

	/**
	 * Sets the level of this pdr attribute.
	 *
	 * @param level the level of this pdr attribute
	 */
	public void setLevel(int level);

	/**
	 * Returns the ids path of this pdr attribute.
	 *
	 * @return the ids path of this pdr attribute
	 */
	@AutoEscape
	public String getIdsPath();

	/**
	 * Sets the ids path of this pdr attribute.
	 *
	 * @param idsPath the ids path of this pdr attribute
	 */
	public void setIdsPath(String idsPath);

	/**
	 * Returns the description of this pdr attribute.
	 *
	 * @return the description of this pdr attribute
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this pdr attribute.
	 *
	 * @param description the description of this pdr attribute
	 */
	public void setDescription(String description);

	/**
	 * Returns the personal data type ID of this pdr attribute.
	 *
	 * @return the personal data type ID of this pdr attribute
	 */
	public long getPersonalDataTypeId();

	/**
	 * Sets the personal data type ID of this pdr attribute.
	 *
	 * @param personalDataTypeId the personal data type ID of this pdr attribute
	 */
	public void setPersonalDataTypeId(long personalDataTypeId);

	/**
	 * Returns the tag name of this pdr attribute.
	 *
	 * @return the tag name of this pdr attribute
	 */
	@AutoEscape
	public String getTagName();

	/**
	 * Sets the tag name of this pdr attribute.
	 *
	 * @param tagName the tag name of this pdr attribute
	 */
	public void setTagName(String tagName);

	/**
	 * Returns the is ro a of this pdr attribute.
	 *
	 * @return the is ro a of this pdr attribute
	 */
	public boolean getIsRoA();

	/**
	 * Returns <code>true</code> if this pdr attribute is is ro a.
	 *
	 * @return <code>true</code> if this pdr attribute is is ro a; <code>false</code> otherwise
	 */
	public boolean isIsRoA();

	/**
	 * Sets whether this pdr attribute is is ro a.
	 *
	 * @param isRoA the is ro a of this pdr attribute
	 */
	public void setIsRoA(boolean isRoA);

	/**
	 * Returns the is rt p of this pdr attribute.
	 *
	 * @return the is rt p of this pdr attribute
	 */
	public boolean getIsRtP();

	/**
	 * Returns <code>true</code> if this pdr attribute is is rt p.
	 *
	 * @return <code>true</code> if this pdr attribute is is rt p; <code>false</code> otherwise
	 */
	public boolean isIsRtP();

	/**
	 * Sets whether this pdr attribute is is rt p.
	 *
	 * @param isRtP the is rt p of this pdr attribute
	 */
	public void setIsRtP(boolean isRtP);

	/**
	 * Returns the separator before of this pdr attribute.
	 *
	 * @return the separator before of this pdr attribute
	 */
	@AutoEscape
	public String getSeparatorBefore();

	/**
	 * Sets the separator before of this pdr attribute.
	 *
	 * @param separatorBefore the separator before of this pdr attribute
	 */
	public void setSeparatorBefore(String separatorBefore);

	/**
	 * Returns the separator after of this pdr attribute.
	 *
	 * @return the separator after of this pdr attribute
	 */
	@AutoEscape
	public String getSeparatorAfter();

	/**
	 * Sets the separator after of this pdr attribute.
	 *
	 * @param separatorAfter the separator after of this pdr attribute
	 */
	public void setSeparatorAfter(String separatorAfter);

	/**
	 * Returns the is merge of this pdr attribute.
	 *
	 * @return the is merge of this pdr attribute
	 */
	public boolean getIsMerge();

	/**
	 * Returns <code>true</code> if this pdr attribute is is merge.
	 *
	 * @return <code>true</code> if this pdr attribute is is merge; <code>false</code> otherwise
	 */
	public boolean isIsMerge();

	/**
	 * Sets whether this pdr attribute is is merge.
	 *
	 * @param isMerge the is merge of this pdr attribute
	 */
	public void setIsMerge(boolean isMerge);

	/**
	 * Returns the is label of this pdr attribute.
	 *
	 * @return the is label of this pdr attribute
	 */
	public boolean getIsLabel();

	/**
	 * Returns <code>true</code> if this pdr attribute is is label.
	 *
	 * @return <code>true</code> if this pdr attribute is is label; <code>false</code> otherwise
	 */
	public boolean isIsLabel();

	/**
	 * Sets whether this pdr attribute is is label.
	 *
	 * @param isLabel the is label of this pdr attribute
	 */
	public void setIsLabel(boolean isLabel);

	/**
	 * Returns the is object of this pdr attribute.
	 *
	 * @return the is object of this pdr attribute
	 */
	public boolean getIsObject();

	/**
	 * Returns <code>true</code> if this pdr attribute is is object.
	 *
	 * @return <code>true</code> if this pdr attribute is is object; <code>false</code> otherwise
	 */
	public boolean isIsObject();

	/**
	 * Sets whether this pdr attribute is is object.
	 *
	 * @param isObject the is object of this pdr attribute
	 */
	public void setIsObject(boolean isObject);

	/**
	 * Returns the group ID of this pdr attribute.
	 *
	 * @return the group ID of this pdr attribute
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this pdr attribute.
	 *
	 * @param groupId the group ID of this pdr attribute
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this pdr attribute.
	 *
	 * @return the company ID of this pdr attribute
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this pdr attribute.
	 *
	 * @param companyId the company ID of this pdr attribute
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this pdr attribute.
	 *
	 * @return the user ID of this pdr attribute
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this pdr attribute.
	 *
	 * @param userId the user ID of this pdr attribute
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this pdr attribute.
	 *
	 * @return the user uuid of this pdr attribute
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this pdr attribute.
	 *
	 * @param userUuid the user uuid of this pdr attribute
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this pdr attribute.
	 *
	 * @return the user name of this pdr attribute
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this pdr attribute.
	 *
	 * @param userName the user name of this pdr attribute
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this pdr attribute.
	 *
	 * @return the create date of this pdr attribute
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this pdr attribute.
	 *
	 * @param createDate the create date of this pdr attribute
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this pdr attribute.
	 *
	 * @return the modified date of this pdr attribute
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this pdr attribute.
	 *
	 * @param modifiedDate the modified date of this pdr attribute
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	@Override
	public PDRAttribute cloneWithOriginalValues();

}