/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package cz.csob.ency.pdr.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the PDRMapping service. Represents a row in the &quot;pdr_mapping&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>cz.csob.ency.pdr.model.impl.PDRMappingModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>cz.csob.ency.pdr.model.impl.PDRMappingImpl</code>.
 * </p>
 *
 * @author Miroslav Čermák
 * @see PDRMapping
 * @generated
 */
@ProviderType
public interface PDRMappingModel
	extends BaseModel<PDRMapping>, GroupedModel, MVCCModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a pdr mapping model instance should use the {@link PDRMapping} interface instead.
	 */

	/**
	 * Returns the primary key of this pdr mapping.
	 *
	 * @return the primary key of this pdr mapping
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this pdr mapping.
	 *
	 * @param primaryKey the primary key of this pdr mapping
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this pdr mapping.
	 *
	 * @return the mvcc version of this pdr mapping
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this pdr mapping.
	 *
	 * @param mvccVersion the mvcc version of this pdr mapping
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the mapping ID of this pdr mapping.
	 *
	 * @return the mapping ID of this pdr mapping
	 */
	public long getMappingId();

	/**
	 * Sets the mapping ID of this pdr mapping.
	 *
	 * @param mappingId the mapping ID of this pdr mapping
	 */
	public void setMappingId(long mappingId);

	/**
	 * Returns the title of this pdr mapping.
	 *
	 * @return the title of this pdr mapping
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this pdr mapping.
	 *
	 * @param title the title of this pdr mapping
	 */
	public void setTitle(String title);

	/**
	 * Returns the system ID of this pdr mapping.
	 *
	 * @return the system ID of this pdr mapping
	 */
	public long getSystemId();

	/**
	 * Sets the system ID of this pdr mapping.
	 *
	 * @param systemId the system ID of this pdr mapping
	 */
	public void setSystemId(long systemId);

	/**
	 * Returns the table ID of this pdr mapping.
	 *
	 * @return the table ID of this pdr mapping
	 */
	public long getTableId();

	/**
	 * Sets the table ID of this pdr mapping.
	 *
	 * @param tableId the table ID of this pdr mapping
	 */
	public void setTableId(long tableId);

	/**
	 * Returns the column ID of this pdr mapping.
	 *
	 * @return the column ID of this pdr mapping
	 */
	public long getColumnId();

	/**
	 * Sets the column ID of this pdr mapping.
	 *
	 * @param columnId the column ID of this pdr mapping
	 */
	public void setColumnId(long columnId);

	/**
	 * Returns the attribute ID of this pdr mapping.
	 *
	 * @return the attribute ID of this pdr mapping
	 */
	public long getAttributeId();

	/**
	 * Sets the attribute ID of this pdr mapping.
	 *
	 * @param attributeId the attribute ID of this pdr mapping
	 */
	public void setAttributeId(long attributeId);

	/**
	 * Returns the mapping rules of this pdr mapping.
	 *
	 * @return the mapping rules of this pdr mapping
	 */
	@AutoEscape
	public String getMappingRules();

	/**
	 * Sets the mapping rules of this pdr mapping.
	 *
	 * @param mappingRules the mapping rules of this pdr mapping
	 */
	public void setMappingRules(String mappingRules);

	/**
	 * Returns the group ID of this pdr mapping.
	 *
	 * @return the group ID of this pdr mapping
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this pdr mapping.
	 *
	 * @param groupId the group ID of this pdr mapping
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this pdr mapping.
	 *
	 * @return the company ID of this pdr mapping
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this pdr mapping.
	 *
	 * @param companyId the company ID of this pdr mapping
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this pdr mapping.
	 *
	 * @return the user ID of this pdr mapping
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this pdr mapping.
	 *
	 * @param userId the user ID of this pdr mapping
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this pdr mapping.
	 *
	 * @return the user uuid of this pdr mapping
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this pdr mapping.
	 *
	 * @param userUuid the user uuid of this pdr mapping
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this pdr mapping.
	 *
	 * @return the user name of this pdr mapping
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this pdr mapping.
	 *
	 * @param userName the user name of this pdr mapping
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this pdr mapping.
	 *
	 * @return the create date of this pdr mapping
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this pdr mapping.
	 *
	 * @param createDate the create date of this pdr mapping
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this pdr mapping.
	 *
	 * @return the modified date of this pdr mapping
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this pdr mapping.
	 *
	 * @param modifiedDate the modified date of this pdr mapping
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the state of this pdr mapping.
	 *
	 * @return the state of this pdr mapping
	 */
	@AutoEscape
	public String getState();

	/**
	 * Sets the state of this pdr mapping.
	 *
	 * @param state the state of this pdr mapping
	 */
	public void setState(String state);

	/**
	 * Returns the state by user ID of this pdr mapping.
	 *
	 * @return the state by user ID of this pdr mapping
	 */
	public long getStateByUserId();

	/**
	 * Sets the state by user ID of this pdr mapping.
	 *
	 * @param stateByUserId the state by user ID of this pdr mapping
	 */
	public void setStateByUserId(long stateByUserId);

	/**
	 * Returns the state by user uuid of this pdr mapping.
	 *
	 * @return the state by user uuid of this pdr mapping
	 */
	public String getStateByUserUuid();

	/**
	 * Sets the state by user uuid of this pdr mapping.
	 *
	 * @param stateByUserUuid the state by user uuid of this pdr mapping
	 */
	public void setStateByUserUuid(String stateByUserUuid);

	/**
	 * Returns the state by user name of this pdr mapping.
	 *
	 * @return the state by user name of this pdr mapping
	 */
	@AutoEscape
	public String getStateByUserName();

	/**
	 * Sets the state by user name of this pdr mapping.
	 *
	 * @param stateByUserName the state by user name of this pdr mapping
	 */
	public void setStateByUserName(String stateByUserName);

	/**
	 * Returns the state date of this pdr mapping.
	 *
	 * @return the state date of this pdr mapping
	 */
	public Date getStateDate();

	/**
	 * Sets the state date of this pdr mapping.
	 *
	 * @param stateDate the state date of this pdr mapping
	 */
	public void setStateDate(Date stateDate);

	@Override
	public PDRMapping cloneWithOriginalValues();

}