/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package cz.csob.ency.modules.e3.entry.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.version.VersionModel;

import java.io.Serializable;

import java.util.Date;
import java.util.Map;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the E3EntryVersion service. Represents a row in the &quot;E3EntryVersion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>cz.csob.ency.modules.e3.entry.model.impl.E3EntryVersionModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>cz.csob.ency.modules.e3.entry.model.impl.E3EntryVersionImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see E3EntryVersion
 * @generated
 */
@ProviderType
public interface E3EntryVersionModel
	extends BaseModel<E3EntryVersion>, GroupedModel, ShardedModel,
			VersionModel<E3Entry> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a e3 entry version model instance should use the {@link E3EntryVersion} interface instead.
	 */

	/**
	 * Returns the primary key of this e3 entry version.
	 *
	 * @return the primary key of this e3 entry version
	 */
	@Override
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this e3 entry version.
	 *
	 * @param primaryKey the primary key of this e3 entry version
	 */
	@Override
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the e3 entry version ID of this e3 entry version.
	 *
	 * @return the e3 entry version ID of this e3 entry version
	 */
	public long getE3EntryVersionId();

	/**
	 * Sets the e3 entry version ID of this e3 entry version.
	 *
	 * @param e3EntryVersionId the e3 entry version ID of this e3 entry version
	 */
	public void setE3EntryVersionId(long e3EntryVersionId);

	/**
	 * Returns the version of this e3 entry version.
	 *
	 * @return the version of this e3 entry version
	 */
	@Override
	public int getVersion();

	/**
	 * Sets the version of this e3 entry version.
	 *
	 * @param version the version of this e3 entry version
	 */
	@Override
	public void setVersion(int version);

	/**
	 * Returns the uuid of this e3 entry version.
	 *
	 * @return the uuid of this e3 entry version
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this e3 entry version.
	 *
	 * @param uuid the uuid of this e3 entry version
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the entry ID of this e3 entry version.
	 *
	 * @return the entry ID of this e3 entry version
	 */
	public long getEntryId();

	/**
	 * Sets the entry ID of this e3 entry version.
	 *
	 * @param entryId the entry ID of this e3 entry version
	 */
	public void setEntryId(long entryId);

	/**
	 * Returns the group ID of this e3 entry version.
	 *
	 * @return the group ID of this e3 entry version
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this e3 entry version.
	 *
	 * @param groupId the group ID of this e3 entry version
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this e3 entry version.
	 *
	 * @return the company ID of this e3 entry version
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this e3 entry version.
	 *
	 * @param companyId the company ID of this e3 entry version
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this e3 entry version.
	 *
	 * @return the user ID of this e3 entry version
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this e3 entry version.
	 *
	 * @param userId the user ID of this e3 entry version
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this e3 entry version.
	 *
	 * @return the user uuid of this e3 entry version
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this e3 entry version.
	 *
	 * @param userUuid the user uuid of this e3 entry version
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this e3 entry version.
	 *
	 * @return the user name of this e3 entry version
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this e3 entry version.
	 *
	 * @param userName the user name of this e3 entry version
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this e3 entry version.
	 *
	 * @return the create date of this e3 entry version
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this e3 entry version.
	 *
	 * @param createDate the create date of this e3 entry version
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this e3 entry version.
	 *
	 * @return the modified date of this e3 entry version
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this e3 entry version.
	 *
	 * @param modifiedDate the modified date of this e3 entry version
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the author ID of this e3 entry version.
	 *
	 * @return the author ID of this e3 entry version
	 */
	public long getAuthorId();

	/**
	 * Sets the author ID of this e3 entry version.
	 *
	 * @param authorId the author ID of this e3 entry version
	 */
	public void setAuthorId(long authorId);

	/**
	 * Returns the author name of this e3 entry version.
	 *
	 * @return the author name of this e3 entry version
	 */
	@AutoEscape
	public String getAuthorName();

	/**
	 * Sets the author name of this e3 entry version.
	 *
	 * @param authorName the author name of this e3 entry version
	 */
	public void setAuthorName(String authorName);

	/**
	 * Returns the xid of this e3 entry version.
	 *
	 * @return the xid of this e3 entry version
	 */
	@AutoEscape
	public String getXid();

	/**
	 * Sets the xid of this e3 entry version.
	 *
	 * @param xid the xid of this e3 entry version
	 */
	public void setXid(String xid);

	/**
	 * Returns the name of this e3 entry version.
	 *
	 * @return the name of this e3 entry version
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this e3 entry version.
	 *
	 * @param name the name of this e3 entry version
	 */
	public void setName(String name);

	/**
	 * Returns the app class of this e3 entry version.
	 *
	 * @return the app class of this e3 entry version
	 */
	@AutoEscape
	public String getAppClass();

	/**
	 * Sets the app class of this e3 entry version.
	 *
	 * @param appClass the app class of this e3 entry version
	 */
	public void setAppClass(String appClass);

	/**
	 * Returns the parent ID of this e3 entry version.
	 *
	 * @return the parent ID of this e3 entry version
	 */
	public long getParentId();

	/**
	 * Sets the parent ID of this e3 entry version.
	 *
	 * @param parentId the parent ID of this e3 entry version
	 */
	public void setParentId(long parentId);

	/**
	 * Returns the parent field of this e3 entry version.
	 *
	 * @return the parent field of this e3 entry version
	 */
	@AutoEscape
	public String getParentField();

	/**
	 * Sets the parent field of this e3 entry version.
	 *
	 * @param parentField the parent field of this e3 entry version
	 */
	public void setParentField(String parentField);

	/**
	 * Returns the values of this e3 entry version.
	 *
	 * @return the values of this e3 entry version
	 */
	public Map<String, Serializable> getValues();

	/**
	 * Sets the values of this e3 entry version.
	 *
	 * @param values the values of this e3 entry version
	 */
	public void setValues(Map<String, Serializable> values);

	/**
	 * Returns the status of this e3 entry version.
	 *
	 * @return the status of this e3 entry version
	 */
	public long getStatus();

	/**
	 * Sets the status of this e3 entry version.
	 *
	 * @param status the status of this e3 entry version
	 */
	public void setStatus(long status);

}