/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package cz.csob.ency.cds.demands.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the CdsDemandGdprInfo service. Represents a row in the &quot;CdsDemands_CdsDemandGdprInfo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>cz.csob.ency.cds.demands.model.impl.CdsDemandGdprInfoModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>cz.csob.ency.cds.demands.model.impl.CdsDemandGdprInfoImpl</code>.
 * </p>
 *
 * @author Miroslav Čermák
 * @see CdsDemandGdprInfo
 * @generated
 */
@ProviderType
public interface CdsDemandGdprInfoModel extends BaseModel<CdsDemandGdprInfo> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a cds demand gdpr info model instance should use the {@link CdsDemandGdprInfo} interface instead.
	 */

	/**
	 * Returns the primary key of this cds demand gdpr info.
	 *
	 * @return the primary key of this cds demand gdpr info
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this cds demand gdpr info.
	 *
	 * @param primaryKey the primary key of this cds demand gdpr info
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this cds demand gdpr info.
	 *
	 * @return the uuid of this cds demand gdpr info
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this cds demand gdpr info.
	 *
	 * @param uuid the uuid of this cds demand gdpr info
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the gdpr info ID of this cds demand gdpr info.
	 *
	 * @return the gdpr info ID of this cds demand gdpr info
	 */
	public long getGdprInfoId();

	/**
	 * Sets the gdpr info ID of this cds demand gdpr info.
	 *
	 * @param gdprInfoId the gdpr info ID of this cds demand gdpr info
	 */
	public void setGdprInfoId(long gdprInfoId);

	/**
	 * Returns the demand ID of this cds demand gdpr info.
	 *
	 * @return the demand ID of this cds demand gdpr info
	 */
	public long getDemandId();

	/**
	 * Sets the demand ID of this cds demand gdpr info.
	 *
	 * @param demandId the demand ID of this cds demand gdpr info
	 */
	public void setDemandId(long demandId);

	/**
	 * Returns the title of this cds demand gdpr info.
	 *
	 * @return the title of this cds demand gdpr info
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this cds demand gdpr info.
	 *
	 * @param title the title of this cds demand gdpr info
	 */
	public void setTitle(String title);

	/**
	 * Returns the description of this cds demand gdpr info.
	 *
	 * @return the description of this cds demand gdpr info
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this cds demand gdpr info.
	 *
	 * @param description the description of this cds demand gdpr info
	 */
	public void setDescription(String description);

	/**
	 * Returns the is employee of this cds demand gdpr info.
	 *
	 * @return the is employee of this cds demand gdpr info
	 */
	public boolean getIsEmployee();

	/**
	 * Returns <code>true</code> if this cds demand gdpr info is is employee.
	 *
	 * @return <code>true</code> if this cds demand gdpr info is is employee; <code>false</code> otherwise
	 */
	public boolean isIsEmployee();

	/**
	 * Sets whether this cds demand gdpr info is is employee.
	 *
	 * @param isEmployee the is employee of this cds demand gdpr info
	 */
	public void setIsEmployee(boolean isEmployee);

	/**
	 * Returns the employee category of this cds demand gdpr info.
	 *
	 * @return the employee category of this cds demand gdpr info
	 */
	@AutoEscape
	public String getEmployeeCategory();

	/**
	 * Sets the employee category of this cds demand gdpr info.
	 *
	 * @param employeeCategory the employee category of this cds demand gdpr info
	 */
	public void setEmployeeCategory(String employeeCategory);

	/**
	 * Returns the employee reasoning of this cds demand gdpr info.
	 *
	 * @return the employee reasoning of this cds demand gdpr info
	 */
	@AutoEscape
	public String getEmployeeReasoning();

	/**
	 * Sets the employee reasoning of this cds demand gdpr info.
	 *
	 * @param employeeReasoning the employee reasoning of this cds demand gdpr info
	 */
	public void setEmployeeReasoning(String employeeReasoning);

	/**
	 * Returns the is client of this cds demand gdpr info.
	 *
	 * @return the is client of this cds demand gdpr info
	 */
	public boolean getIsClient();

	/**
	 * Returns <code>true</code> if this cds demand gdpr info is is client.
	 *
	 * @return <code>true</code> if this cds demand gdpr info is is client; <code>false</code> otherwise
	 */
	public boolean isIsClient();

	/**
	 * Sets whether this cds demand gdpr info is is client.
	 *
	 * @param isClient the is client of this cds demand gdpr info
	 */
	public void setIsClient(boolean isClient);

	/**
	 * Returns the client category of this cds demand gdpr info.
	 *
	 * @return the client category of this cds demand gdpr info
	 */
	@AutoEscape
	public String getClientCategory();

	/**
	 * Sets the client category of this cds demand gdpr info.
	 *
	 * @param clientCategory the client category of this cds demand gdpr info
	 */
	public void setClientCategory(String clientCategory);

	/**
	 * Returns the client reasoning of this cds demand gdpr info.
	 *
	 * @return the client reasoning of this cds demand gdpr info
	 */
	@AutoEscape
	public String getClientReasoning();

	/**
	 * Sets the client reasoning of this cds demand gdpr info.
	 *
	 * @param clientReasoning the client reasoning of this cds demand gdpr info
	 */
	public void setClientReasoning(String clientReasoning);

	/**
	 * Returns the user ID of this cds demand gdpr info.
	 *
	 * @return the user ID of this cds demand gdpr info
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this cds demand gdpr info.
	 *
	 * @param userId the user ID of this cds demand gdpr info
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this cds demand gdpr info.
	 *
	 * @return the user uuid of this cds demand gdpr info
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this cds demand gdpr info.
	 *
	 * @param userUuid the user uuid of this cds demand gdpr info
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this cds demand gdpr info.
	 *
	 * @return the user name of this cds demand gdpr info
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this cds demand gdpr info.
	 *
	 * @param userName the user name of this cds demand gdpr info
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this cds demand gdpr info.
	 *
	 * @return the create date of this cds demand gdpr info
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this cds demand gdpr info.
	 *
	 * @param createDate the create date of this cds demand gdpr info
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this cds demand gdpr info.
	 *
	 * @return the modified date of this cds demand gdpr info
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this cds demand gdpr info.
	 *
	 * @param modifiedDate the modified date of this cds demand gdpr info
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public CdsDemandGdprInfo cloneWithOriginalValues();

}